### ISSUE TITLE
Test against kerberized Kafka environments

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream-binder-kafka#10]
See https://github.com/spring-projects/spring-integration-kafka/issues/123#issuecomment-232620365

**Comment by sabbyanandan** [comment]
As of today, we have support to pass kerberos settings both at the producer and consumer level. They are passed as k/v pairs chained under `.configuration` property. 

For example, at the producer level, you'd pass settings like: `spring.cloud.stream.kafka.bindings.<channelName>.producer.configuration.sasl.kerberos.service.name=VALUE`.

**Comment by sabbyanandan** [comment]
The list of all consumer properties in Kafka 0.9 is here: http://kafka.apache.org/090/documentation.html#newconsumerconfigs

(_they can all be prefixed with spring.cloud.stream.kafka.bindings.<channelName>.consumer.configuration_) 

The list of all producer properties in Kafka 0.9 is here: http://kafka.apache.org/090/documentation.html#producerconfigs

(_they can all be prefixed with spring.cloud.stream.kafka.bindings.<channelName>.producer.configuration_)

Here is an example on configuring clients and brokers for kerberos: http://kafka.apache.org/documentation.html#security_sasl_kerberos
