### ISSUE TITLE
multiple Flux suppliers don't work

### ISSUE THREAD

**Issue by benkeil** [spring-cloud/spring-cloud-stream-binder-kafka#1011]
I have a spring cloud stream kafka application with two suppliers.
But it only works, if I comment one out (both are working if the other one is not there).

```
@Bean
public Supplier<Flux<Message<Product>>> productSupplier() {
    return () -> Flux.from(emitter -> {
        while (true) {
            try {
                emitter.onNext(createProductMessage());
                Thread.sleep(1000);
            } catch (Exception e) {
                // ignore
            }
        }
    });
}
```

and in another class

```
@Bean
public Supplier<Flux<Message<Channel>>> channelSupplier() {
    return () -> Flux.from(emitter -> {
        while (true) {
            try {
                emitter.onNext(createChannelMessage());
                Thread.sleep(1000);
            } catch (Exception e) {
                // ignore
            }
        }
    });
}
```

**Edit**

When I change both suppliers to work without `Flux`, everything works.

**Comment by garyrussell** [comment]
See [the documentation](https://docs.spring.io/spring-cloud-stream/docs/3.1.0/reference/html/spring-cloud-stream.html#spring-cloud-stream-overview-producing-consuming-messages).

When there is more than one binding, you must specify them using the `spring.cloud.function.definition` property (`productSupplier;channelSupplier`).

**Comment by benkeil** [comment]
> When I change both suppliers to work without Flux, everything works.

It has nothing to do with a wrong configuration...

**Comment by garyrussell** [comment]
If you are still having problems, reopen this and provide a complete, minimal, example that exhibits the behavior you see.
