### ISSUE TITLE
Exception - y: java.lang.NoClassDefFoundError: io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe

### ISSUE THREAD

**Issue by manthak** [spring-cloud/spring-cloud-stream-binder-kafka#1013]
Hi 

I am getting the following exception- while using the spring-cloud-stream-binder-kafka 
Confluent version is 5.5.1 

Caused by: java.lang.NoClassDefFoundError: io/confluent/kafka/serializers/AbstractKafkaSchemaSerDe
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_221]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_221]

POM details

 <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.0.RELEASE</version>
        <relativePath/> 
    </parent>
    <groupId>com.moodys.analyst</groupId>
    <artifactId>analyst-kafka-producer</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>analystProducer</name>
    <description>Demo project for Spring Boot</description>

    <properties>
        <java.version>8</java.version>
        <avro.version>1.10.0</avro.version>
        <confluent.version>5.5.1</confluent.version>
        <spring-cloud.version>Hoxton.SR8</spring-cloud.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-binder-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.victools</groupId>
            <artifactId>jsonschema-generator</artifactId>
            <version>4.16.0</version>
        </dependency>
         <dependency>
    		<groupId>io.confluent</groupId>
   			 <artifactId>common-utils</artifactId>
    		 <version>${confluent.version}</version>
    		 <scope>system</scope> 
    		<systemPath>${basedir}/src/main/resources/lib/common-utils-5.5.1.jar</systemPath>
    		</dependency>
    	<dependency>
    		<groupId>io.confluent</groupId>
   			 <artifactId>common-utils</artifactId>
    		 <version>${confluent.version}</version>
    		 <scope>system</scope> 
    		<systemPath>${basedir}/src/main/resources/lib/common-config-5.5.1.jar</systemPath>
		</dependency>

**Comment by sobychacko** [comment]
@manthak We need more information on this issue. It's not clear why you are running into this error. From what I can see, that is a schema registry related class. If you can provide a small sample with minimal dependencies to reproduce this issue with instructions, we can then further triage. Thanks.

**Comment by manthak** [comment]
Soby

Thank you very much for reaching out to me, we realized that it was an issue with dependency management and error went away when we cleaned up the POM file.

The case can be closed.

Regards

  *   Kamy Mantha

**Comment by sobychacko** [comment]
Thanks for letting us know that it was a non-issue. Closing the issue.
