### ISSUE TITLE
unable to customize AdminClientConfig programmatically

### ISSUE THREAD

**Issue by colaho** [spring-cloud/spring-cloud-stream-binder-kafka#1014]
Due to security reason, our kafka credentials are stored in aws secrets manager and are extracted on the fly during the application bootstrap. With the `ProducerConfigCustomizer` and `ConsumerConfigCustomizer` beans, we can connect to our cluster successfully by injecting the SASL config into the producer / consumer properties. However, we are getting this error in the log.

> 2021-01-15 17:51:52.660  INFO 1 --- [| adminclient-6] o.a.k.c.a.i.AdminMetadataManager         : [AdminClient clientId=adminclient-6] Metadata update failed
> org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call.

From [`KafkaTopicProvisioner`](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka-core/src/main/java/org/springframework/cloud/stream/binder/kafka/provisioning/KafkaTopicProvisioner.java). it seems that the provisioner always creates the AdminClient from properties. Is there any way which we could customize the AdminClientConfig via a `AdminClientConfigCustomizer` bean? Thanks

**Comment by sobychacko** [comment]
Hi @colaho Here is a sample that demonstrates how to access a Kaka cluster with security by providing binder level properties. By providing it at the binder level, these security properties are applicable to all the components such as producer, consumer and admin client. 
https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/kafka-security-samples/kafka-ssl-demo

This is the config for this project: https://github.com/spring-cloud/spring-cloud-stream-samples/blob/master/kafka-security-samples/kafka-ssl-demo/src/main/resources/application.yml

Here is another project that uses multi-binder support with security: https://github.com/spring-cloud/spring-cloud-stream-samples/blob/master/multi-binder-samples/kafka-multi-binder-jaas/src/main/resources/application.yml

Please let us know if they satisfy your use case. Thanks!

**Comment by colaho** [comment]
Hi @sobychacko, our case is a bit different from the examples. 

Because the credentials are secretly stored on the aws (in another words, we won't even know it in production) and are rotated regularly, we could not put it statically in the properties. As mentioned, for consumer and producer, we used the `ProducerConfigCustomizer` and `ConsumerConfigCustomizer` beans to dynamically inject the credentials and it works.

```java
    @Bean
    public ProducerConfigCustomizer producerConfigCustomizer() {
        return props -> {
            props.put(CommonClientConfigs.SECURITY_PROTOCOL_CONFIG, "SASL_SSL");
            props.put(SaslConfigs.SASL_MECHANISM, "SCRAM-SHA-256");
            props.put(SaslConfigs.SASL_JAAS_CONFIG, String.format("%s required username=\"%s\" password=\"%s\";",
                    ScramLoginModule.class.getName(),
                    awsSecret.get("USERNAME"),
                    awsSecret.get("PASSWORD")
            ));
        };
    }
```

But this doesn't apply to the AdminClient because there is no such `AdminClientConfigCustomizer` now.

**Comment by sobychacko** [comment]
@colaho Sure, that makes sense. We can think about adding a hook to customize the admin config. We will let you know if there are any updates.
