### ISSUE TITLE
Help exposing KafkaBinderHealthIndicator / KafkaStreamsBinderHealthIndicator

### ISSUE THREAD

**Issue by rfogel** [spring-cloud/spring-cloud-stream-binder-kafka#1015]
Hello.

Im in need to create a custom healthcheck endpoint for my project and I steped up on this little problem. Both indicators work fine but they have package visibility so I can't autowired them to build my own custom message. Is there a way to retrieve these beans and get the information I need?

Thanks in advanced.

**Comment by sobychacko** [comment]
@rfogel which version of the binder are you using? We can make the configuration public so that you can override them.

**Comment by rfogel** [comment]
Hi sobychacko. Here the versions im using:

![image](https://user-images.githubusercontent.com/3649288/105057793-7bce8800-5a6d-11eb-8f9a-422a0627f5f5.png)

Thanks man!

**Comment by sobychacko** [comment]
@rfogel I made those beans public and pushed a commit on both master and 3.0.x branches. If you update your binder versions to `3.0.11.BUILD-SNAPSHOT`, you should be able to get the changes. Please let us know if you see any issues. There will be a release for `3.0.11.RELEASE` later this month.

**Comment by rfogel** [comment]
Thanks @sobychacko. Unfortunately I can't test it because I'm getting this error:

**Type org.springframework.cloud.stream.binder.kafka.utils.DlqDestinationResolver not present**

`Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.stream.binder.kafka.utils.DlqDestinationResolver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	... 89 common frames omitted`

It seems to start at 3.0.9 version although.

This is my application.yml:

``
spring:
  cloud:
    stream:
      default-binder: kafka
      default:
        producer:
          useNativeEncoding: true
        consumer:
          useNativeEncoding: true
      kafka:
        default:
          consumer:
            enableDlq: true
            dlqName: cib.ppt.ic.mktrdl.contracts-out-all.DLT
            autoCommitOnError: true
        binder:
          jaas:
            enabled: false
            controlFlag: optional
          consumer-properties:
            value.deserializer: com.hortonworks.registries.schemaregistry.serdes.avro.kafka.KafkaAvroDeserializer
            schema.registry.url: ${app.schema-registry.url}
          producer-properties:
            value.serializer: com.hortonworks.registries.schemaregistry.serdes.avro.kafka.KafkaAvroSerializer
            schema.registry.url: ${app.schema-registry.url}
            auto.register.schemas: false
            value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
          brokers: ${app.kafka.bootstrap-servers}
          autoCreateTopics: false
``

Any idea what it is?
