### ISSUE TITLE
Reinstate `spring-cloud-stream-binder-kafka-test-support` artifact

### ISSUE THREAD

**Issue by reda-alaoui** [spring-cloud/spring-cloud-stream-binder-kafka#102]
Currently, I have a bunch of Integration tests based on Spring Cloud Stream `TestSupportBinder`.
But I want my tests to go deeper by binding directly to a kafka embedded instance.

I am seeing a lot of spring cloud stream projects refering to `spring-cloud-stream-binder-kafka-test-support`. Where I can find its rabbit mq sibling `spring-cloud-stream-binder-rabbit-test-support`, the former can't be found.
Did it ever exist?

In `spring-cloud-stream-samples/multibinder` there is an import for this module:
```xml
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-stream-binder-rabbit-test-support</artifactId>
	<scope>test</scope>
</dependency>
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-stream-binder-kafka-test-support</artifactId>
	<scope>test</scope>
</dependency>
```
It seems it should allow to import spring-kafka-test which contains `KafkaEmbedded`.

**Comment by reda-alaoui** [comment]
Fetching the history, I found that the project was deleted with https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/866eaf4a25802c31c8e418eb56ce43eee79390e9

Is there a real reason? Without it, people must configure the `spring-kafka-test` dependency themselves.

**Comment by mbogoevici** [comment]
> Without it, people must configure the spring-kafka-test dependency themselves.

That's intentional. There's no need for an additional level of indirection. Also, the end user knows what Spring Kafka version they are using.

**Comment by mbogoevici** [comment]
We will correct the samples to use the `spring-kafka-test` themselves.

**Comment by reda-alaoui** [comment]
Hello,

The spring-kafka version is technically unknown to the end user. 
How can I get the spring-kafka-test artifact without passing the spring-kafka version my test while using:
```xml
<dependency>
   <groupId>org.springframework.cloud</groupId>
   <artifactId>spring-cloud-stream-dependencies</artifactId>
   <version>Brooklyn.SR2</version>
   <type>pom</type>
   <scope>import</scope>
</dependency>
```

**Comment by mbogoevici** [comment]
Ah, you're using Brooklyn. For the `Brooklyn` release train and Boot 1.4.4 you can use the Spring Kafka 1.0.5 as version (unless you're overriding that to use 0.10.x clients). 

Starting with the Chelsea release train which is based on Spring Boot 1.5,  the dependency for `spring-kafka-test` is managed by Spring Boot directly so you don't need to specify it. I would suggest to start using `Chelsea.BUILD-SNAPSHOT` now, since we're going to have a release candidate next week.

**Comment by reda-alaoui** [comment]
But I don't use Spring Boot :/

**Comment by mbogoevici** [comment]
Ok. I suppose that we can reinstate the previous `spring-cloud-stream-binder-kafka-test-support` module to provide some dependency management.

**Comment by mbogoevici** [comment]
@reda-alaoui thanks for bringing this up and for the clarifications. We're going to add this back - feel free to open a PR - we do welcome contributions.

**Comment by reda-alaoui** [comment]
Thank you :)
