### ISSUE TITLE
java.lang.ClassCastException: class java.lang.Object cannot be cast to class com.example.Sensor

### ISSUE THREAD

**Issue by samragu** [spring-cloud/spring-cloud-stream-binder-kafka#1022]
**Description of the problem**:
With Spring Boot 2.3.4.RELEASE and SCSt Hoxton.SR8, Avro message is not being converted into Java object. A ClassCastException is thrown

**Reproduce using the attached artifacts**:
[avro.zip](https://github.com/spring-cloud/spring-cloud-stream/files/5491555/avro.zip)

**Versions**:
SCSt: Hoxton.SR8
Spring Boot: 2.3.4.RELEASE

StackOverflow question and comments - https://stackoverflow.com/questions/64651330/scst-java-lang-classcastexception-class-java-lang-object-cannot-be-cast-to-cl

**Comment by sobychacko** [comment]
@samragu I tried to reproduce your issue using Kafka binder, but couldn't. I was able to run the application fine and see the proper `Sensor` output. I added this as a new [sample](https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/schema-registry-samples/spring-schema-registry-kafka-standalone) in the samples repository. Please take a look and see what is different for you. The fact that you are using the Rabbit binder should not make a difference from what I can see. 

Closing the issue. Please feel free to reopen, if you still think that this is a bug.
