### ISSUE TITLE
Support Instrumentation of Spring Cloud Stream Kafka Streams Binder

### ISSUE THREAD

**Issue by codependent** [spring-cloud/spring-cloud-stream-binder-kafka#1025]
This issue is related to https://github.com/spring-cloud/spring-cloud-sleuth/issues/1832
I've updated the repository with a pure Java version: https://github.com/codependent/sleuth-kafka-streams/tree/java-version

This is a feature request to add support for Spring Cloud Stream Kafka Streams binder. 

Current support only addresses instrumentation of Spring Cloud Stream Kafka binder, so applications based on `KStream`s, whose [programming model](https://docs.spring.io/spring-cloud-stream-binder-kafka/docs/3.1.0/reference/html/spring-cloud-stream-binder-kafka.html#_programming_model) relies on the `KStream` concept instead of `Message`, have no way to instrument the correlation information.

It would be great that Sleuth dealt with it or at least provided some documentation about how to manually instrument it.

**Comment by sobychacko** [comment]
@codependent There were some discussions prior on this [here](https://github.com/spring-cloud/spring-cloud-sleuth/issues/1363). If you read the discussion, there is already a way that you can use `KafkaStreamsTracing` from Kafka Streams binder. Is this issue related to those discussions or something different? 

We also filed a previous issue around this: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/699.
There is a sample provided in which we demonstrate how  `KafkaStreamsTracing` works with the binder. 

If you could chime in on how exactly this issue corresponds to those discussions, we can use that as a springboard to explore this further. Thanks!

**Comment by codependent** [comment]
Hi @sobychacko, I missed that issue, I'm closing this one and continue the discussion in the open one.
