### ISSUE TITLE
Consuming Batch property name error

### ISSUE THREAD

**Issue by liam-bin0** [spring-cloud/spring-cloud-stream-binder-kafka#1032]
Hello.

The consumer property name has not been changed in other documents. (#902)

(https://docs.spring.io/spring-cloud-stream-binder-kafka/docs/3.0.11.RELEASE/reference/html/spring-cloud-stream-binder-kafka.html#_consuming_batches)

Please check this. Thanks!

**Comment by sobychacko** [comment]
@liam-bin0 Thanks for pointing this out. The original commit needed to go to another docs file.  I applied the change to the proper file on master and backported it to `3.0.x`. The next release will pick up this change.
