### ISSUE TITLE
RecordMetadata channel not found when custom converter is used

### ISSUE THREAD

**Issue by UgiR** [spring-cloud/spring-cloud-stream-binder-kafka#1036]
When a custom `MessageConverter` is used, and `recordMetadataChannel` property is set, the following error occurs:

>org.springframework.messaging.MessageHandlingException: error occurred during processing message in 'MethodInvokingMessageProcessor' [org.springframework.integration.handler.MethodInvokingMessageProcessor@d39f66a]; nested exception is org.springframework.expression.spel.SpelEvaluationException: EL1004E: Method call: Method onKafkaAck(org.springframework.messaging.support.GenericMessage) cannot be found on type com.example.demo.KafkaAckHandler$$EnhancerBySpringCGLIB$$d69f5d5c, failedMessage=GenericMessage [payload=byte[13], headers={id=7c61be89-ee4d-cf11-64eb-8192438e135c, contentType=application/thing, kafka_recordMetadata=thing-topic-0@0, timestamp=1614982181425}]

Here is a reproducer: https://github.com/UgiR/SCSt-repro

**Comment by garyrussell** [comment]
```java
    @ServiceActivator(inputChannel = "kafkaAckListener")
    void onKafkaAck(final Message<?> message) {
        System.out.println("Got Kafka producer acknowledgment");
    }
```

The method needs to be `public`.

**Comment by UgiR** [comment]
Thanks @garyrussell , can confirm it works when method is public.

Out of curiousity, why does the non-public method work when contentType is `application/json`?

**Comment by garyrussell** [comment]
I am not sure; but, for some reason, we're falling back to use SpEL to invoke the method

>SpelEvaluationException: EL1004E

and SpEL can only invoke public methods.

If you can provide the alternate configuration for your sample where it works, I can take a look next week.

**Comment by UgiR** [comment]
Yes, the alternate configuration is in the application.yml of the repro, commented out for easy swap

**Comment by garyrussell** [comment]
We're falling back to SpEL because we're getting a `MessageConversionException`

>org.springframework.messaging.converter.MessageConversionException: No converter found from actual payload type 'byte[]' to expected payload type 'java.lang.Object', failedMessage=GenericMessage [payload=byte[13], headers={id=da58080e-c146-38a2-b109-5e1963c2d823, contentType=application/thing, kafka_recordMetadata=thing-topic-0@0, timestamp=1614984207919}]

After a quick look, it seems your `ThingConverter` needs

```java
    ThingConverter() {
		super(MimeType.valueOf("application/thing"));
	}

	@Override
    protected boolean supports(Class<?> aClass) {
        return Object.class.isAssignableFrom(aClass);
    }

```

(Because the generic type of Message in the method is `<?>`).

And you need to implement 

```java
	@Nullable
	protected Object convertFromInternal(
			Message<?> message, Class<?> targetClass, @Nullable Object conversionHint) {

		return null;
	}
```

**Comment by garyrussell** [comment]
You could also change the ack handler to this...

```java
    @ServiceActivator(inputChannel = "kafkaAckListener")
    void onKafkaAck(final Message<byte[]> message) {
        System.out.println("Got Kafka producer acknowledgment");
    }
```

To avoid converting back to a thing.

**Comment by UgiR** [comment]
For the `onKafkaAck` to be as general-purpose as possible, would `Message<byte[]>` be the safest/most tolerant way to declare that method argument (instead of `Message<?>`? The way I want to use it would not even access the payload anyway, only the headers.

**Comment by garyrussell** [comment]
As long as you don't have `useNativeEncoding` set to `true`, the payload will always be a `byte[]`.

However, if you are only interested in the headers, you can use

```java
    @ServiceActivator(inputChannel = "kafkaAckListener")
    void onKafkaAck(@Header(KafkaHeaders.RECORD_METADATA) RecordMetadata meta, @Header(...) ...) {
        System.out.println("Got Kafka producer acknowledgment " + meta);
    }
```

and then no payload conversion will be attempted.

**Comment by garyrussell** [comment]
By the way

```java
@EmbeddedKafka(bootstrapServersProperty = "spring.kafka.bootstrap-servers")
```

is better than hard-coding port 9092 for the embedded broker. If there's a real broker running on that port, the tests will fail.

**Comment by UgiR** [comment]
`@Header(KafkaHeaders.RECORD_METADATA) RecordMetadata meta`

> and then no payload conversion will be attempted.

Ah, perfect! This is great feedback, thank you very much.

> is better than hard-coding port 9092 for the embedded broker

Good tip, noted!
