### ISSUE TITLE
Set custom BatchMessageConverter for consumer binding in batch mode

### ISSUE THREAD

**Issue by ferblaca** [spring-cloud/spring-cloud-stream-binder-kafka#1043]
spring-cloud-stream-binder-kafka 3.1.1
spring-integration-kafka 5.4.3
spring-kafka 2.6.5

We are not able to set up a custom BatchMessageConverter from Spring cloud stream for the Kafka binder.

We are using the property 'converterBeanName' in the consumer configured as batch mode, so when configured in the KafkaMessageChannelBinder class it gets the bean as converter, but it only supports MessagingMessageConverter.class

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/v3.1.1/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java#L1046

so when creating the consumer we can never set the converter in the BatchListener because MessagingMessageConverter implements RecordMessageConverter and never BatchMessageConverter...

https://github.com/spring-projects/spring-integration-kafka/blob/master/src/main/java/org/springframework/integration/kafka/inbound/KafkaMessageDrivenChannelAdapter.java#L138

Is it possible to use a custom batch converter in batch mode?

**Comment by garyrussell** [comment]
As a work around, you can add a `ListenerContainerCustomizer` `@Bean`.

```java
@Bean
public ListenerContainerCustomizer<AbstractMessageListenerContainer<?, ?>> customizer() {
	return (container, dest, group) -> container.setBatchErrorHandler(...);
}
```

**Comment by ferblaca** [comment]
Thanks @garyrussell for the workaround, but I don't see how to set the BatchMesageConverter from the ConcurrentMessageListenerContainer container... I could only set the error handler for Batching....

**Comment by garyrussell** [comment]
Sorry, I misread the question as `BatchErrorHandler`, not `BatchMessageConverter`.

Yes, it will be fixed in a future release, but I can't say when that will be.

There is currently no easy work around. It can be done with reflection if you would be comfortable with that. If so, I can work it up for you.

**Comment by ferblaca** [comment]
Thanks @garyrussell! in principle we are going to wait for the release that fixes it so we don't have to use reflection.

Anyway, if there is anything we can help you with, let us know.

**Comment by ferblaca** [comment]
Blocked by issue https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/1043
