### ISSUE TITLE
APM support

### ISSUE THREAD

**Issue by nirajhx** [spring-cloud/spring-cloud-stream-binder-kafka#1047]
Not a bug or feature request but more like a support request.

I have a Spring Webflux application with spring-cloud-stream-binder-kafka integrated, I am facing some load issues and want to monitor the Kafka message processing. I am using newrelic as an APM but by default, it's not able to detect the Kafka consumer tasks, newrelic team asked me to do manual instrumentation which starts the Kafka consumers, for doing so I want to know the class name & method name which I should instrument manually in newrelic which triggers the bean registered methods in my application.

**Comment by sabbyanandan** [comment]
Hi, @nirajhx. Spring Cloud Stream workloads can be instrumented through Micrometer to support [NewRelic and a variety of other APM systems](https://micrometer.io/docs). All you need is the right Micrometer dependency in the classpath. There's nothing more we need to do in Spring Cloud Stream proper to get this working.

Experiment with the binder and the Micrometer dependencies of choice.
