### ISSUE TITLE
Update Kafka Binder Configuration at runtime

### ISSUE THREAD

**Issue by TechUnsupportGuy** [spring-cloud/spring-cloud-stream-binder-kafka#1056]
I am using Spring Cloud Stream along with Kafka binders to connect to a Kafka cluster using SASL. The SASL config looks as follows:

```
spring.cloud.stream.kafka.binder.configuration.sasl.mechanism=SCRAM-SHA-512
spring.cloud.stream.kafka.binder.configuration.sasl.jaas.config= .... required username="..." password="..."
spring.cloud.stream.kafka.binder.configuration.security.protocol=SASL_SSL
```

My application would receive updated username and passwords periodically and I want to update the SASL Kafka configuration with the latest credentials at runtime. I need help with the same, I have tried googling and searched [stackoverflow ](https://stackoverflow.com/questions/66813966/spring-cloud-stream-kafka-binder-configuration-update-at-runtime) but can't find any solution for this.

**Comment by olegz** [comment]
There is no reason to double post in SO and here. It's not going to make things any faster and actually creates a bit of confusion. Please give someone a chance to respond first. 

Also, we generally do not use this issue tracker for questions.

**Comment by TechUnsupportGuy** [comment]
Apologies for the confusion due to posting on SO as well, however I couldn't get any solution for this on SO and anywhere else. Some help on possible approaches to solve this would be appreciated.
