### ISSUE TITLE
Healthcheck is not showing actual status of consumer

### ISSUE THREAD

**Issue by tdanylchuk** [spring-cloud/spring-cloud-stream-binder-kafka#1059]
The issue we had were fixed in - https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/991
Although In case if real broker altering is needed and broker will have INCREMENTAL_ALTER_CONFIGS disabled, consumer will have continuous attempts to alter broker config with healthcheck being in UP status at the same time no messages will be consumed.

I feel that health check should be up only if listener container started and ready to receive messages, the issue above is only one of the possible issues we may encounter with ```KafkaMessageListenerContainer``` and I believe ```KafkaMessageChannelBinder``` should expose ```isRunning``` status of ```KafkaMessageListenerContainer``` to health endpoint.

As a result showing just a status of topics that are in use is not enough to understand if the binder is healthy and up & running.

**Comment by sobychacko** [comment]
@tdanylchuk Thanks for filing the issue. Now I understand the context. Are you planning to PR a solution for this?

**Comment by tdanylchuk** [comment]
I planned, i was curious about your opinion on this, there is no refference inside binder object about crated listener container, so in order to get it work on creation we need to preserve it as field inside binder, so healthcheck can use it for retrieving isRunning flag.

**Comment by sobychacko** [comment]
Yes, I think you can add a field for the `ListenerContainer` and then provide an accessor. In the case of multiple input bindings (for e.g. using `StreamListener` or the tuple approach in the functional model), you probably have to consider creating a map of containers and somehow key them so that you can access the proper container from the health check. cc @garyrussell What do you think about that approach?

**Comment by garyrussell** [comment]
I am not sure I follow; if the provisioning fails, there is no listener container - what am I missing?

**Comment by tdanylchuk** [comment]
I guess that could be a case, then kafka binder should be down, right?
also what if provisioning were successful, but for some reason listener container stop running (plenty of reasons i guess might occur) then kafka binder also should be down imo.

**Comment by djangofan** [comment]
Personally, my experience with the health check on **spring-cloud-stream-binder-kafka**  is that it says healthy if it is able to simply ping the kafka endpoint BUT will not say unhealthy if there is any problem actually consuming/producing.   I would be nice if this healthcheck would/could cache unhealthy requests as a temporary bad-state.

**Comment by tdanylchuk** [comment]
Hi guys, I might work on this next week, just to be sure we all aligned is proposed idea ok with @garyrussell @sobychacko ?
