### ISSUE TITLE
Upgrade spring-kafka to 2.7.0

### ISSUE THREAD

**Issue by chenrujun** [spring-cloud/spring-cloud-stream-binder-kafka#1062]
Refs: https://repo.spring.io/milestone/org/springframework/boot/spring-boot-dependencies/2.5.0-RC1/spring-boot-dependencies-2.5.0-RC1.pom

**Comment by garyrussell** [comment]
This will not happen until the next minor version (not in a patch release). If you want to override the version yourself, see https://docs.spring.io/spring-kafka/docs/2.6.7/reference/html/#update-deps

**Comment by chenrujun** [comment]
Hi, @garyrussell .

Thank you for your response. When will next minor version release?

**Comment by sabbyanandan** [comment]
Spring Cloud Stream 3.2.0 will ship with Spring Cloud's [2021.0.0](https://github.com/spring-cloud/spring-cloud-release/milestone/109) - please follow the timelines through this milestone.
