### ISSUE TITLE
Enable Kafka Streams binder for Graal native compilation

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream-binder-kafka#1064]

**Comment by sabbyanandan** [comment]
Verification on the KTable is still pending.

**Comment by sobychacko** [comment]
Issue moved to [spring-cloud/spring-cloud-stream #2323](https://github.com/spring-cloud/spring-cloud-stream/issues/2323) via [**ZenHub**](https://www.zenhub.com/)
