### ISSUE TITLE
Error for kstream Inclusion (listener' cannot be null)

### ISSUE THREAD

**Issue by outminder** [spring-cloud/spring-cloud-stream-binder-kafka#1071]
[https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/1030](url)
This states a similar error and the solution seems to be in 3.1.3-SNAPSHOT, but I cannot find this version in maven repo. I am facing this error 
`nested exception is org.springframework.kafka.KafkaException: Could not start stream: ; nested exception is java.lang.IllegalArgumentException: 'listener' cannot be null
`
Any clues what can be done to solve this?

**Comment by garyrussell** [comment]
Add this repo to your pom/build.gradle.

https://repo.spring.io/snapshot      

However, don't use snapshots in production.

**Comment by outminder** [comment]
@garyrussell  thanks after including the snapshot, it resolves the problem. I hope this will be part of the release soon
