### ISSUE TITLE
ConsumerConfigCustomizer/ProducerConfigCustomizer in Cloud Binder for  kafka-streams

### ISSUE THREAD

**Issue by bek-tws** [spring-cloud/spring-cloud-stream-binder-kafka#1072]
Hi, 

Similar to [1014](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/1014 ), due to security reasons, we need to set the SASL/SCRAM credentials at runtime in our Kafka Streams app. The documentation seems to indicate we should be able to achieve this by providing ConsumerConfigCustomizer/ProducerConfigCustomizer. However, I am not actually seeing this being used anywhere in the Kafka-streams config code (only in Kafka binding). Interestingly enough, AdminConfigCustomizer is being properly passed in [here](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/9e4a1075d437f2e6aa7dad0a38d8286de94234a4/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/KTableBinderConfiguration.java#L51) and works as expected. 

If this is currently not supported, what is the recommended way to set the client configs at runtime?

**Comment by sobychacko** [comment]
@bek-tws Apologies for the delay in getting back to you on this. In Kafka Streams binder, you can use the `StreamsBuilderFactoryBeanConfigurer` for customizing the consumer and producer configurations. For example, you can do this to customize the credentials.
```
@Bean
public StreamsBuilderFactoryBeanConfigurer customizer() {
	return fb -> {
		final Properties streamsConfiguration = fb.getStreamsConfiguration();
		streamsConfiguration.put("foo", "bar");  // just as an example
                 // Similarly, you can provide SASL/SCRAM properties.
	};
}
```

Is this sufficient for your use case? I don't see much advantage for providing consumer/producer config customizers in Kafka Streams binder as ultimately we have to modify the Streams configuration anyway and that is already possible through the configurer as shown above.

**Comment by sobychacko** [comment]
@bek-tws Closing this issue. Feel free to re-open, if you are finding issues with the suggestions I made above.
