### ISSUE TITLE
Suspicious multiplication of ScheduledExecutorService in the method "bindTo" of class "KafkaBinderMetrics"

### ISSUE THREAD

**Issue by krocodl** [spring-cloud/spring-cloud-stream-binder-kafka#1081]
@Override
	public void bindTo(MeterRegistry registry) {
		this.scheduler = Executors.newScheduledThreadPool(this.binder.getTopicsInUse().size());
...
}

As a result, during the initialization of the application at some point, we can observe a lot of threads (for 33 topics, for example, more than 550), the maintenance of which slows down the process and sometimes even results in OOM

**Comment by sobychacko** [comment]
@krocodl The thread pool, in this case, is upper bounded by the maximum number of topics. Therefore, you should only observe 33 threads at the most for 33 topics, I am not sure how you get to see 550. Did you do any further triaging to find out how it spawns that many threads?

**Comment by krocodl** [comment]
First of all you created the pool with 1 thread. After you lost the reference on it and created the pool with 2 threads. But, the first pool is not yet collected by GC and now you have 3 threads together. And so on. Each thread does nothing, but it takes system memory and takes part in the scheduling process. After 30 topics, you potentially have (30+1)*15=465 threads. It is already the serious load on the switching contexts. 
In my case, the concurrency of the consumer was 5 and cpu was bounded by K8 settings. As a result these pools were not collected by GC in time and the instance was crashed with OOM. In the dump I found more than 2000 threads and start my investigations about strange count of threads. 
I think, that it is necessary to shutdown the existing pool before the new creation.

**Comment by krocodl** [comment]
After that I started the service locally, waited for the end of the initialization and immediately made thread dump. In it I found all these threads.

**Comment by sobychacko** [comment]
@krocodl Thank you for this analysis. We will try to fix this asap. Pull requests are welcomed to address this issue. If you plan to fix it, please let us know. Otherwise, we will do it on our end.

**Comment by krocodl** [comment]
My next work day is Tuesday. I will try to make a patch that will subscribe to the same event and keep track of the fact that the scheduler field has changed, causing a cleanup for the old version of the value. This will allow me to fix the problem quickly and finally test my hypothesis. In that case, I will make a patch for binder as well. Thanks for the quick response!

**Comment by sobychacko** [comment]
Sure, thanks for the update. We have a release scheduled for `3.1.3` next week. Hopefully, we can try to include it in the release.

**Comment by krocodl** [comment]
Proof of the suspicions (the thread dump after start and how "pool-x-thread-y" like threads are created):

![image](https://user-images.githubusercontent.com/22099242/119345938-d553f700-bc99-11eb-9166-d9dfade79d38.png)

![image](https://user-images.githubusercontent.com/22099242/119345993-e7359a00-bc99-11eb-9476-244a533312a4.png)

**Comment by krocodl** [comment]
The possible fast fix:

@Component
public class KafkaBinderMetricsFinder implements ApplicationListener<ContextRefreshedEvent> {

    public static final String KAFKA_BINDER_METRICS_BEAN_NAME = "kafkaBinderMetrics";
    private final List<ApplicationContext> childContexts = new ArrayList<>();

    @Override
    public void onApplicationEvent(ContextRefreshedEvent event) {
        childContexts.add((ApplicationContext) event.getSource());
    }

    public KafkaBinderMetrics getKafkaBinderMetrics() {
        return childContexts.stream()
                .filter(c -> c.containsBean(KAFKA_BINDER_METRICS_BEAN_NAME))
                .map(c -> (KafkaBinderMetrics) c.getBean(KAFKA_BINDER_METRICS_BEAN_NAME))
                .findAny().orElseThrow(() -> new IllegalStateException("Can't find any " + KAFKA_BINDER_METRICS_BEAN_NAME));
    }
}

@Slf4j
@Component
@RequiredArgsConstructor
public class KafkaBinderMetricsFixer implements ApplicationListener<BindingCreatedEvent> {

    private final KafkaBinderMetricsFinder finder;

    private KafkaBinderMetrics kafkaBinderMetrics;
    private ScheduledThreadPoolExecutor lastExecutor = null;

    @Override
    public void onApplicationEvent(BindingCreatedEvent event) {
        ScheduledThreadPoolExecutor current = getCurrentExecutor();
        if (lastExecutor == null) {
            lastExecutor = current;
        } else if (current.getPoolSize() > lastExecutor.getPoolSize()) {
            lastExecutor.shutdown();
            lastExecutor = current;
        }
    }

    private ScheduledThreadPoolExecutor getCurrentExecutor() {
        kafkaBinderMetrics = kafkaBinderMetrics == null ? finder.getKafkaBinderMetrics() : kafkaBinderMetrics;
        try {
            return (ScheduledThreadPoolExecutor) FieldUtils.readField(kafkaBinderMetrics, "scheduler", true);
        } catch (Exception ex) {
            throw new IllegalStateException("Can't extract ScheduledThreadPoolExecutor from KafkaBinderMetrics", ex);
        }
    }
}
