### ISSUE TITLE
Support set kafkaTemplate for afterRollbackProcessor

### ISSUE THREAD

**Issue by mhyeon-lee** [spring-cloud/spring-cloud-stream-binder-kafka#1084]
The `setKafakOperations` method of `DefaultAfterRollbackProcessor` has been removed from the commit below.

https://github.com/spring-projects/spring-kafka/commit/47cb78d7179c47c0449134f0dd31084247846b5e#diff-ff8091e38ec4607d2a31e6c38245c6949ccaede0cad7686a367ae6660e2c3a35

Deprecate javadoc sets KafkaOperations and commitRecovered as constructors.
`in favor of DefaultAfterRollbackProcessor(BiConsumer, BackOff, KafkaOperations,  boolean).`

I want to inject KafkaOperations when KafkaMessageChannelBinder creates the DefaultAfterRollbackProcessor.
(https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/5f4e3eebc5ec664769107d089e60ec8457e81caa/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java#L746)

Can you support it or guide me on a good way to make it possible?

**Comment by garyrussell** [comment]
It's not clear what you are trying to do here; the `KafkaTemplate` is only used if `commitRecovered` is `true` in the DARP and the binder is transactional.

In any case, the binder's producer factory must be used for this to work properly.

How are you using it with older versions?

The binder should automatically configure the correct template rather than allowing a custom one to be set.

**Comment by mhyeon-lee** [comment]
I want to execute `this.kafkaTemplate.sendOffsetsToTransaction` in DefaultAfterRollbackProcessor.
https://github.com/spring-projects/spring-kafka/blob/main/spring-kafka/src/main/java/org/springframework/kafka/listener/DefaultAfterRollbackProcessor.java#L141

So I set commitRecovered true and kafkaTemplate in `ListenerContainerCustomizer` with older version.
``` java
@Bean
ListenerContainerCustomizer<AbstractMessageListenerContainer<?, ?>> listenerContainerCustomizer() {
    return (container, topic, group) -> {
        KafkaTransactionManager<?, ?> transactionManager =
				(KafkaTransactionManager<?, ?>)container.getContainerProperties().getTransactionManager();

        @SuppressWarnings("rawtypes")
        KafkaTemplate kafkaTemplate = new KafkaTemplate<>(transactionManager.getProducerFactory());

	DefaultAfterRollbackProcessor<?, ?> rollbackProcessor =
				(DefaultAfterRollbackProcessor<?, ?>)container.getAfterRollbackProcessor();
        rollbackProcessor.setCommitRecovered(true);
        rollbackProcessor.setKafkaOperations(kafkaTemplate);
    };
}
```

What about KafkaMessageChannelBinder reading `commit-recovered` property and creating DefaultAfterRollbackProcessor with constructor with correct KafkaTemplate?

**Comment by garyrussell** [comment]
Right - that's what I am thinking.

Thanks for confirming; I was guessing that you were using the proper producer factory.
