### ISSUE TITLE
Can't provision  topic consumer property from bindings

### ISSUE THREAD

**Issue by cterron** [spring-cloud/spring-cloud-stream-binder-kafka#1095]
I have a Spring Application using spring cloud and  I use the kafka binder and I'm trying to modify the topic properties of a consumer So I use this code in my application.yaml

```
spring.cloud.bindings.my-input-in-0.destination: some-topic
spring.cloud.kafka.bindings.my-input-in-0.consumer.topic.properties.cleanup.policy: compact

```
The code creates the topic but the clean.policy is always delete, it ignores the compact configuration.

But if I do the same thing with an producer bindings, works correctly:

```
spring.cloud.bindings.my-input-out-0.destination: some-topic
spring.cloud.kafka.bindings.my-input-out-0.producer.topic.properties.cleanup.policy: compact

```
Not sure why I can't create automatically the topic in a consumer with policy compact

**Comment by sobychacko** [comment]
@cterron I verified that the topic level `cleanup.policy` overrides work fine for both producer and consumer bindings. I noticed some typo in your configuration, but wonder if that is a copy/paste error. Following are the correct configs.
```
spring.cloud.stream.bindings.my-input-in-0.destination: some-topic
spring.cloud.stream.kafka.bindings.my-input-in-0.consumer.topic.properties.cleanup.policy: compact
spring.cloud.stream.bindings.my-input-out-0.destination: some-topic
spring.cloud.stream.kafka.bindings.my-input-out-0.producer.topic.properties.cleanup.policy: compact
```
If it still doesn't work for you, please share a small reproducible sample for us to further debug. Thank you!

**Comment by sobychacko** [comment]
Closing the issue. Feel free to re-open, if you are still facing issues. Thanks!
