### ISSUE TITLE
KafkaMessageChannelBinder.DlqSender.sendToDlq()  causes OutOfMemory exceptions for large messages

### ISSUE THREAD

**Issue by krocodl** [spring-cloud/spring-cloud-stream-binder-kafka#1112]
The problem code fragment:

`
					.append("'").append(" and payload='")
					.append(toDisplayString(ObjectUtils.nullSafeToString(value), 50))
`

If processing the messages results in an exception, we can expect to get an error log message and publishing into DLQ. 

But instead of this, ObjectUtils.nullSafeToString(record.value()) attempts to transform byte[] inside the String, where each byte is represented by about 5 bytes - something like ", 123".
As a result, we receive OOM, where the StringJoiner object occupies about half of the memory.

So, it is necessary to pass the "this.maxContentLogged" parameter inside the function "ObjectUtils.nullSafeToString" too, in order to prevent dumping the full byte array.

**Comment by krocodl** [comment]
BTW, this pattern is widely copied in Kafka-related projects. For example, we can see completely the same in the LoggingProducerListener.onError() and have completely the same OOM error with large messages.

**Comment by garyrussell** [comment]
Fix for the logging listener here https://github.com/spring-projects/spring-kafka/pull/1904

**Comment by sobychacko** [comment]
This is addressed through https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/1b26f5d6293e0b7d7d94d3100fd2e0434eadb2f6.
