### ISSUE TITLE
Kafka messages are being lost on INVALID_FETCH_SESSION_EPOCH 

### ISSUE THREAD

**Issue by mraliagha** [spring-cloud/spring-cloud-stream-binder-kafka#1118]
Recently we have observed that whenever there is an issue with INVALID_FETCH_SESSION_EPOCH from Kafka client the corresponding message is being skipped and hence it's lost in transit. INVALID_FETCH_SESSION_EPOCH is a known issue that was fixed in Kafka client 2.3.0 + according to [KAFKA-8052](https://issues.apache.org/jira/browse/KAFKA-8052). However, what we observed is when this is printed in logs the corresponding message is skipped entirely. This is impacting the at-least-once guaranteed message delivery part of Spring Cloud Stream, so I am not sure if this is a known issue or not. Obviously, with the most recent versions of Spring Cloud Stream, this issue should not happen but it raises a point that under similar circumstances a message could be skipped due. I just want to raise this issue here due to the importance of losing messages in transit. 

`"@timestamp":"2021-08-11T13:40:44.081+00:00","message":"[Consumer clientId=consumer-9, groupId=tag-modifiers] Node 17 was unable to process the fetch request with (sessionId=1995608629, epoch=331): INVALID_FETCH_SESSION_EPOCH.","logger_name":"org.apache.kafka.clients.FetchSessionHandler","thread_name":"KafkaConsumerDestination{consumerDestinationName='edit-tag', partitions=9, dlqName='dlq'}.container-0-C-1","level":"INFO","profile":"beats","microservice":"data-service"`

This issue is observed for Spring Cloud Stream 2.2.0 which uses Kafka client 2.0.1, but it should happen for any version of Spring Cloud Stream that uses Kafka client before 2.3.0.

I was under the impression that an exception in Kafka client to fetch a message should trigger the consumer to retry to fetch a message, but it seems that's not what's happening.

**Comment by sobychacko** [comment]
@mraliagha Could you give some more details on how we can reproduce this issue? You seem to indicate that you are using Spring Cloud Stream 2.2.0. That is a very old version. Did you try to upgrade to the latest 3.1.x releases and observed the same issue? If so, please provide some more context around this issue for reproducing. Then we will look into it further.

**Comment by mraliagha** [comment]
@sobychacko Reproducing this is quite hard because this is an intermittent behaviour in Kafka client.  It was fixed in Kafka client 2.3.0 and therefore it should not happen in any version of Spring Cloud Stream Kafka binder that uses 2.3.0+ Kafka client. Further description on how this issue could happen was shared in KAFKA-8052 which is not easy to reproduce tbh. It was fixed in https://github.com/apache/kafka/pull/6582 FYI. 

We are in the process of upgrading our applications to 3.1.3. However, this could take some time. In the meantime, I had two purposes for raising this issue:
- Is there any workaround we could have for older versions while we are waiting for all upgrades to finish?
- Does this issue raise another bug in Spring Cloud Stream that why such an issue at the client level could cause the entire message to be missed out? We cannot expect that there are no bugs in Kafka client, but I was hoping that such a case would cause consumers to reattempt to fetch a message instead of ignoring it entirely.

**Comment by garyrussell** [comment]
I don't think there is anything we can do; we can only get the records returned by the poll; if the poll doesn't return the record after this error then there is nothing Spring can do.

**Comment by mraliagha** [comment]
@garyrussell I see. But why the message was entirely skipped? It's like the message was committed without being polled.

**Comment by garyrussell** [comment]
I have no idea - ask the Kafka folks - as I said, it's totally out of our control.

**Comment by sobychacko** [comment]
@mraliagha Closing the issue. Please feel free to re-open with more context if you think that is necessary.
