### ISSUE TITLE
Function with batch producer fails during Kafka Avro serialization

### ISSUE THREAD

**Issue by serghei-ilin** [spring-cloud/spring-cloud-stream-binder-kafka#1121]
**Describe the issue**

Following the [documentation](https://github.com/spring-cloud/spring-cloud-stream/blob/main/docs/src/main/asciidoc/spring-cloud-stream.adoc#batch-producers) I have the following function which is used as Kafka processor using Spring Cloud Stream:
```
Function<Event, List<Message<IndexedRecord>>>
```
which has the following configuration:
```
spring.cloud.stream.bindings.fn-in-0.content-type=application/json

spring.cloud.stream.kafka.bindings.fn-in-0.consumer.configuration.key.deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.cloud.stream.kafka.bindings.fn-in-0.consumer.configuration.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.cloud.stream.kafka.bindings.fn-in-0.consumer.configuration.value.deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.cloud.stream.kafka.bindings.fn-in-0.consumer.configuration.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

spring.cloud.stream.bindings.fn-out-0.content-type=application/*+avro
spring.cloud.stream.bindings.fn-out-0.producer.use-native-encoding=true

spring.cloud.stream.kafka.bindings.fn-out-0.producer.configuration.schema.registry.url=${schema_registry_url}
spring.cloud.stream.kafka.bindings.fn-out-0.producer.configuration.key.serializer=org.apache.kafka.common.serialization.StringSerializer
spring.cloud.stream.kafka.bindings.fn-out-0.producer.configuration.value.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
```
The exception I am getting is:
```
Caused by: org.springframework.messaging.MessageHandlingException: error occurred in message handler
[org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder$ProducerConfigurationMessageHandler@5c64b969];
nested exception is java.lang.IllegalArgumentException: 
Unsupported Avro type. Supported types are null, Boolean, Integer, Long, Float, Double, String, byte[] and IndexedRecord
```
While debugging I see that serializer receives `List<Message<IndexedRecord>>` instead of individual objects. Seems like it's because the method:
```
org.springframework.integration.handler.AbstractMessageHandler#handleMessageInternal
```
always fallback to the last `doSendMessage` instead of the `if`s for list:
```
Object result = functionInvocationWrapper.apply((Message<byte[]>) message);
...
if (result instanceof Iterable) {
  ...
} else if (ObjectUtils.isArray(result) && !(result instanceof byte[])) {
  ...
} else {
  this.doSendMessage(result, message); // always fallback here
}
```
since the result of `functionInvocationWrapper` is always a `Message` with the `List` payload and that scenario is not expected.

Is that the expected behaviour or a bug for batch producer when Kafka is in use?

**Version of the framework**
Spring boot 2.5.3
Spring Cloud Stream 3.1.3
Spring Kafka 2.7.4
Spring Integration 5.5.2

**Comment by sobychacko** [comment]
@serghei-ilin This issue is already addressed in the core Spring Cloud Stream. See this commit: https://github.com/spring-cloud/spring-cloud-stream/commit/9d5679ae1d89e5d75416b359f815798fade534e1. Please update the following artifacts to `3.1.4-SNAPSHOT` and try again. The `3.1.4` release should contain the fixes. 

`spring-cloud-stream` - `3.1.4-SNAPSHOT`.
`spring-cloud-function-context` - `3.1.4-SNAPSHOT`. 

Closing the issue now. Feel free to re-open if you find further issues. Thank you!
