### ISSUE TITLE
auto topic creation setting does not work

### ISSUE THREAD

**Issue by zurada** [spring-cloud/spring-cloud-stream-binder-kafka#1134]
Hi,

I try to disable automatic topic creation and it does not work. Java app (kafka-streams binder) always creates the topic.
My config:
Broker: 
**auto.create.topics.enable = false**

and in application.properties:
**spring.cloud.stream.kafka.binder.consumer-properties.allow.auto.create.topics=false
spring.cloud.stream.kafka.binder.autoCreateTopics=false
spring.cloud.stream.kafka.binder.autoAddPartitions=false**

it does not create topic "exampleOutput" but still creates a topic "exampleInput" when defined in this way:
spring.cloud.stream.bindings.process-out-0.destination=exampleOutput
spring.cloud.stream.bindings.process-in-0.destination=exampleInput

My version of the project is:
		<spring-cloud.version>2020.0.3</spring-cloud.version>
with 
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.5.4</version>

The whole project reproducing the issue is:
https://github.com/zurada/kafka-streams-demo-config

Please help

![Screenshot from 2021-08-30 12-05-31](https://user-images.githubusercontent.com/32738441/131323355-a3ef78b1-4d1e-481e-8cd8-f4708074042b.png)
![Screenshot from 2021-08-30 12-06-37](https://user-images.githubusercontent.com/32738441/131323363-3f911e07-d854-480a-ac13-7bf1f790d478.png)
![Screenshot from 2021-08-30 11-59-28](https://user-images.githubusercontent.com/32738441/131323369-5ac7a4b6-0827-418b-8500-8c7982ca084f.png)
![Screenshot from 2021-08-30 12-08-17](https://user-images.githubusercontent.com/32738441/131323578-c402c87e-6578-43b9-9f17-a6aa3948f74c.png)
![Screenshot from 2021-08-30 12-08-42](https://user-images.githubusercontent.com/32738441/131323581-45217ad8-b09a-4604-bed9-4a2d2ced2c87.png)

**Comment by sobychacko** [comment]
@zurada These following properties need to be prefixed with `kafka.streams.binder` when using Kafka Streams binder.
```
spring.cloud.stream.kafka.streams.binder.consumer-properties.allow.auto.create.topics=false
spring.cloud.stream.kafka.streams.binder.autoCreateTopics=false
spring.cloud.stream.kafka.streams.binder.autoAddPartitions=false
```
I just tested your application with these properties and it is not auto-creating the input topic. Could you update these properties and test again?

**Comment by zurada** [comment]
Hi @sobychacko 

It indeed helped but does it mean that documentation is wrong?
https://docs.spring.io/spring-cloud-stream-binder-kafka/docs/3.0.10.RELEASE/reference/html/spring-cloud-stream-binder-kafka.html#_reference_guide

So instead of **spring.cloud.stream.kafka.binder** we have to use  **spring.cloud.stream.kafka.streams.binder**,

What about other properties mentioned in the docs? 
Does it mean that all the properties mentioned there should have the different prefix with "kafka.streams.binder"?

**Comment by sobychacko** [comment]
@zurada When you use Kafka Streams binder, you have to use the prefix `spring.cloud.stream.kafka.streams.binder`. The only exception for this rule is for broker property, for which you can use either prefix. You pointed to the Kafka binder docs. [Here](https://docs.spring.io/spring-cloud-stream-binder-kafka/docs/3.0.10.RELEASE/reference/html/spring-cloud-stream-binder-kafka.html#_kafka_streams_binder) are the Kafka Streams binder docs.

**Comment by sobychacko** [comment]
We can use this issue to clarify the docs.

**Comment by zurada** [comment]
@sobychacko thank you so much for the help.
That is very good to actually clarify the docs - why?
For example I try to enable all the other properties defined in the docs such as
**spring.cloud.stream.kafka.binder.transaction.transactionIdPrefix**
and I tried both
**spring.cloud.stream.kafka.binder.transaction.transactionIdPrefix**
and 
**spring.cloud.stream.kafka.binder.streams.binder.transaction.transactionIdPrefix**
and it does not work probably as expected (transaction.id = null).

Currently I had to do all the "transactional - related" properties in this way:

![Screenshot from 2021-09-02 11-09-46](https://user-images.githubusercontent.com/32738441/131816745-21fe0f9b-816f-40fb-b885-830b8d1b33fa.png)

Is it correct way to have transactional streams ? Or any easier way would be using somehow this "transactionIdPrefix"?

**Comment by sobychacko** [comment]
@zurada Apologies for not getting back to you earlier. The transaction properties look right to me in your configuration. I don't think there is another way to configure them in the binder. 

I [updated](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/ac0e462ed23409b6bdf65a3a1426101ef478e178) the docs with the prefix clarification for the Kafka Streams binder.
