### ISSUE TITLE
Random generated client id for the pollable consumers

### ISSUE THREAD

**Issue by sbogadhi** [spring-cloud/spring-cloud-stream-binder-kafka#1139]
Spring boot = 2.1.7 
spring-cloud-dependencies = Hoxton.SR4
Infrastructure = Pivotal Cloud foundry

Running multiple instances for high availability of the service. By default same client id is being generated in all the instances. 

Which making the partition rebalance always and consumption of the messages stops abruptly.

Hence looking for the unique client id for each instance when we scale up the services.

**Comment by garyrussell** [comment]
Spring Boot 2.1 is no longer supported; even 2.3 is out of Open Source support and will go completely end of life in February.

https://github.com/spring-projects/spring-boot/wiki/Supported-Versions

With current versions, you can use an environment variable to set the client id.

```properties
spring.cloud.stream.kafka.bindings.source.consumer.configuration.client.id=${client.id}
```

with environment variable `CLIENT_ID=foo` ...

```
ConsumerConfig values: 
	allow.auto.create.topics = true
	auto.commit.interval.ms = 100
	auto.offset.reset = latest
	bootstrap.servers = [localhost:9092]
	check.crcs = true
	client.dns.lookup = use_all_dns_ips
	client.id = foo
        ...
```

This may work with older versions too, but you should really upgrade to a supported version.
