### ISSUE TITLE
RangeAssignor doesn't work as expected.

### ISSUE THREAD

**Issue by metalpalo** [spring-cloud/spring-cloud-stream-binder-kafka#1153]
Hi,

I use spring could framework together with kafka binder. 
That means that our spring boot microservice connects to kafka server(cluster) and consumes messages from topics.

Here is setup exampl

1. 4 instances(pods) of application are connected to kafka
2. all pods have same counsumer group like **CS_Group**
3. all pods consume messages from 2 topics, let say **CS_Topic_1**, **CS_Topic_2**
4. both topics have 30 partions, numbers from 0 -29
5. we use _RangeAssignor_ strategy in order to consume exact range of partitions across topic by identical pods.

The problem is that when I looked at logs I see that concrete identical partition from both topics are consumed by different pods.

`pod#1: "received message: GenericMessage" AND "kafka_receivedPartitionId=20" AND "CS_Topic_1"`
`pod#2: "received message: GenericMessage" AND "kafka_receivedPartitionId=20" AND "CS_Topic_2"`

This is a big problem for us.

I also looked at logs during startup and I see that RangeAssignor is really used and also partition ranges in result assingment look ok but probably for incorrect consumer client id.
I dont understand generation of consumer client id on broker's side. We didn't define _client-id_ value but this shouldnt be a problem.
I've read that RangeAssignor put consumers in lexicographic order to calculate partition order. Maybe here is a problem.
Here is example of final assigment I see in the logs:
```
{
  consumer-CS_Group-4-5d6f9333-fc67-4bb1-9063-b599fd5d8cc8=Assignment(partitions=[
    CS_Topic_1-16,
    CS_Topic_1-17,
    CS_Topic_1-18,
    CS_Topic_1-19,
    CS_Topic_1-20,
    CS_Topic_1-21,
    CS_Topic_1-22
  ]),
  consumer-CS_Group-17-e2c701d4-5e10-44d4-b4e9-ceb29b6c383c=Assignment(partitions=[
    CS_Topic_2-8,
    CS_Topic_2-9,
    CS_Topic_2-10,
    CS_Topic_2-11,
    CS_Topic_2-12,
    CS_Topic_2-13,
    CS_Topic_2-14,
    CS_Topic_2-15
  ]),
  consumer-CS_Group-14-7fe74919-44b6-4f32-9168-60920afea8ee=Assignment(partitions=[
    CS_Topic_1-8,
    CS_Topic_1-9,
    CS_Topic_1-10,
    CS_Topic_1-11,
    CS_Topic_1-12,
    CS_Topic_1-13,
    CS_Topic_1-14,
    CS_Topic_1-15
  ]),
  consumer-CS_Group-14-5e0146b5-0d1a-435a-9e65-b5e8ac29cd1c=Assignment(partitions=[
    CS_Topic_2-0,
    CS_Topic_2-1,
    CS_Topic_2-2,
    CS_Topic_2-3,
    CS_Topic_2-4,
    CS_Topic_2-5,
    CS_Topic_2-6,
    CS_Topic_2-7
  ]),
  consumer-CS_Group-6-c1d939da-1f89-4f22-8f32-c90c95d71b06=Assignment(partitions=[
    CS_Topic_2-23,
    CS_Topic_2-24,
    CS_Topic_2-25,
    CS_Topic_2-26,
    CS_Topic_2-27,
    CS_Topic_2-28,
    CS_Topic_2-29
  ]),
  consumer-CS_Group-4-40065d2b-d202-4de1-8107-13063fcc4717=Assignment(partitions=[
    CS_Topic_2-16,
    CS_Topic_2-17,
    CS_Topic_2-18,
    CS_Topic_2-19,
    CS_Topic_2-20,
    CS_Topic_2-21,
    CS_Topic_2-22
  ]),
  consumer-CS_Group-8-87f3067f-7065-46b4-ae93-437b52bf779a=Assignment(partitions=[
    CS_Topic_1-23,
    CS_Topic_1-24,
    CS_Topic_1-25,
    CS_Topic_1-26,
    CS_Topic_1-27,
    CS_Topic_1-28,
    CS_Topic_1-29
  ]),
  consumer-CS_Group-12-45a74f00-0b06-409a-99e5-c1e93766958a=Assignment(partitions=[
    CS_Topic_1-0,
    CS_Topic_1-1,
    CS_Topic_1-2,
    CS_Topic_1-3,
    CS_Topic_1-4,
    CS_Topic_1-5,
    CS_Topic_1-6,
    CS_Topic_1-7
  ])
}
```

Can somebody tell me where can be problem? Im sure that we didn't have this problem in th past. 
We have a lot of logs like: **Attempt to heartbeat failed since group is rebalancing**, maybe this can be a reason?
Maybe kafka server was upgraded, Im not sure.

It doesn't work for following tested configurations
```
spring-cloud-starter-parent:Hoxton.SR12
spring-cloud-stream-binder-kafka: 3.0.13.RELEASE

spring-cloud-starter-parent:Greenwich.SR3
spring-cloud-stream-binder-kafka: 2.1.4.RELEASE
```

thanks
brpalo

**Comment by sobychacko** [comment]
@metalpalo I don't believe that this issue has anything to do with Spring Cloud Stream as it does not directly involve with the operations of `ConsumerPartitionAssignor`. You may want to reach out to the Kafka community through its mailing list or ask on StackOverflow. Closing the issue now; please feel free to re-open, if you believe this is Spring Cloud Stream related.
