### ISSUE TITLE
Producer callback in Spring Cloud Stream with reactor core publisher

### ISSUE THREAD

**Issue by aniket0788** [spring-cloud/spring-cloud-stream-binder-kafka#1155]
Could you look into this here please

https://stackoverflow.com/questions/69120425/producer-callback-in-spring-cloud-stream-with-reactor-core-publisher

**Comment by sobychacko** [comment]
@aniket0788 See the answer by @garyrussell on the SO thread ^^.

We also have this [note](https://github.com/spring-cloud/spring-cloud-stream-samples/blob/main/recipes/recipe-11-keep-track-of-successful-send-kafka.adoc) about `recordMetadataChannel` that might be useful.

Closing the issue. Feel free to re-open if need be.
