### ISSUE TITLE
InteractiveQueryService breaks Streams Application Isolation if mutliple Stream Apps using same Store Name

### ISSUE THREAD

**Issue by nico-javadev** [spring-cloud/spring-cloud-stream-binder-kafka#1161]
Hi there,
not sure if this is a really a Bug or if some other principle applies that should avoid this situation, but here's an interesting detail that we found out about the behavior of InteractiveQueryService, which produces an unwanted behavior in our use case:

When running multiple Stream Apps in the same JVM where the same State Store name is used in the different Streaming Apps, the InteractiveQueryService does not respect the StreamApp origin of the StateStore to query, but just returns the first Store with that name and type from any of the known KafkaStreams instances within the KafkaStreamsRegistry.

In our case this causes errors in processing, since we're using the same Store Names for our Query Services (as a common lib) but require each Stream App to get their specific instance of it's store, even if deployed in the same unit.

The [code responsible](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/f3a954fad71c3fc87c87bd98d0e66735ba9b766f/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/InteractiveQueryService.java#L100) is pretty straight forward, so I would like to know if this behavior is on purpose, or if this can be considered a bug?

To avoid this, in our case unwanted, behavior we patched the InteractiveQueryService to filter the KafkaStreams instances by matching the Thread's name (which contains the StreamApp's application id). But this is a not so clean workaround I would say, so not gonna share that in the first place here ;)

I'm happy to share more details about the Use Case and workaround if required, but first I would like to know your opinion on this topic and if maybe there's a totally different approach to this.

**Comment by sobychacko** [comment]
@nico-javadev Thanks for this report. It looks like you have an application with multiple Kaka Streams functions (i.e. separate topologies with their own `applicaiton.id`). Is that a true assumption? If that is true, the lack of a guard when querying the KafkaStreams instances from the registry is a bug I think. You are welcome to contribute a PR fixing this.

**Comment by nico-javadev** [comment]
Thanks, yes your assumption is correct. I will prepare a PR :)

**Comment by sobychacko** [comment]
@nico-javadev I see that you have some changes in a branch. If the work is done, could you submit it as a PR?

**Comment by nico-javadev** [comment]
PR is open. Not 100% happy with it since I would consider the Thread name matching rather a hack, but didn't come up with a smarter solution and works for our implementation for now :)
https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/1166
