### ISSUE TITLE
Question: how to send messages to multiple topics?

### ISSUE THREAD

**Issue by benkeil** [spring-cloud/spring-cloud-stream-binder-kafka#1167]
I want to send messages to multiple topics at once (no branching), how can I do this with spring cloud stream?

**Comment by sobychacko** [comment]
I assume you are using Kafka Streams binder since you mentioned branching. You can use `StreamBrdige` to programmatically send to multiple topics. `StreamBridge` allows you to configure your bindings with Kafka topics.

**Comment by sabbyanandan** [comment]
@benkeil: Please use StackOverflow for questions going forward.
