### ISSUE TITLE
Consuming from topics with higher consumer count than partition count not possible though auto rebalancing enabled

### ISSUE THREAD

**Issue by sflandergan** [spring-cloud/spring-cloud-stream-binder-kafka#118]
When consuming from a topic with auto rebalancing enabled, the KafkaMessageChannelBinder still validates the amount of partitions available, though the partition provider:
```
int partitionCount = extendedConsumerProperties.getInstanceCount() * extendedConsumerProperties.getConcurrency();

		Collection<PartitionInfo> allPartitions = provisioningProvider.getPartitionsForTopic(partitionCount,
				new Callable<Collection<PartitionInfo>>() {
					@Override
					public Collection<PartitionInfo> call() throws Exception {
						return consumerFactory.createConsumer().partitionsFor(destination.getName());
					}
				});
```

```
public Collection<PartitionInfo> getPartitionsForTopic(final int partitionCount, final Callable<Collection<PartitionInfo>> callable) {
		try {
			return this.metadataRetryOperations
					.execute(new RetryCallback<Collection<PartitionInfo>, Exception>() {

						@Override
						public Collection<PartitionInfo> doWithRetry(RetryContext context) throws Exception {
							Collection<PartitionInfo> partitions = callable.call();
							// do a sanity check on the partition set
							if (partitions.size() < partitionCount) {
								throw new IllegalStateException("The number of expected partitions was: "
										+ partitionCount + ", but " + partitions.size()
										+ (partitions.size() > 1 ? " have " : " has ") + "been found instead");
							}
							return partitions;
						}
					});
		}
		catch (Exception e) {
			this.logger.error("Cannot initialize Binder", e);
			throw new BinderException("Cannot initialize binder:", e);
		}
	}
```

This is not necessary, since the partition assigning is handled by Kafka, when auto rebalance is enabled. The partition info is ignored and only the topic name is used:
```
final ContainerProperties containerProperties =
				anonymous || autoRebalanceEnabled ? new ContainerProperties(destination.getName())
						: new ContainerProperties(topicPartitionInitialOffsets);
```

A very simple fix could be the following:
```
boolean autoRebalanceEnabled = extendedConsumerProperties.getExtension().isAutoRebalanceEnabled();
		
/*
 * if auto rebalance is enabled, we don't assign specific partitions, so it's okay, if we have less partitions
 * than consumers. Some will be idle until another consumer crashes. We set the partition count to 1 to disable
 * the sanity check
 */
int partitionCount = autoRebalanceEnabled? 1 : extendedConsumerProperties.getInstanceCount() * extendedConsumerProperties.getConcurrency();

Collection<PartitionInfo> allPartitions = provisioningProvider.getPartitionsForTopic(partitionCount,
		new Callable<Collection<PartitionInfo>>() {
			@Override
			public Collection<PartitionInfo> call() throws Exception {
				return consumerFactory.createConsumer().partitionsFor(destination.getName());
			}
		});
```

**Comment by sobychacko** [comment]
@sflandergan Thanks for the feedback. Contributions are welcome and feel free to send a PR fixing this!

**Comment by sflandergan** [comment]
I opened: #119 

Cheers
Simon

**Comment by mbogoevici** [comment]
Thanks @sflandergan - trying to understand the motivation for it - you'd like to start a number of consumers larger than the available partition count, and use rebalancing for failover?

**Comment by sflandergan** [comment]
@mbogoevici yes that's the idea. Though I'd prefer to use load balancing instead of high availability only, I'm consuming from a topic, that is forced to have 1 partition for ordering guarantees.

**Comment by odedia** [comment]
Was this fixed in any release? We are facing the same problem. There are valid scenarios where we don't want multiple partitions but we have many consumers. For example, when the same application exposes a REST API (so many instances are required for HA) but also listen to some rare event from Kafka (like a date change). For that I want only one instance to handle the event (for example, update the date in MySQL).
Thanks.

**Comment by sobychacko** [comment]
@odedia The PR is still in review and will be part of an upcoming release soon.

**Comment by odedia** [comment]
Thank you. For the meantime, I would presume the only workaround is to use the same number of partitions as the number of consumers?
If I use the autoAddPartitions property, it will never decrease the number of partitions, only increase, correct?
We did face an issue when testing failure handling where if we have 2 partitions and 2 consumers, if we kill one of the consumers there will not be a rebalance so some messages are not processed until the second consumer is restarted.

**Comment by sobychacko** [comment]
@odedia Yes, that will be the workaround for the time being, i.e sending the same number of partitions as the number of consumers. More partitions than the number of consumers also work. Lets say you have 2 partitions and 1 consumer. The current strategy in the binder will work in that case. That brings to your next question about having less consumers than partitions. In that case, the binder will not decrease the number of partitions provisioned for the topic. It will only try to add partitions if the right conditions are met.

**Comment by sobychacko** [comment]
This issue is resolved via https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/119
