### ISSUE TITLE
Topic and header will be omitted when using event type based routing

### ISSUE THREAD

**Issue by andrashatvani** [spring-cloud/spring-cloud-stream-binder-kafka#1186]
The topic and the headers will be omitted when using event_type-based routing. 
On lines https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/63b306d34c2c0a84267e0842f15d0d10b8ed17d2/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/AbstractKafkaStreamsBinderProcessor.java#L457 and 
https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/63b306d34c2c0a84267e0842f15d0d10b8ed17d2/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/AbstractKafkaStreamsBinderProcessor.java#L559

Thus, it's currently not possible to use event type routing and method-based json target type determination based on topic or header data. 

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/1003#issuecomment-1004615339

**Comment by sobychacko** [comment]
@andrashatvani This is now fixed in main (3.2.x) and backported to 3.1.x.
