### ISSUE TITLE
@EmbeddedKafka not working properly with GlobalKTable and transformer

### ISSUE THREAD

**Issue by ecristobal** [spring-cloud/spring-cloud-stream-binder-kafka#1196]
Hi guys!

In this [repo](https://github.com/ecristobal/example.git) I've attached a project that is not currently working. To sum up what it is intended to do, we have 2 input topics: one with incoming purchases (KStream) and one with an item catalog (GlobalKTable, materialized as a state store). The idea is, each time we receive a purchase, we enrich its content with a property stored on the KTable, and with some other operations an enriched purchase object will be returned. There are also a couple of caches implemented with Spring and Redis to cache calls to a couple of external methods (I've added the code to give you full context, but I don't think they affect tp the result of the sample).

However, I didn't find a way to make this example work. I've tried to switch from GlobalKTable to KTable, follow your documentation about state stores, transformations and so on, but it wasn't possible to me to make this work. The project also contains a sample test to reproduce the problem [here](https://github.com/ecristobal/example/blob/6d34bacb8f56f66d94e04b0186b97dc66281b6f7/src/test/java/com/example/enrich/spring/StreamFunctionIT.java).

Please, can you help us in figuring out what is happening?

Thanks and regards!

**Comment by sobychacko** [comment]
Issue moved to [spring-cloud/spring-cloud-stream #2319](https://github.com/spring-cloud/spring-cloud-stream/issues/2319) via [**ZenHub**](https://www.zenhub.com/)
