### ISSUE TITLE
Live producer threads and dynamic-destination-cache-size property

### ISSUE THREAD

**Issue by ferblaca** [spring-cloud/spring-cloud-stream-binder-kafka#1198]
We have detected a problem in the increase of resources when there are configured in an application more bindings out (producers) which value has the property `spring.cloud.stream.dynamic-destination-cache-size` (default 10).

The problem is that the created threads grow without control and are not released, and in some cases consuming memory and even occupying all the descriptors of the system causing the application to fail.

Is this an expected behavior? the only solution is to increase the value of the `spring.cloud.stream.dynamic-destination-cache-size` property?

Attached is an application that reproduces the case we explained and we add a screenshot with the threads created are only 2 binding and `spring.cloud.stream.dynamic-destination-cache-size=1`:
<img width="561" alt="visualvm-threads" src="https://user-images.githubusercontent.com/9643385/153007391-ded415a2-02ee-4f77-aa75-1cea8658cdb1.png">
[demoDynamicDestinationCache.zip](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/files/8024630/demoDynamicDestinationCache.zip)

**Comment by sobychacko** [comment]
@ferblaca Good to hear that the issue has been resolved once you upgraded. We will see if we can update the release notes. In the meantime, can we close this issue? Is there anything more to be done on this?
