### ISSUE TITLE
Default spring boot console logging pattern corruption

### ISSUE THREAD

**Issue by e-zhydzetski** [spring-cloud/spring-cloud-stream-binder-kafka#128]
SpringBoot: 1.5.3.RELEASE
SpringCloudStreamBinderKafka: 1.2.0.RELEASE

`KafkaBinderEnvironmentPostProcessor` breaks the default spring boot console logging pattern: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderEnvironmentPostProcessor.java#L58

**Comment by mbogoevici** [comment]
Duplicate of #133
