### ISSUE TITLE
Kafka producer should support SpEL expressions to indicate target topic

### ISSUE THREAD

**Issue by hekonsek** [spring-cloud/spring-cloud-stream-binder-kafka#130]
Hi Marius (@mbogoevici),

This is continuation of the [1] discussion. 

Just to summarize my goal here. I'd like to be able to send message to HTTP endpoint [2] for example and specify target Kafka topic dynamically using HTTP header for example.

I think it might be indeed possible to handle bridging between HTTP app starter [2] and Kafka producer without dedicated Kafka sink component. Correct me if I'm wrong, but if we manage to change this [3] line to support SpEL expression (not only hardcoded `LiteralExpression` like now), then we should be able to specify target topic via expression.

Let's say that we introduce new property to indicate that certain binding should use SpEL expression (like `spring.cloud.stream.bindings.output.destinationExpression=spel`) instead of Literal (default). Then we should be able to specify destination dynamically:

    spring.cloud.stream.bindings.output.destinationExpression=spel
    spring.cloud.stream.bindings.output.destination=headers.target_topic 

And in such case HTTP request coming to HTTP app starter should be routed to the topic indicated by `target_topic` HTTP header.

This is just hypothesis which might be wrong considering my limited Spring Cloud Stream expertise. :) What do you think about such approach, Marius?

[1] https://github.com/spring-cloud/spring-cloud-stream/issues/946
[2] https://github.com/spring-cloud-stream-app-starters/http
[3] https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/66eb15a8e2d90b1f593f19ddc07869b8d8b1d74c/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java#L373

**Comment by mbogoevici** [comment]
Hi Henrik, 

I believe things got a little crosswired here. Regarding the dynamic destination support, I still think that an can leverage the dynamic destination support which is the basis of the router sink: http://docs.spring.io/autorepo/docs/spring-cloud-stream-docs/Chelsea.SR1/reference/htmlsingle/#dynamicdestination  - which is what @markfisher was hinting here: https://github.com/spring-cloud/spring-cloud-stream/issues/946#issuecomment-299577574. 

The original issue proposed two things:
a) that we support routing (which is where the paragraph above applies IMO)
b) that we support a SpEL expression for populating keys in the Kafka binder, which I think we should definitely do.

For a), it looks like a customized version of the http starter could help using the dynamic destination support. Making the destination a SpEL expression is possible, but requires some serious changes in the core. Populating the key could be easily done as an additional feature of the binder tho.

Let me know what you think.

**Comment by hekonsek** [comment]
Hi Marius,

Indeed `BinderAwareChannelResolver` seems to do the job when it comes to dynamic destinations. Kudos! :) 

The other question if it is possible to take advantage of dynamic destinations in HTTP starter app, so we can use dynamic HTTP routing in Spring Cloud Data Flow without writing customized version HTTP starter for this purpose. But maybe let's try to focus on this later :) .

First things first - dynamic key expression support. :) So you have something like #131 in mind?

**Comment by mbogoevici** [comment]
Hi Henryk,

Yes - I will close this issue in favour of creating a new issue - #134, since the current one mostly deals with dynamic topics.

**Comment by hekonsek** [comment]
Agreed! Many thanks, Marius.
