### ISSUE TITLE
Configuration of instanceIndex and instanceCount per topic

### ISSUE THREAD

**Issue by sauliust** [spring-cloud/spring-cloud-stream-binder-kafka#14]
Currently it is possible to setup partitioned kafka consumers using **spring.cloud.stream.instanceIndex** and **spring.cloud.stream.instanceCount**. However the same application might have several consumer groups. I tried to specify these options per topic, but no luck. Could we add an option to configure it per topic likes this:
**spring.cloud.stream.bindings.input.consumer.instanceCount=2**

**Comment by sabbyanandan** [comment]
This is supported via: https://github.com/spring-cloud/spring-cloud-stream/commit/d11b3cf08db4a10b8740401b20203f6355bb6b56.
