### ISSUE TITLE
Problem with Serializers and Deserializers during channel binding

### ISSUE THREAD

**Issue by TabberGit** [spring-cloud/spring-cloud-stream-binder-kafka#142]
We're using SpringBoot/SpringCloudStream to stream information into Kafka.  There is an autoconfiguration in SpringBoot `org.springframework.boot.autoconfigure.kafka.KafkaProperties` that is setting both serializers and deserializers in the Producer and Consumer objects therein.

This is later referenced in `org.springframework.cloud.stream.binder.kafka.config. KafkaBinderConfiguration` in the PostConstruct because of the `@ConditionalOnClass(name = "org.springframework.boot.autoconfigure.kafka.KafkaProperties")`

As the `init()` method progresses, it constructs a `Map<String,Object> configuration` where all of the kafka configuration properties are dumped into one Map...  This is where the problem starts.

Later, when channels are bound, both the Producer and Consumer are fed serializers AND deserializers.  The `org.apache.kafka.clients.consumer.KafkaConsumer` and `org.apache.kafka.clients.producer.KafkaProducer` classes log the unnecessary configuration information at the WARN level (in the case of the Consumer, repeatedly on a scheduler)

I believe that an adjustment to the `init()` method in `KafkaPropertiesConfiguration` to filter out these fields (as you're only looking for binder information...), this will eliminate this misconfiguration.

Currently, I am able to circumvent the issue by setting:

- spring.kafka.consumer.key-deserializer=null
- spring.kafka.consumer.value-deserializer=null
- spring.kafka.producer.key-serializer=null
- sprint.kafka.producer.value-serializer=null

These are then not carried erroneously into the binder configuration.

If there were a filter put into the code
```
for (Map.Entry<String, Object> producerProperties : this.kafkaProperties.buildProducerProperties().entrySet()) {
	if (!configuration.containsKey(producerProperties.getKey())) {
		configuration.put(producerProperties.getKey(), producerProperties.getValue());
	}
}
for (Map.Entry<String, Object> consumerProperties : this.kafkaProperties.buildConsumerProperties().entrySet()) {
	if (!configuration.containsKey(consumerProperties.getKey())) {
		configuration.put(consumerProperties.getKey(), consumerProperties.getValue());
	}
}
```
such that it left out the properties if the key was in:

- ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG
- ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG
- ConsumerConfig.KEY_SERIALIZER_CLASS_CONFIG
- ConsumerConfig.VALUE_SERIALIZER_CLASS_CONFIG

**Comment by mbogoevici** [comment]
We can filter out properties before creating a consumer/producer.

**Comment by tschuettel** [comment]
Thank you for fixing. This problem currently keeps us from upgrading to the Dalston release train. Is it possible to backport this to 1.2.x?

**Comment by sourabhXIII** [comment]
I am facing the same issue with:
```
<dependency>
		<groupId>org.springframework.kafka</groupId>
		<artifactId>spring-kafka</artifactId>
		<version>2.2.8.RELEASE</version>
	</dependency>
	<dependency>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-stream</artifactId>
		<version>2.2.1.RELEASE</version>
	</dependency>
```
