### ISSUE TITLE
Honour `startOffsets` setting and don't hardcode `auto.offset.reset`

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream-binder-kafka#145]
It seems like we always start anonymous groups at the latest offset, even if there's a use case for starting at earliest. Keep the current behaviour as default and try honour the `startOffset` setting if explicitly configured.

**Comment by Delmonte3161** [comment]
I think this extends beyond just anonymous consumers as well.  startOffset value is ignored completely and is forcibly set based on using an anonymous consumer or not.  Additionally, setting the "auto.offset.reset" kafka property directly (via the kafka binder configuration map) is currently overwritten by the same anonymous check.

**Comment by mbogoevici** [comment]
@Delmonte3161 Thanks for point that out. Will change the title.

**Comment by Delmonte3161** [comment]
I submitted a pull request for this.
https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/146
