### ISSUE TITLE
Make it possible to use a different ProducerFactory/ConsumerFactory from the KafkaMessageChannelBinder 

### ISSUE THREAD

**Issue by sebay** [spring-cloud/spring-cloud-stream-binder-kafka#148]
Hi,
I am trying to use a different implementation of the Kafka Consumer/Producer (https://github.com/linkedin/li-apache-kafka-clients/blob/master/src/main/java/com/linkedin/kafka/clients/producer/LiKafkaProducer.java / LiKafkaConsumer.java).
For this I need KafkaMessageChannelBinder to be able to create those producer/consumer. Unfortunately KafkaMessageChannelBinder is hardcoded to return the Default factories:

	private DefaultKafkaProducerFactory<byte[], byte[]> getProducerFactory(
			ExtendedProducerProperties<KafkaProducerProperties> producerProperties) {
		Map<String, Object> props = new HashMap<>();
		props.put(ProducerConfig.RETRIES_CONFIG, 0);
		props.put(ProducerConfig.BUFFER_MEMORY_CONFIG, 33554432);
		props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, ByteArraySerializer.class);
		props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, ByteArraySerializer.class);
		props.put(ProducerConfig.ACKS_CONFIG, String.valueOf(this.configurationProperties.getRequiredAcks()));
		if (!ObjectUtils.isEmpty(configurationProperties.getConfiguration())) {
			props.putAll(configurationProperties.getConfiguration());
		}
		if (ObjectUtils.isEmpty(props.get(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG))) {
			props.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, this.configurationProperties.getKafkaConnectionString());
		}
		if (ObjectUtils.isEmpty(props.get(ProducerConfig.BATCH_SIZE_CONFIG))) {
			props.put(ProducerConfig.BATCH_SIZE_CONFIG, String.valueOf(producerProperties.getExtension().getBufferSize()));
		}
		if (ObjectUtils.isEmpty(props.get(ProducerConfig.LINGER_MS_CONFIG))) {
			props.put(ProducerConfig.LINGER_MS_CONFIG, String.valueOf(producerProperties.getExtension().getBatchTimeout()));
		}
		if (ObjectUtils.isEmpty(props.get(ProducerConfig.COMPRESSION_TYPE_CONFIG))) {
			props.put(ProducerConfig.COMPRESSION_TYPE_CONFIG,
					producerProperties.getExtension().getCompressionType().toString());
		}
		if (!ObjectUtils.isEmpty(producerProperties.getExtension().getConfiguration())) {
			props.putAll(producerProperties.getExtension().getConfiguration());
		}
		return new DefaultKafkaProducerFactory<>(props);
	}

**Comment by mbogoevici** [comment]
Hi @sebay - thanks for the suggestion. We'll look into making this more flexible, so that perhaps you  can provide your own `ProducerFactory`/`ConsumerFactory` bean.

If you feel so inclined, we welcome contributions as well :)!

**Comment by jzc928** [comment]
The same statement, is there a plan?

**Comment by artembilan** [comment]
In Kinesis Binder we have figured out that we can use a `@Configuration` class with a custom client to feed to the particular binder in the multi-binder environment: https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/issues/74#issuecomment-444931466

**Comment by sobychacko** [comment]
This issue is no longer a requirement and out of scope. Closing the issue due to inactivity.
