### ISSUE TITLE
Group ID from Spring Boot configuration is overridden with anonymous

### ISSUE THREAD

**Issue by rotilho** [spring-cloud/spring-cloud-stream-binder-kafka#149]
The group.id is been overridden in the latest version (1.2.1) with anonymous group.

This issue was introduced in 5c70e2df43e3bb59bda52ef6e66b6ecfbbd2a468 and mainly is caused because KafkaMessageChannelbinder.createConsumerEndpoint create a anonymous group id by default if `spring.cloud.stream.bindings.<channelName>.group` is null.

How to reproduce

- Create a project with Spring Boot configuration
- Start the application

Workaround

- Define `spring.cloud.stream.bindings.<channelName>.group=groupName`

**Comment by ilayaperumalg** [comment]
@rotilho do you want to override the `group.id` with explicit `configuration` properties?

**Comment by rotilho** [comment]
Actually no. I want to use Spring Boot configuration as much as possible however in the latest version the group.id is been replaced with anonymous by KafkaMessageChannelBinder.createKafkaConsumerFactory
