### ISSUE TITLE
Current runtime scaling status

### ISSUE THREAD

**Issue by hekonsek** [spring-cloud/spring-cloud-stream-binder-kafka#151]
Hi @mbogoevici,

According to the Spring Cloud Data Flow documentation [1] after introducing Kafka client >= 0.9 it should be possible to scale up/down applications at runtime. After brief look into current master branch of Kafka Binder I have an impression that you still calculate partition numbers to consume and assign those manually to the consumer. At least I don't see any obvious partition rebalancing logic there. Am I right by any chance?

I'm asking because with runtime scaling in place #143 will be much much more useful. Without runtime scaling I can detect that there is a significant lag that has to addressed and tell Kubernetes to stop current consumers, reconfigure instance count to be higher and start my consumers again. However that approach would generate an ugly pause in message consumption until new consumers are provisioned and started up. This still solves the autoscaling problem, but an ability to scale up/down at more fine-grained level would be just much more efficient - for example you could spawn a couple of extra instances just to deal with traffic peak and dispose them after that. I'm aware that Kafka competing consumer auto-rebalancing also causes some pause during the actual rebalancing process, but it is significantly shorter than turning down and starting up a bunch of JVMs. 

[1] http://docs.spring.io/spring-cloud-dataflow/docs/1.2.1.RELEASE/reference/htmlsingle/#arch-runtime-scaling

**Comment by mbogoevici** [comment]
@hekonsek The code might be somewhat complex (we can do a better job simplifying it I guess), but this is the relevant bit is:

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java#L245

If `autoRebalanceEnabled` is set to `true` (the default), then consumers rely on the automatic partition assignment done by the Kafka consumer (including rebalancing). We do support a use case where partitions are assigned statically to a fixed set of consumers under the control of the consumer (`autoRebalanceEnabled` is `false`). This is mainly to address semantic partitioning scenarios where the number of processing nodes is generally known in advance and node rebalancing in the event of a node restart is undesirable.

**Comment by hekonsek** [comment]
OK, I have found an appropriate piece code. Awesome! I'm glad to see this being implemented. Many thanks for the pointer, Marius.
