### ISSUE TITLE
React to consumer rebalance

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-stream-binder-kafka#166]
_From @janoskranczler on June 28, 2017 12:14_

Hi guys,
Is there any way I can react on a consumer rebalance (Kafka), if `autoRebalanceEnabled` is set to `false`? In Kafka client there is `ConsumerRebalanceListener`, but how can I listen on rebalance in SCS?
(And if I can, what is the simplest way to determine the partition count before and after the rebalance?)

_Copied from original issue: spring-cloud/spring-cloud-stream#1004_

**Comment by ilayaperumalg** [comment]
Hi @janoskranczler ,

For tracking this better, please create Kafka binder related issues here: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka

I will move this now.

**Comment by ilayaperumalg** [comment]
@janoskranczler, 

Configuring `ConsumerRebalanceListener` feature has been added in `spring-kafka` 2.0.0.M1: https://github.com/spring-projects/spring-kafka/commit/e857c248eb88116bfd28ccf05671e5be13741f96 .  
I think the Kafka binder can make use of this feature by setting the user provided `ConsumerRebalanceListener` to `KafkaMessageListenerContainer` once we update to `spring-kafka` 2.x.

**Comment by janoskranczler** [comment]
Thanks, for your answer. Yes, it is a Kafka related question, sorry.

**Comment by ilayaperumalg** [comment]
@janoskranczler No problem at all; thank you for the suggestion! If you would like to contribute this feature as a PR (once spring-kafka 2.x is updated), that would be great!

**Comment by neilg** [comment]
Is there still interest in a PR for this? I'd like to do it but might need some pointers.

**Comment by sobychacko** [comment]
@neilg Sure, if the user provided `ConsumerRebalanceListener` needs to be used, binder changes are required. Feel free to send a PR and we can review it. This is the main class for the Kafka biner implementation: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java

**Comment by neilg** [comment]
Apologies if this is answered elsewhere, or if there's a more appropriate place to ask. Are there some IDE settings I can import for code style, etc? I'm using IntelliJ.

**Comment by sobychacko** [comment]
[This commit](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/2144d3e26f4b980196633219a3cacd5e2a815a87) introduced the ability for apps to provide custom rebalance listener. Closing the issue.
