### ISSUE TITLE
Partitioning should use the existing partition count

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream-binder-kafka#169]
Instead, it seems to use the `partitionCount` property of the topic.

Originally it was: https://github.com/spring-cloud/spring-cloud-stream/issues/977

**Comment by garyrussell** [comment]
This was broken long ago, perhaps when partitioning was moved from the binder to a channel interceptor in https://github.com/spring-cloud/spring-cloud-stream/commit/bd92af47840e861afccb3a1a263216311e400743#diff-290b09119bc6747e86a6d2720a0c52a7

So, it happens far-removed from the binder where knowledge of the physical partition count resides.

We might need to add a header to the message to tell the interceptor how many partitions exist.

cc/ @viniciusccarvalho @elnur
