### ISSUE TITLE
auto.offset.reset policy cannot be changed

### ISSUE THREAD

**Issue by vaisegid** [spring-cloud/spring-cloud-stream-binder-kafka#177]
I have consumer group non anonymous and wish to put policy "auto.offset.reset" to the "latest". I always get it overwritten by the KafkaMessageChannelBinder with 'earliest'. I put my value to the spring.kafka.consumer.auto-offset-reset or to the spring.cloud.stream.kafka.binder.configuration but non of these worked. I am using org.springframework.cloud:spring-cloud-netflix:1.2.4.RELEASE

This policy is quite important when you try to achieve that message won't be consumed twice on offset corruption.

**Comment by ilayaperumalg** [comment]
Hi, 

Looks like you are running into the issue which was fixed via https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/7355ada4613ad50fe95430f1859d4ea65f004be1

These changes are pushed into 1.3.0.M1/M2 and 2.0.0.M1 of Spring Cloud Stream versions. Do you think you can try one of them?

**Comment by vaisegid** [comment]
We are using kafka 0.9 cluster but 1.3.0M1 is using kafka 0.10 client which is not compatible with 0.9. At resent time I cannot confirm if this is working for us. But from the first glance looks like commit is fixing the right place.

**Comment by ilayaperumalg** [comment]
@vaisegid ok, thanks! Please re-open this if you see the issue after you get to use any of the versions that have the fix for this. Closing this for now.
