### ISSUE TITLE
Refactor and adapt to core's error-handling strategy

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-kafka#178]
As a developer, I'd like to refactor kafka-binder's error handling implementation to adapt to core's new abstraction. 

This is a continuation of spring-cloud/spring-cloud-stream#1036, but the changes required in kafka-binder.

**Comment by sobychacko** [comment]
This issue is no longer a requirement and out of scope. Closing the issue.
