### ISSUE TITLE
Revisit the use and naming for "autoCommitOffset" and "autoCommitOnError" properties

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-kafka#185]
As a user, while using `autoCommitOffset` and `autoCommitOnError` properties, I'm confused what to do with them. The [docs](http://docs.spring.io/autorepo/docs/spring-cloud-stream-binder-kafka-docs/1.1.1.BUILD-SNAPSHOT/reference/htmlsingle/#_kafka_consumer_properties) aren't very clear either. 

Whether or not the DLQ is configured, the offset commit _will_ happen on the next successful message anyway, so why it is necessary to expose the properties to control this? The benefits of interacting with those properties are unclear. Let's revisit the purpose in the context of possible use-cases.

**Comment by sobychacko** [comment]
@sabbyanandan As discussed internally, closing this issue. Created a new [issue](https://github.com/spring-cloud/spring-cloud-stream-samples/issues/166) in the samples repository to create an app that tackles these properties from a use-case angle as you suggested.
