### ISSUE TITLE
Test against Spring Kafka 1.1.0.M1

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-kafka#19]
As a developer, I'd like to test Kafka binder against 1.1.0.M1 release of Spring Kafka, so I can evaluate binder functionality against 0.10 release of Kafka.

**Comment by sobychacko** [comment]
This is resolved through https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/35
