### ISSUE TITLE
Broker Leader Change is not Handled

### ISSUE THREAD

**Issue by TimShi** [spring-cloud/spring-cloud-stream-binder-kafka#197]
When broker leader changes, we expect spring-cloud-stream-binder-kafka to be able to figure out the new broker leader.

However, we are getting the following exception:

```
2017-09-14 10:16:17.896 ERROR 1 --- [d | producer-10] o.s.k.support.LoggingProducerListener    : Exception thrown when sending a message with key='null' and payload='...' to topic MY_TOPIC:
org.apache.kafka.common.errors.NotLeaderForPartitionException: This server is not the leader for that topic-partition.
```
Note: I'm not sure if this should be handled at the lower level Spring-Kafka repo. But we encountered this when using Spring Cloud Stream.

**Comment by artembilan** [comment]
Related to https://github.com/spring-projects/spring-kafka/issues/429.
