### ISSUE TITLE
Document transaction configuration

### ISSUE THREAD

**Issue by codependent** [spring-cloud/spring-cloud-stream-binder-kafka#226]
Starting with Kafka 0.11 transaction support is already available and has been included in Spring Cloud Stream 1.3 as @artembilan kindly [told me](https://github.com/spring-cloud/spring-cloud-stream/issues/536#issuecomment-335837105). 

The scenario I want to control with a transaction is a database write along with a message publication, which should happen atomically, something like this:

```
/**
 * writes in DB and sends a message atomically
 */
@Transactional
@SendTo(Source.OUTPUT)
public void createUser(User user){
   userRepository.save(user);
   return new UserCreatedEvent(user.getId())
}
```

I've had a look at Spring Kafka 2.0.0 documentation where it is specified [how to do something analogous to what I want](https://docs.spring.io/spring-kafka/docs/2.0.0.RELEASE/reference/html/_reference.html#_transaction_synchronization).

However, going back to Spring Cloud Stream, it is not clear (it's [undocumented](https://docs.spring.io/spring-cloud-stream/docs/Elmhurst.BUILD-SNAPSHOT/reference/htmlsingle/)) how to configure the applications to support transactionality and synchronization with a `DataSourceTransactionManager`.

I'd really appreciate if you could make this clearer.

**Comment by garyrussell** [comment]
Injecting some external transaction manager (such as a `DataSourceTransactionManager`) into the Kafka listener container is not currently supported.

You can achieve similar effects by enabling transactions in the binder and using `@Transactional` on the listener for the datasource transaction manager; the Kafka transaction will commit shortly after the DB.

Note that the producer properties have to be set on the transactional producer...

```
 +		/*
 +		 * IMPORTANT: With a transactional binder, individual producer properties for
 +		 * Kafka are ignored; the global binder
 +		 * (spring.cloud.stream.kafka.binder.transaction.producer.*) properties are used
 +		 * instead, for all producers. A binder is transactional when
 +		 * 'spring.cloud.stream.kafka.binder.transaction.transaction-id-prefix' has text.
 +		 */
```

I am not sure what happened to the doc updates; I distinctly remember writing them.
