### ISSUE TITLE
Kafka binder metrics not showing up in /metrics in spring boot actuator

### ISSUE THREAD

**Issue by marcusn** [spring-cloud/spring-cloud-stream-binder-kafka#250]
I have an application using spring boot starter 1.5.8 and spring cloud stream 1.3.0. However, the metrics for the binders does not show up in /metrics. After debugging it seems that the binder is running in a separate application context, meaning that the metrics endpoint does not find it. Is there a way to get that to work? Or some other way of accessing the metrics? Can I access the binder application context?

**Comment by marcusn** [comment]
Any ideas? Maybe more general, do you have an example how to access these metrics in any way?

**Comment by vsaini-rythmos** [comment]
I have the same question, will like to know how i can see the lag metric

**Comment by urgelacko** [comment]
Same problem here. More problems found

1. Binder config is in separate context so the applications `MeterBinder` mechanism isn't using it.
2. If you import the `KafkaBinderConfiguration` explicitly with `@Import` the `MeterBinder` is hooked up however when `bindTo` is called during application startup the `this.binder.getTopicsInUse()` returns 0 because the Kafka connections wasn't built up yet.

**Comment by olegz** [comment]
@urgelacko with MeterBinder reference it appears you are pointing to Micrometer support for each was just introduced for 2.0 and did not exist in 1.3 version of Spring Cloud Stream. 
If so, please raise a new issue (if you believe you're having an issue) for 2.0 and do not conflate it with the original problem reported here

**Comment by urgelacko** [comment]
Sorry, you are right, I missed the version numbers.
https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/318

**Comment by artembilan** [comment]
@marcusn,

See the related issue #318 .

I would say that my workaround there works well for your as well.

Only a difference that you have to gather `PublicMetrics` beans and register them into the `MetricsEndpoint` via its `registerPublicMetrics(PublicMetrics metrics)`.

I hope we will have some out-of-the-box fix for the problem in the `2.0` version.

**Comment by artembilan** [comment]
Sorry, linked to the wrong issue from the PR.

However this one can be as an indicator for the fix in SCSt Core.

See my  comments in the related issue #318, plus the commit message in the PR #320

**Comment by marcusn** [comment]
Thanks @artembilan that worked! Here is the adapted code:


```
@Configuration
public class KafkaBinderMetricsWorkaround implements ApplicationListener<ApplicationReadyEvent> {

    @Autowired
    private MetricsEndpoint metricsEndpoint;

    private final List<PublicMetrics> springCloudStreamMeterBinders = new ArrayList<>();

    @Bean
    public DefaultBinderFactory.Listener listenerForMeterBinders() {

        return (configurationName, binderContext) -> {
            springCloudStreamMeterBinders.add(binderContext.getBean(PublicMetrics.class));
        };

    }

    @Override
    public void onApplicationEvent(ApplicationReadyEvent event) {
        this.springCloudStreamMeterBinders.forEach(metricsEndpoint::registerPublicMetrics);
    }
}

```

**Comment by olegz** [comment]
@marcusn while it is great to see that it worked, it is no longer needed if you upgrade to Spring Cloud Stream 2.0.0.RC2 which was released few hours ago. Also, Spring Boot 2.0.0.RELEASE
