### ISSUE TITLE
ReplicationFactor not properly set when deleting topic at runtime

### ISSUE THREAD

**Issue by rzeijde** [spring-cloud/spring-cloud-stream-binder-kafka#256]
setting the `spring.cloud.stream.kafka.binder.replicationFactor` at spring boot startup results in the correct replicationFactor. Deleting the topic at runtime e.g.

`/opt/kafka/bin/kafka-topics.sh --zookeeper zookeeper --delete --topic sometopic`

will always result in a topic being recreated with replicationFactor 1.

**Comment by sabbyanandan** [comment]
Hi, @rzeijde: Could you describe your use-case, please?

**Comment by sobychacko** [comment]
Closing the issue due to inactivity.
