### ISSUE TITLE
kstream11 with Kafka 0.11.0.1 not working but kstream with Kafka 0.10.1.1 works.

### ISSUE THREAD

**Issue by xmlking** [spring-cloud/spring-cloud-stream-binder-kafka#267]
code works with `org.springframework.cloud:spring-cloud-stream-binder-kstream` and Kafka `0.10.1.1`

but not with `org.springframework.cloud:spring-cloud-stream-binder-kstream11:1.3.0.RELEASE` and Kafka `0.11.0.1`

when using with Kafka `0.11.0.1`,  no messages reach to kstream processor. 

### How to reproduce:
https://github.com/xmlking/kafka-kstream

**Comment by xmlking** [comment]
I setup new repo 
https://github.com/xmlking/kstream-experiments
This is somehow working as expected with `0.11.0.0`.  (tested with Kafka `0.10.1.1`  and  `0.11.0.0` and both works)

Kafka Version  `0.10.1.1` &  `0.11.0.0`

```bash

springBootVersion=1.5.9.RELEASE
springCloudVersion=Edgware.RELEASE
springCloudStreamVersion=Ditmars.RELEASE

compile("org.springframework.cloud:spring-cloud-stream-binder-kstream11:1.3.0.RELEASE")
```

**Comment by olegz** [comment]
@xmlking As I mentioned on gitter, the stack trace you've provided doesn't point to anything related to spring-cloud-stream. 
You are using two different versions of Kafka and your stack trace points to some issue with native Kafka serde (something that is not managed by spring-cloud-stream). Have you investigated it by trying to send/receive message to Kafka 11 outside of spring-cloud-stream?

**Comment by xmlking** [comment]
@olegz yes I tested with producer, consumer CLI tools using following commends to same topic, and it is woking. 
```
kafka-console-producer --broker-list kafka:9092 --topic words
kafka-console-consumer --bootstrap-server kafka:9092 --topic words
```
anyway I was able to  run my [demo](https://github.com/xmlking/kstream-experiments) setup with `0.11.0.0`  . so this can be closed.

**Comment by xmlking** [comment]
looks like we are hardcoding application.id , is there a way to overwrite StreamsConfig in my code?


```
props.put(StreamsConfig.APPLICATION_ID_CONFIG, "default");
```

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kstream/src/main/java/org/springframework/cloud/stream/binder/kstream/config/KStreamBinderSupportAutoConfiguration.java#L74

**Comment by sobychacko** [comment]
@xmlking at the moment, there is not a way to do that, but will make it more configurable in 2.0.

**Comment by sobychacko** [comment]
@xmlking Actually, you can override that by providing the following property.
`spring.cloud.stream.kstream.binder.configuration.application.id`. Sorry for the confusion.
