### ISSUE TITLE
Add data processing support for branched KStream predicates

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-kafka#278]
As a continuation of spring-cloud/spring-cloud-stream-binder-kafka#274, as a developer, I'd like to add support for data processing on branched KStream predicates. 

**Note:**
A typical use-case would be to do the transformation on branched predicates prior to it being published to a branched-topic (see [discussion](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/265#issuecomment-355715675)).

**Acceptance:**
Do the [wordcount](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/265#issuecomment-355698317) (on language list - in lowercase), branch it based on "language", and convert one of the branched predicates to "uppercase". Assert that the before and after (lowercase -> uppercase) is applied.

**Comment by sobychacko** [comment]
This issue is addressed as part of this commit: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/3a5aed61c9744bec4776745db1720e0f3f34df44
