### ISSUE TITLE
spring-cloud-stream with new kafka-clients missing features

### ISSUE THREAD

**Issue by YossiShasha** [spring-cloud/spring-cloud-stream-binder-kafka#285]
Our application uses spring-cloud-stream for Kafka messaging.
spring-cloud-stream version is Ditmars.RELEASE, and spring-cloud-stream-binder-kafka version is 1.3.0.RELEASE.
Our Kafka broker version is 1.0.0, we want to upgrade our kafka-clients to 1.0.0 as well, but it looks like that autoCreateTopics and autoAddPartitions capabilities are no longer supported? There is a reason for that? Are they going to be supported in the future?

**Comment by sobychacko** [comment]
@YossiShasha kafka 1.0.0 is not compatible with Ditmars. You need to use 0.10 version. You can also use the 0.11 binder that is available as part of Ditmars which allows you to use Kafka 0.11. If you want to use 1.0.0 version of Kafka you need to use `spring-cloud-stream` 2.0.0 (Elmhurst). Latest release is M3. You can check out the latest snapshot as well. 
Please use Stackoverflow or Gitter for questions like this. Use GH issues for bug reports or feature requests.
Thank you!
