### ISSUE TITLE
Resolve the Kafka Broker and zookeeper node from service discovery

### ISSUE THREAD

**Issue by Addymaddy** [spring-cloud/spring-cloud-stream-binder-kafka#286]
Currently the kafka brokers and zoo keeper nodes are fetched from these properties
spring.cloud.stream.kafka.binder.zkNodes=
spring.cloud.stream.kafka.binder.brokers=

Can we have the feature where we instead of specifying the absolute broker and zknode values here , we just give the serviceName and get it discovered from the service discovery server like (Eureka or consul)

**Comment by elsega** [comment]
Hi, I have the same question. Does the stream binder kafka support consul discovery out of the box or do we have to use the DiscoveryClient from spring cloud consul ?
If so, which is the best approach to override the kafka binder configs ? enabling `spring.main.allow-bean-definition-overriding=true` and then manually redefine `org.springframework.cloud.stream.binder.kafka.properties.KafkaBinderConfigurationProperties` ?

**Comment by sobychacko** [comment]
This issue is no longer a requirement and out of scope. Closing the issue.
