### ISSUE TITLE
Add KStreams support

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-kafka#30]

**Comment by sabbyanandan** [comment]
Depends on https://github.com/spring-cloud/spring-cloud-stream/issues/519

**Comment by mbogoevici** [comment]
Duplicated by #144

**Comment by codependent** [comment]
@mbogoevici It's great to have KStreams available directly in Spring Cloud Streams. I only miss one thing: 

With Spring Kafka I wanted to use interative queries so I configured KStreams like this to generate a KTable:

```
KStream<Integer, JsonNode> stream = kStreamBuilder.stream(integerSerde, jsonSerde, STREAMING_TOPIC1);

        stream.map( (key, value) -> {
            return new KeyValue<>(value.get("productId").asInt(), value.get("quantity").asInt());
        }).groupByKey().reduce( (v1, v2) -> v1 + v2, "ProductsStock");
```
The in my business service I injected `KStreamBuilderFactoryBean` to have access to KafkaStreams and thus be able to implement the query against the previously defined store:

@Autowired
private KStreamBuilderFactoryBean kStreamBuilderFactoryBean;

```
@Override
public Integer getProductStock(Integer id) {
        KafkaStreams streams = kStreamBuilderFactoryBean.getKafkaStreams();
        ReadOnlyKeyValueStore<Integer, Integer> keyValueStore =
        streams.store("ProductsStock", QueryableStoreTypes.keyValueStore());
        return keyValueStore.get(id);
}
```

Can we do the same when using Spring Cloud Streams?

**Comment by artembilan** [comment]
@codependent ,

Yes, according to the code in the  PR #159  from @sobychacko , we have:
```
@Bean(name = KafkaStreamsDefaultConfiguration.DEFAULT_KSTREAM_BUILDER_BEAN_NAME)
public KStreamBuilderFactoryBean defaultKStreamBuilder(
```
So, that is really feasible what we have discussed with you in the https://github.com/spring-projects/spring-kafka/issues/365

Why do you think that might be something different?

Thanks for your feedback though!
