### ISSUE TITLE
ClassCast exception when  testing a KStream application

### ISSUE THREAD

**Issue by Veske** [spring-cloud/spring-cloud-stream-binder-kafka#304]
I am getting a classcast exception when starting my application using KStreams on Ditmars.SR3.

ClassCast exception happens in BindingService bindProducer():

```
Binding<T> binding = binder.bindProducer(bindingTarget, output,
				producerProperties);
```

The output I have is not of type MessageChannel.

The reason is not is that when in KStreamBoundElementFactory.class createOutput method... we get a `Method threw 'java.lang.IllegalStateException' exception. Cannot evaluate org.springframework.cloud.stream.binder.kstream.$Proxy96.toString()` when trying to get a proxy from our ProxyFactory that was just built. 

When building the input, everything works and we get back a correct KStreamImpl.

This only happens when I am trying to test my application with embedded Kafka. Currently it is impossible due to this error it seems. Application it self works fine tough.

**Comment by sobychacko** [comment]
@Veske Are you including the regular Kafka binder in the classpath? Also, any chance you can upgrade to the latest `2.0.0.BUILD-SNAPSHOT`? We made a lot of improvements there and would like to get more feedback.

**Comment by Veske** [comment]
It seems that I was able to fix it by composing the pom file a bit differently. 
Before I was including in Spring cloud stream but now I am including in spring cloud with version Edgware.SR2. Managed to get it working finally altough hacks had to be made still in testing part.
