### ISSUE TITLE
PartitionHandler unaware of Kafka partition count

### ISSUE THREAD

**Issue by sladkoff** [spring-cloud/spring-cloud-stream-binder-kafka#309]
On version **1.3.2.RELEASE**

**Expectation**

I expect the `PartitionHandler` to use the partition count that is available on the Kafka Topic. 

Logging indicates that: `The partitionCount of the producer for topic facts is 1, smaller than the actual partition count of 2 of the topic. The larger number will be used instead.` 

**Problem**

When I step throught the `PartitionHandler#determinePartition` method, I see that `producerProperties.getPartitionCount() = 1` and my messages arrive in the incorrect Kafka partition.

I already updated from 1.2.2 to 1.3.2 after noticing https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/184 which was supposed to be fixed.

**Comment by garyrussell** [comment]
Confirmed this is still a bug; the comment in that commit in incorrect; in a real environment the binder and partition handler don't hold a reference to the same properties instance; the test is not realistic.
