### ISSUE TITLE
Make KafkaBinderHealthIndicator a conditional on HealthIndicator to avoid CNFE

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream-binder-kafka#322]
Make `KafkaBinderHealthIndicator` conditional on `org.springframework.boot.actuate.health.HealthIndicator` to avoid CNFE during runtime.

**Comment by olegz** [comment]
Given that actuator dependencies are now optional we forgot to annotate `KafkaHealthIndicator` as bean conditional on `org.springframework.boot.actuate.health.HealthIndicator` resulting in `ClassNotFoundException`. This will be fixed for the release, but for now the workaround is to simply add actuator dependency in your project:
```
dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
```

**Comment by sobychacko** [comment]
This is fixed via https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/323.
