### ISSUE TITLE
KafkaProperties is not found when explicit binder configuration is used

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream-binder-kafka#326]
Without explicitly adding `KafkaAutoConfiguration` to the binder configuration, KafkaProperties is not found when using explicit (and multiple) binder configurations.

**Comment by garyrussell** [comment]
This is because the provisioner now has a hard reference to `KafkaProperties` - I don't know why boot doesn't process the `KafkaAutoConfiguration` when we create the binder `SpringApplication`.

Also this: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka-core/src/main/java/org/springframework/cloud/stream/binder/kafka/properties/KafkaBinderConfigurationProperties.java#L48

(required = false)

is bogus; it means binders configured via `environment` properties won't inherit boot props.

**Comment by garyrussell** [comment]
Looks like the problem is the child is not a `@SpringBootApplication`.

This fails too

```java
@SpringBootApplication
public class NestedApplication {

	public static void main(String[] args) {
		ConfigurableApplicationContext ctx = new SpringApplicationBuilder(NestedApplication.class)
				.run();
		KafkaProperties props = ctx.getBean(KafkaProperties.class);
		System.out.println("main: " + props.getBootstrapServers());
		ctx.close();
	}

	@Bean
	public ApplicationRunner runner() {
		return args -> {
			SpringApplicationBuilder builder = new SpringApplicationBuilder(com.example2.Nested.class);
			ConfigurableApplicationContext ctx = builder.run();
			System.out.println(ctx.getBean(String.class));
			try {
				KafkaProperties props = ctx.getBean(KafkaProperties.class);
				System.out.println("nested: " + props.getBootstrapServers());
			}
			catch (Exception e) {
				e.printStackTrace();
			}
			ctx.close();
		};
	}

}
```

and

```java
@Configuration
public class Nested {

	@Bean
	public String string() {
		return "foo";
	}

}
```

```
foo
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.boot.autoconfigure.kafka.KafkaProperties' available
```

If I change it to 

```java
@SpringBootApplication
public class Nested {

	@Bean
	public String string() {
		return "foo";
	}

}
```

I get

```
Caused by: javax.management.InstanceAlreadyExistsException: org.springframework.boot:type=Admin,name=SpringApplication
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437) ~[na:1.8.0_131]
```

even with 

```
spring.jmx.enabled=false
```

**Comment by garyrussell** [comment]
This works...

```java
@SpringBootApplication(exclude = SpringApplicationAdminJmxAutoConfiguration.class)
public class Nested {

	@Bean
	public String string() {
		return "foo";
	}

}
```

```
foo
nested: [localhost:9092]
main: [localhost:9092]
```

**Comment by olegz** [comment]
@garyrussell @sobychacko  While trying to compare the same in Rabbit binder I noticed that Rabbit has an extra import in `RabbitServiceAutoConfiguration`:
```
@Import(RabbitAutoConfiguration.class)
```
We don't have the same in Kafka. 
After adding it to `KafkaBinderConfiguration` everything seems to align and test passes.
Please give it a look and confirm that you see the same, so we can make the change.

**Comment by garyrussell** [comment]
Yes; agreed.
