### ISSUE TITLE
DLQs do not work with headerMode: raw in spring-cloud-stream-binder-kafka v1.3.2 as KafkaMessageChannelBinder.getErrorMessageHandler always uses EmbeddedHeaderUtils when it encounters a Throwable payload.

### ISSUE THREAD

**Issue by jmax01** [spring-cloud/spring-cloud-stream-binder-kafka#344]
DLQs throw when `headerMode: raw` in `spring-cloud-stream-binder-kafka` v1.3.2 as `KafkaMessageChannelBinder.getErrorMessageHandler` always uses `EmbeddedHeaderUtils` when it encounters a `Throwable` payload. 

Also it seems to me that when the error message payload is not a `Throwable` the meta-data about the failed record and any of the original headers should be placed in the DLQ message header.

I believe this would require dependency updates. 
```xml
		<kafka.version>0.11.0.1</kafka.version>
		<spring-kafka.version>1.3.3.RELEASE</spring-kafka.version>
		<spring-integration-kafka.version>2.3.0.RELEASE</spring-integration-kafka.version>
```
However `KafkaBinderJaasInitializerListener` uses `JaasUtils.LOGIN_CONTEXT_CLIENT` which was removed in Kafka 0.11.

So _**current**_ usage of `KafkaBinderJaasInitializerListener` may break with newer Kafka clients.

I am not familiar enough with this to fix it and will submit my PR with do not merge.

Additional changes: 
 - Removal of needless `byte[]-> ByteBuffer->byte[]` actions:
    `byte[] payload = Utils.toArray(ByteBuffer.wrap((byte[]) record.value()))`
- Additional meta-data should be added to the DLQ message headers:
```java
	public static final String X_EXCEPTION_FQCN = "x-exception-fqcn";
	public static final String X_ORIGINAL_OFFSET = "x-original-offset";
	public static final String X_ORIGINAL_PARTITION = "x-original-partition";
	public static final String X_ORIGINAL_TIMESTAMP = "x-original-timestamp";
	public static final String X_ORIGINAL_TIMESTAMP_TYPE = "x-original-timestamp-type";
```

**Comment by garyrussell** [comment]
There is a kafka11 artifact (0.11 branch) that supports the 0.11 kafka-clients.

There are instructions at [the bottom of the project page](https://cloud.spring.io/spring-cloud-stream/) for using it instead of the 0.10 binder.

**Comment by jmax01** [comment]
OK I will close then
