### ISSUE TITLE
why spring.cloud.stream.default.consumer.concurrency=5 is not work

### ISSUE THREAD

**Issue by ZT5250** [spring-cloud/spring-cloud-stream-binder-kafka#347]
I set this :
`
spring:
  cloud:
    stream:
      default:
          consumer:
            concurrency: 5
`
in my spring boot yml file, but when i start my spring boot application i got this warning from the console:
`The number of expected partitions was: 5, but 1 has been found instead.There will be 4 idle consumers`
it seemed my setting is not work, i want to know the reason, is there any other things i need to pay attention to?

**Comment by artembilan** [comment]
Maybe this `spring.cloud.stream.kafka.binder.autoAddPartitions=true`?

https://docs.spring.io/spring-cloud-stream/docs/Elmhurst.RC3/reference/htmlsingle/#_configuration_options_2

**Comment by ZT5250** [comment]
Thank you! yes it is, i just add
 `spring.cloud.stream.kafka.binder.autoAddPartitions=true` 
to my yml file, and it works! This problem bothered me for few days until you come up!

**Comment by artembilan** [comment]
Great! 
In the future, please, consider to ask questions on StackOverflow.
You may get an answer quickly because there are more Community to help and here is only our team.

**Comment by ZT5250** [comment]
okay, thank you! I will ask questions on StackOverflow in the future, thank you for your help.  👍
