### ISSUE TITLE
KTable binding in Kafka Streams binder

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream-binder-kafka#354]
When we do an inbound binding on KTable, currently the deserialization is done by the broker. As a developer, if I choose Spring Cloud Stream to do this deserialization it should be possible to do so.

**Comment by msmsimondean** [comment]
See https://github.com/msmsimondean/spring-cloud-stream-kafka-streams/blob/master/src/main/java/com/example/analytics/AnalyticsApplication.java#L113 for an example

**Comment by sobychacko** [comment]
Starting from 3.0, we default to Kafka Streams provided native Serdes for de/serialization. There is still a way to use the framework serialization for `KStream`. We haven't encountered a need for providing the same for the table types. Closing the issue.
