### ISSUE TITLE
Interactive query issues when multiple Kafka Streams instances are used

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream-binder-kafka#369]
When there are multiple instances of the same Kafka Streams application, support for interactive queries in the binder is unstable. Especially, when a particular state store is hosted on a different instance and the query is invoked against another instance, it may not produce correct results or throw exceptions. Binder should expose `StreamsMetadata` from the underlying `KafkaStreams` object so that the user can decide which host to invoke the query against.

**Comment by tzolov** [comment]
From `superficial` review (could not dive too much into logic's internals) the PR looks good and is ready to merge.
