### ISSUE TITLE
Use Kafka 2.0 Test Support for KStreams Binder

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-kafka#371]

**Comment by sabbyanandan** [comment]
Child of #370

**Comment by sobychacko** [comment]
Spring cloud stream kafka streams applications are spring boot applications. The best way to test these applications is by running them as boot applications or by loading the corresponding configuration classes in the tests and using an [embedded kafka broker](https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka-test/src/main/java/org/springframework/kafka/test/EmbeddedKafkaBroker.java) provided by the spring-kafka project along with it. The kafka streams binder uses this approach for integration testing [extensively](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/tree/master/spring-cloud-stream-binder-kafka-streams/src/test/java/org/springframework/cloud/stream/binder/kafka/streams/integration). 

If the users want to unit test their kafka streams application, they can go with the strategy outlined [here](https://kafka.apache.org/20/documentation/streams/developer-guide/testing.html) by directly including the `kafka-streams-test-utils` as a test dependency in the application itself.
