### ISSUE TITLE
Add binding support for GlobalKTable

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream-binder-kafka#384]

**Comment by orchesio** [comment]
+1
Where are we on this? We're also thinking about doing this.

**Comment by sobychacko** [comment]
@orchesio It is on the roadmap. We will try to get to it, in the meantime, if you want to tackle it, please do so and feel free to PR.

**Comment by RawToast** [comment]
@sobychacko please could a contributor someone fix the typo in this issue request? It would help with visibility of this issue, as at the moment nothing appears in a search of this repository for `GlobalKTable`

**Comment by garyrussell** [comment]
@RawToast Done.
