### ISSUE TITLE
KafkaBinderProperties does not override with the KafkaBinderConfigurationProperties

### ISSUE THREAD

**Issue by prashantulavapalli** [spring-cloud/spring-cloud-stream-binder-kafka#385]
the Kafka Streams Binder topic does not seem to take the overrides provided in application.yml (or application.properties)
I have added the property - (default port for Kafka is different)
`spring.cloud.stream.kafka.streams.binder.brokers: localhost:29092 `

The KafkaBinderConfiguration seems to read from KafkaBinderConfigurationProperties by initializing a new new KafkaBinderConfigurationProperties() and does not read the binder properties in application.yml
```
 @Configuration
@ConditionalOnMissingBean({Binder.class})
@Import({KafkaAutoConfiguration.class, PropertyPlaceholderAutoConfiguration.class, KafkaBinderHealthIndicatorConfiguration.class})
@EnableConfigurationProperties({KafkaExtendedBindingProperties.class})
public class KafkaBinderConfiguration {
    @Autowired
    private KafkaExtendedBindingProperties kafkaExtendedBindingProperties;
    @Autowired
    private ProducerListener producerListener;
    @Autowired
    private KafkaProperties kafkaProperties;

    public KafkaBinderConfiguration() {
    }

    @Bean
    KafkaBinderConfigurationProperties configurationProperties() {
        return new KafkaBinderConfigurationProperties();
    }

    @Bean
    KafkaTopicProvisioner provisioningProvider(KafkaBinderConfigurationProperties configurationProperties) {
        return new KafkaTopicProvisioner(configurationProperties, this.kafkaProperties);
    }

```

The KTableBinderConfiguration is doing the right thing with resolved KafkaBinderConfigurationProperties
```
public class KTableBinderConfiguration {
    @Autowired
    private KafkaProperties kafkaProperties;
    @Autowired
    private KafkaStreamsExtendedBindingProperties kafkaStreamsExtendedBindingProperties;

    public KTableBinderConfiguration() {
    }

    @Bean
    public KafkaTopicProvisioner provisioningProvider(KafkaBinderConfigurationProperties binderConfigurationProperties) {
        return new KafkaTopicProvisioner(binderConfigurationProperties, this.kafkaProperties);
    }

    @Bean
    public KTableBinder kTableBinder(KafkaStreamsBinderConfigurationProperties binderConfigurationProperties, KafkaTopicProvisioner kafkaTopicProvisioner, KafkaStreamsBindingInformationCatalogue KafkaStreamsBindingInformationCatalogue) {
        KTableBinder kStreamBinder = new KTableBinder(binderConfigurationProperties, kafkaTopicProvisioner, KafkaStreamsBindingInformationCatalogue);
        return kStreamBinder;
    }
}

```

the workaround for the override is to use the Kafka Spring Boot properties. 
`spring.kafka.producer.bootstrap-servers: localhost:29092`

**Comment by garyrussell** [comment]
Creating a new bean like that is fine because of...

```java
@ConfigurationProperties(prefix = "spring.cloud.stream.kafka.binder")
public class KafkaBinderConfigurationProperties {
```

That's what triggers the property population.

However, note that this class is shared between the kafka message channel binder and the KStream binder. I don't see the `.streams` element, but I am not familiar with the KStream binder so I don't know if there is some other magic involved - I do see that the documentation says to add the `.streams` element to the property.

Can you try `spring.cloud.stream.kafka.binder.brokers: localhost:29092` (without the `.streams` part).

cc/ @sobychacko

**Comment by garyrussell** [comment]
I just checked the KStreams binder config and it has

```java
	@Bean
	@ConfigurationProperties(prefix = "spring.cloud.stream.kafka.streams.binder")
	public KafkaStreamsBinderConfigurationProperties binderConfigurationProperties() {
		return new KafkaStreamsBinderConfigurationProperties();
	}
```

So it looks like you are using the message channel binder, not the KStream binder so you must not have that `.streams` element.

**Comment by prashantulavapalli** [comment]
Thanks @garyrussell . Yes it works with -
```spring.cloud.stream.kafka.binder.brokers: localhost:29092```

thanks. the [documentation](https://docs.spring.io/spring-cloud-stream/docs/Elmhurst.RELEASE/reference/htmlsingle/#_configuration_options_2) talks about the using the ``` spring.cloud.stream.kafka.binder.brokers ``` 

what through me off, i guess, is the configuration (Map with a key/value pair containing properties pertaining to Apache Kafka Streams API.) is expected under the ```spring.cloud.stream.kafka.streams.binder. ```

thanks. this solves for what i am looking for. Thanks Gary for your help.

**Comment by sobychacko** [comment]
`spring.cloud.stream.kafka.stream.binder.brokers: ` should have worked. It didn't?
For example: `spring.cloud.stream.kafka.streams.binder.brokers: 192.168.99`

**Comment by garyrussell** [comment]
It sounds like he was incorrectly using the KStream binder configuration properties for a message channel binder,

**Comment by sobychacko** [comment]
Ah - thanks @garyrussell. 
@prashantulavapalli  Can we close this issue then?

**Comment by prashantulavapalli** [comment]
@sobychacko - Yes we can close this. thanks for the quick closure on this.
