### ISSUE TITLE
Serde with custom aggregater 

### ISSUE THREAD

**Issue by vinu** [spring-cloud/spring-cloud-stream-binder-kafka#386]
Can any please let me know what is the best way to set the serde for the materialized stores with custom aggregater class 
Following is my aggregation 

`groupByKey()
                .windowedBy(TimeWindows.of(1000).until(1000))
                .aggregate(DataAggregate::new, (key, value, aggregate) -> {
                    aggregate.add(1);
                    return aggregate;
                }, Materialized.as("aggstore"))`

DataAggregate is the class that holds the aggregation - I need to save that to `aggstore`

but the default serde I am using is the 
`spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms=1000
spring.cloud.stream.kafka.streams.binder.configuration.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.kafka.streams.binder.configuration.default.value.serde=org.apache.kafka.common.serialization.Serdes$StringSerde`

exception I am getting is 
`Exception in thread "eventsin-00aacb65-5224-4b2f-858b-fe98bd134b7c-StreamThread-1" java.lang.ClassCastException: sample.streamprocessor.dataaggregator.DataAggregate cannot be cast to java.lang.String
	at org.apache.kafka.common.serialization.StringSerializer.serialize(StringSerializer.java:28)
	at org.apache.kafka.streams.state.StateSerdes.rawValue(StateSerdes.java:178)
	at org.apache.kafka.streams.state.internals.MeteredWindowStore.put(MeteredWindowStore.java:96)
	at org.apache.kafka.streams.kstream.internals.KStreamWindowAggregate$KStreamWindowAggregateProcessor.process(KStreamWindowAggregate.java:122)
`

**Comment by olegz** [comment]
Perhaps @sobychacko will provide more info, but from the exception stack trace it looks pretty clear to me that you are using the wrong serde as it expects `String` and you are passing `DataAggregate`.
Why did you expect it to work in the first place?

**Comment by orchesio** [comment]
@vinu The Serdes specified in application.yml are for input/output topics. In your case it's for state store, which can be specified by providing key/value serdes to Materialized explicitly.
Details in doc.
https://kafka.apache.org/10/javadoc/org/apache/kafka/streams/kstream/Materialized.html#withValueSerde-org.apache.kafka.common.serialization.Serde-

**Comment by sobychacko** [comment]
@vinu what @olegz and @orchesio said above. You need to pass the proper key and value `Serde` when you materialize the state store. Since you are not passing any `Serde`s for that, the defaults are kicking in and running into that exception. You need to use the `Materialized.with...` methods for that. If your `DataAggregate` is `json` friendly, you can use the `JsonSerde` provided as part of spring-kafka and pass a reference of this to your aggregation. Hope this helps.

**Comment by vinu** [comment]
thanks @sobychacko @orchesio - for that 
It worked good with the valueserde with `Materialized.with` 

is there any option to set the `JsonSerde` to the application level 
I tried with 
`spring.cloud.stream.kafka.streams.binder.configuration.default.value.serde=org.springframework.kafka.support.serializer.JsonSerde`

but it error-ed with 
```
Caused by: java.lang.IllegalStateException: No type information in headers and no default type provided
	at org.springframework.util.Assert.state(Assert.java:73)
	at org.springframework.kafka.support.serializer.JsonDeserializer.deserialize(JsonDeserializer.java:220)

```

the producer is writing to the topic as string json - that is a separate application

**Comment by sobychacko** [comment]
@vinu - You cannot directly use the `JsonSerde` class like that. However, you can extend from this in your project and use it in properties. For instance, 
```
FooSerde extends JsonSerde<Foo> {}
```
and then 
`spring.cloud.stream.kafka.streams.binder.configuration.default.value.serde=FooSerde`

**Comment by vinu** [comment]
I am closing this issue - I think I have enough information on this at this moment :) 
thanks guys

**Comment by nehasewda** [comment]
Hi @sobychacko ,

I am facing same issue with providing custom serde in spring cloud stream application.
I have already tried with - 
1. defining custom bean serde.
2. creating a class extending JsonSerde and provide the class in  application.yml via spring.cloud.stream.kafka.streams.binder.configuration.default.value.serde=<classname>.
But nothing worked.
Not sure what's missing. Kindly help.

**Comment by sobychacko** [comment]
@nehasewda I think you are referring to [this issue](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/1168), right? See my latest [comment](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/1168#issuecomment-965746836) on that issue.
