### ISSUE TITLE
May I use the aws sqs with the binder?

### ISSUE THREAD

**Issue by sofior** [spring-cloud/spring-cloud-stream-binder-kafka#387]
My company don't want to manage the mq machine

**Comment by sobychacko** [comment]
Not clear what the request is. We provide a binder for aws Kinesis. You can find more details [here](https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis). If you have specific questions regarding the Kafka binder in this context, please check back here. Closing this issue for the time being.
