### ISSUE TITLE
Wrong comparsion in JaasLoginModuleConfiguration

### ISSUE THREAD

**Issue by bleipold** [spring-cloud/spring-cloud-stream-binder-kafka#394]
Hi,

when trying to start a stream app with Spring Cloud Dataflow Server with Kafka as message broker I get following error message:

``Field error in object 'spring.cloud.stream.kafka.binder' on field 'jaas.controlFlag': rejected value [required];``

After having a look at the code in JaasLoginModuleConfiguration#setControlFlag (line 57f), it's quite obvious that this cannot work since LoginModuleControlFlag.equals(String) will always return false.

**Comment by olegz** [comment]
@bleipold the stack trace would help

**Comment by bleipold** [comment]
All I can give you at the moment is this [error.txt](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/files/2104911/error.txt). I will try to get a stack trace.

**Comment by bleipold** [comment]
Here is the [stack trace](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/files/2105183/stacktrace.txt).

**Comment by sabbyanandan** [comment]
Hi, @bleipold. This doesn't include any errors. Can you provide the actual stack trace?

**Comment by sobychacko** [comment]
@bleipold Can you check again against the latest snapshot on the master branch? We had a recent commit that went in that fixed some of the issues associated with `JassLoginModuleConfiguration`.

**Comment by sobychacko** [comment]
@bleipold Closing this issue since we haven't heard from you regarding further updates. See my comments above about the fixes made in `JassLoginModuleConfiguration`. Please reopen if you are still seeing the issues.
