### ISSUE TITLE
Binder throws MessageHandlingException when destination.errors is configured

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-stream-binder-kafka#395]
While working on [this](https://github.com/spring-cloud/spring-cloud-stream/issues/1384) I've discovered this issue:

Here is how to reproduce:
Application
```
@StreamListener("input")
public void handle(String message) {
        System.out.println("Received message: " + message);
        throw new RuntimeException("Boom");
}

@ServiceActivator(inputChannel = "errorChannel") //channel name 'input.myGroup.errors'
public void error(Message<?> message) {
        System.out.println("Handling ERROR: " + message);
}
```
Configuration:
```
spring:
  cloud:
      stream:
        bindings:
          input:
            destination: input
            group: myGroup
            binder: kafka
          error:
            destination: errors
            binder: kafka
```
Exception:
`
org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder$ProducerConfigurationMessageHandler@29203d7f]; nested exception is org.apache.kafka.common.errors.SerializationException: Can't convert value of class org.springframework.messaging.MessagingException to class org.apache.kafka.common.serialization.ByteArraySerializer specified in value.serializer, failedMessage=ErrorMessage [payload=org.springframework.messaging.MessagingException: Exception thrown while invoking io.spring.barcelona.springcloudstreamdemorabbit.SpringCloudStreamDemoRabbitApplication#handle[1 args]; nested exception is java.lang.RuntimeException: Boom, failedMessage=GenericMessage [payload=byte[9], headers={kafka_offset=1, kafka_consumer=org.apache.kafka.clients.consumer.KafkaConsumer@7fffafd2, deliveryAttempt=3, kafka_timestampType=CREATE_TIME, kafka_receivedMessageKey=null, kafka_receivedPartitionId=0, kafka_receivedTopic=input, kafka_receivedTimestamp=1528986379041, contentType=application/json}], headers={kafka_data=ConsumerRecord(topic = input, partition = 0, offset = 1, CreateTime = 1528986379041, serialized key size = -1, serialized value size = 9, headers = RecordHeaders(headers = [], isReadOnly = false), key = null, value = [B@5b88dce4), id=2f645c3c-a719-0e05-46dd-c01731954015, timestamp=1528988603774}]
`

**Comment by sobychacko** [comment]
This issue is resolved via https://github.com/spring-cloud/spring-cloud-stream/commit/a82c906913d9dbf0c42810443adce3ec1b2b5eb6
With this change, the usage of setting `error.destination` and binding the global error channel to it are removed. The preferred way to receive error messages in the broker is through the DLQ mechanism.
