### ISSUE TITLE
Provide an easy option to apply same connection credentials for Kafka and KStreams binders

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-kafka#401]
As a user, while orchestrating Kafka and KStream Apps in K8S, I'm _requried_ to supply connection creds for both Kafka and KStreams binders individually (see below), albeit they both are using the same Kafka broker. 

Deployment manifest had to incude:
> \"spring.cloud.skipper.server.platform.kubernetes.accounts.minikube.environmentVariables\" : \"SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=${KAFKA_SERVICE_HOST}:${KAFKA_SERVICE_PORT},SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=${KAFKA_ZK_SERVICE_HOST}:${KAFKA_ZK_SERVICE_PORT},SPRING_CLOUD_STREAM_KAFKA_STREAMS_BINDER_BROKERS=${KAFKA_SERVICE_HOST}:${KAFKA_SERVICE_PORT},SPRING_CLOUD_STREAM_KAFKA_STREAMS_BINDER_ZK_NODES=${KAFKA_ZK_SERVICE_HOST}:${KAFKA_ZK_SERVICE_PORT}\"

Without the explicit declaration, the KStream specific channels were defaulting to `localhost` at runtime, and it failed to bootstrap.

Notes: 

For when the same broker is used, we could simplify it by reusing the same connection properties for both the binders. We don't need the extra `spring.cloud.stream.kafka.streams.binder` prefix literal in that case.

For when the broker is different, we could continue to provide the ability to supply different creds, but I'm not sure if it is relevant in real-world scenarios and also based on how KStreams work.

relates to spring-cloud/spring-cloud-stream-binder-kafka#400
relates to spring-cloud/spring-cloud-dataflow-server-kubernetes#306

**Comment by sobychacko** [comment]
In the scenario in which we have both binders present on the classpath, we can fall back to the boot configuration `spring.kafka.bootstrap-servers` since that will be applied to both binders. This way, we can avoid repeating the bootstrap configuration per binder. I think this is a reasonable compromise when we have both binders in the same app. @sabbyanandan What do you think?

**Comment by sabbyanandan** [comment]
@sobychacko: Yes; that'd simplify the current requirement to supply k/v pairs for Kafka and KStream binders individually. Please feel free to issue a PR to K8s-server docs with the recommendation.

**Comment by sobychacko** [comment]
@sabbyanandan will do. Thanks for the confirmation!

**Comment by sobychacko** [comment]
Since we have more occurrences of this issue, reopening it.
