### ISSUE TITLE
Kafka Health actuator indicator fail randomly

### ISSUE THREAD

**Issue by Delorien84** [spring-cloud/spring-cloud-stream-binder-kafka#404]
Hi, 
 I have simple service, that produce messages to Kafka topic using spring cloud stream. The service is added into Consul service discovery. Consul indicate, that the service is randomly failed. Consul use `/actuator/health` endpoint to indicate if service is in healthy state. Some call to the service return 503 with detail

```
HTTP GET http://172.31.135.146:9080/actuator/health: 503 Service Unavailable Output: 
{
  "status":"DOWN", 
  "binders": {
    "status":"DOWN",
    "details":{
      "kafka":{
        "status":"DOWN",
        "details":{
          "healthIndicator": {
            "status":"DOWN",
            "details": {
              "error":"java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access"
             }
           }
         }
       }
     }
   },
  ....
}
```

It seems that this happened in case parallel call is done on `/actuator/health` endpoint.

Using Spring Boot 2.0.3 and Spring Cloud Finchley.RELEASE

**Comment by garyrussell** [comment]
Broken by https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/231
