### ISSUE TITLE
Unable to set arbitrary properties on Consumer or Producer

### ISSUE THREAD

**Issue by Woodham** [spring-cloud/spring-cloud-stream-binder-kafka#417]
I have a very specific case but can't find a way to work around my issue. I need to set a custom serializer and deserializer class for my kafka producer and consumer, which is fine because I can just set the class using the properties. 

However, these custom serializer/deserializers look for a custom property inside the config map of the producer/consumer respectively, and I cannot add these properties when using Spring Cloud Stream.

I believe it's because of these snippets from `KafkaBinderConfigurationProperties.java`:

```
// Copy configured binder properties
for (Map.Entry<String, String> configurationEntry : this.configuration.entrySet()) {
	if (ConsumerConfig.configNames().contains(configurationEntry.getKey())) {
		consumerConfiguration.put(configurationEntry.getKey(), configurationEntry.getValue());
	}
}
```

```
// Copy configured binder properties
for (Map.Entry<String, String> configurationEntry : configuration.entrySet()) {
	if (ProducerConfig.configNames().contains(configurationEntry.getKey())) {
		producerConfiguration.put(configurationEntry.getKey(), configurationEntry.getValue());
	}
}
```

I can see the intent is to validate the producer and consumer properties before propagating them through to the Kafka client, however by doing so it filters out my custom properties.

Is there any way I can force the setting of arbitrary properties on the consumer/producer when using the kafka binder?

**Comment by garyrussell** [comment]
What version are you using? In 2.0, producer and consumer now has a generic `properties` property map: https://docs.spring.io/spring-cloud-stream/docs/Elmhurst.RELEASE/reference/htmlsingle/index.html#kafka-consumer-properties.

For earlier versions, use `spring.kafka.properties.foo.bar=baz`.

**Comment by Woodham** [comment]
I'm using 2.0, and that's pretty much what I'm trying to do. The issue I believe is the code above, where for e.g. the consumer:

```ConsumerConfig.configNames().contains(configurationEntry.getKey())```

It only adds the properties to the `consumerConfiguration` map if the key is present in the Apache Kafka client `ConsumerConfig` class. The property I'm trying to add isn't a standard kafka property so it just gets dropped.

**Comment by garyrussell** [comment]
That's the binder configuration properties; the link I provided is for binding consumer properties

```
spring.cloud.stream.bindings.myInput.consumer.properties.foo.bar=baz
```

**Comment by Woodham** [comment]
Sorry I must be missing something here, I still can't get this to work via spring-cloud-stream properties.

I don't see a config value documented at your link for `properties`, do you mean `configuration`? Either way I still can't seem to get arbitrary properties propagated to the Kafka consumer.

I put a breakpoint on the constructor of the Apache `KafkaConsumer` class, and have tried combinations of:

```
spring.cloud.stream.bindings.input.consumer.configuration.SOME_PROPERTY=SOME_VALUE
spring.cloud.stream.bindings.input.consumer.properties.SOME_PROPERTY=SOME_VALUE
spring.cloud.stream.bindings.default.consumer.configuration.SOME_PROPERTY=SOME_VALUE
spring.cloud.stream.bindings.default.consumer.properties.SOME_PROPERTY=SOME_VALUE
```

However none of them seem to propagate. 

Fortunately using the Spring boot property `spring.kafka.properties.foo.bar=baz` as you suggest does work, which solves my problem.

**Comment by garyrussell** [comment]
Apologies; the documentation is incorrect; it's `consumer-properties` on the binder (since 2.1) and `configuration` on the binding.

The binder merges boot, binder and binding properties (in that order).

With 2.0, we can have:

```properties
spring.kafka.properties.some.common.property=foo
spring.kafka.consumer.properties.some.consumer.property=bar

spring.cloud.stream.kafka.binder.configuration.max.poll.records=42 #legacy only known consumer/producer properties allowed here

spring.cloud.stream.kafka.bindings.input.consumer.configuration.some.binding.consumer.property=qux
```
Result:

>{key.deserializer=class org.apache.kafka.common.serialization.ByteArrayDeserializer, some.common.property=foo, value.deserializer=class org.apache.kafka.common.serialization.ByteArrayDeserializer, enable.auto.commit=false, max.poll.records=42, group.id=anonymous.b6d914e8-f982-4613-9a56-22353b1ff0c8, some.consumer.property=bar, some.binding.consumer.property=qux, bootstrap.servers=localhost:9092, auto.commit.interval.ms=100, auto.offset.reset=latest}

In 2.1, we've added it at the binder level...

```properties
spring.cloud.stream.kafka.binder.consumer-properties.some.binder.consumer.property=baz
```

>{key.deserializer=class org.apache.kafka.common.serialization.ByteArrayDeserializer, some.binder.consumer.property=baz, some.common.property=foo, value.deserializer=class org.apache.kafka.common.serialization.ByteArrayDeserializer, enable.auto.commit=false, max.poll.records=42, group.id=anonymous.b6d914e8-f982-4613-9a56-22353b1ff0c8, some.consumer.property=bar, some.binding.consumer.property=qux, bootstrap.servers=localhost:9092, auto.commit.interval.ms=100, auto.offset.reset=latest}

**Comment by garyrussell** [comment]
I'll keep this issue open to fix the docs.

**Comment by Woodham** [comment]
Ah great that makes sense, thanks for the clarification!
