### ISSUE TITLE
Exposing lag metrics

### ISSUE THREAD

**Issue by scoof** [spring-cloud/spring-cloud-stream-binder-kafka#422]
According to the docs, the binder should expose a lag metric automatically:

> Kafka binder module exposes the following metrics:
> 
> spring.cloud.stream.binder.kafka.someGroup.someTopic.lag: This metric indicates how many messages have not been yet consumed from a given binder’s topic by a given consumer group. For example, if the value of the metric spring.cloud.stream.binder.kafka.myGroup.myTopic.lag is 1000, the consumer group named myGroup has 1000 messages waiting to be consumed from the topic calle myTopic. This metric is particularly useful for providing auto-scaling feedback to a PaaS platform.

This seems to happen if we manually import KafkaBinderConfiguration, but not automatically. I can't find any trace of autoconfiguration of this.

**Comment by sobychacko** [comment]
@scoof Can you elaborate what you are trying to do? By default, the Kafka binder will automatically import `KafkaBinderConfiguration` which will provide `KafkaBinderMetrics`. `KafkaBinderMetrics` itself is not intended for autoconfiguration. Btw - the metric name is changed to `spring.cloud.stream.binder.kafka.offset` in 2.0.0.RELEASE. We need to update the docs. I will use this issue to update the docs. Please let us know what you think.

**Comment by scoof** [comment]
I have no idea how I ended up at the above conclusion. It must have been the heat. You're correct, it is being recorded (in the new metric), so forget everything after "According" :)
I'll leave this open so you can fix the doc bug.

**Comment by sobychacko** [comment]
@scoof np! Thanks for the confirmation. I will update the docs and close this issue.

**Comment by sobychacko** [comment]
The docs fix is committed to master and cherry-picked to 2.0.x
