### ISSUE TITLE
KafkaMessageChannelBinder should support setting the topic name per message through the use of KafkaHeaders.TOPIC (i.e. "kafka_topic" header)

### ISSUE THREAD

**Issue by ngbalk** [spring-cloud/spring-cloud-stream-binder-kafka#423]
The `KafkaProducerMessageHandler` has the following logic to allow for the producer to drive the topic name through setting the "kafka_topic" header:

```java
String topic = this.topicExpression != null ?
		this.topicExpression.getValue(this.evaluationContext, message, String.class)
		: messageHeaders.get(KafkaHeaders.TOPIC, String.class);
```

However, in the `KafkaMessageChannelBinder`, we always set the topic expression:
https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/7007f9494a2f43e066141dda90c85cde62a83f1c/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java#L878

I feel that it would be nice if we could somehow take advantage of this feature in spring-integration-kafka by providing some logic or configuration to optionally set the topicExpression.  Then we could use the "kafka_topic" field to drive the destination topic name.  

I've noticed that the spring-cloud-streams abstraction will try to use the channelName as the topic name, so maybe we need some property like `headerDrivenTopicResolution=true` that will skip setting the topicExpression and rely on the "kafka_topic" header for the topic name (and fail if not present).

Thoughts?

Nick

**Comment by sabbyanandan** [comment]
Hi, @ngbalk / @Walliee! Based on our discussion yesterday, it sounded like you're already doing this using `BinderAwareChannelResolver`. You may have already managed to solve it with customizations - did I get that right? 

It'd be nice to learn how you're doing it, and if it is generic enough, we could even add it to the framework. 

If I misinterpreted any of this, feel free to clarify with a use-case, and we will be open to exploring options on our side.

**Comment by ngbalk** [comment]
@sabbyanandan  We use `BinderAwareChannelResolver` along with `AbstractMappingMessageRouter` to achieve our "multi-tenant topic routing".  In pseudo-code, it ends up looking something like this in our Impl of `AbstractMappingMessageRouter` : 
```java

  @Override
  protected List<Object> getChannelKeys(Message<?> message) {
    String tenantId = determineTenantId();
    String destinationTopicName = tenantId + "_" + originalTopicName;
    return destinationTopicName;
  }
```
When we return our new multitenant topicName from getChannelKeys, the BinderAwareChannelResolver will create the binding to a topic of that name for us.

**Comment by sabbyanandan** [comment]
Ah, thanks for the details. It looks straightforward. I wonder if there's an opportunity to provide a hook in the framework for handling things like this, but at the same time, I'm not sure if it'd be useful for the broader audience since it could be very use-case centric.

Perhaps there are other ways to solve it. @sobychacko: any other thoughts/recommendations?

**Comment by garyrussell** [comment]
There is a similar feature in the RabbitMQ binder, but that's facilitated by the way queues are bound to exchanges. With Rabbit, the exchange is the producer destination and the user can provide a custom `routingKeyExpression` to determine where the message is routed at runtime.

The Kafka message handler has a similar feature (topic selection based on the message), but we currently don't allow it to be configured...

`setTopicExpression(new LiteralExpression(topic));`

We could expose a producer property `useTopicHeaderForRouting` and simply don't set the expression if true. The logic looks like this

```
		String topic = this.topicExpression != null ?
				this.topicExpression.getValue(this.evaluationContext, message, String.class)
				: messageHeaders.get(KafkaHeaders.TOPIC, String.class);
```

i.e. The user code would be responsible for populating the `KafkaHeaders.TOPIC` before sending.

Or we could configure an expression to use that header first and, if null, fall back to the default destination.
