### ISSUE TITLE
Make HealthIndicator conditional on missing KafkaBinderHealthIndicatorConfiguration 

### ISSUE THREAD

**Issue by nhomble** [spring-cloud/spring-cloud-stream-binder-kafka#429]
Because of #404 health checks on any app pulling in the dependency will fail, does it make sense to always give users of the library the option to change the default health check? 

In springframeworks's kafka configuration [Add Kafka health indicator](https://github.com/spring-projects/spring-boot/pull/11515/files) the bean definition has that conditional. I suppose that's a nice pattern to follow.

**Comment by sobychacko** [comment]
@nhomble What do you mean by `"any app pulling in the dependency will fail"`? We cannot technically introduce `ConditionalOnMissingBean` in `KafkaBinderHealthIndicatorConfiguration` class as this not an auto configuration class. If you provide other health indicators, that will still be collected by the boot heath actuator.

**Comment by nhomble** [comment]
Hmm maybe it was a bad idea from me then - in this situation what would you recommend users do then? Currently, I ignore the health altogether by disabling in my properties since the configuration is guarded by enabling 'binders'. I still wanted to use the rest of the built-in checks though.

**Comment by sobychacko** [comment]
@nhomble Its not clear to me exactly what the use case you are trying to accomplish. There are few recent changes that went into this space. See [this issue](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/454) and the [associated PR](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/463) for more details. In addition, there is a [PR in flight in core](https://github.com/spring-cloud/spring-cloud-stream/pull/1504) that clarifies the docs on binder health indicators. 
If things are still unclear after reviewing these changes, please ping back here and elaborate on the usecase.
