### ISSUE TITLE
Creating a DLQ fails if group name does not pass topic name validations

### ISSUE THREAD

**Issue by odin-delrio** [spring-cloud/spring-cloud-stream-binder-kafka#43]
When the DLQ is created, the pattern to create the topic name is: 
- `error.<destination>.<group>`

The <group> part is refering to the current group name and this value is not validated with same rules as the topic name (using the **org.springframework.cloud.stream.binder.kafka.KafkaTopicUtils#validateTopicName** method)

So, if the group name contains special chars like ":" the dlq topic creation fails...

I would like to contribute to solve the problem, but I don't know what would be the better approach:
1. Validate the group name with the KafkaTopicUtils class if the **enableDlq** option is enabled
2. Filter the group name on the fly to create a valid DLQ topic name.

any suggestions?

**Comment by mbogoevici** [comment]
Thanks for the offer to contribute!

All things being equal, I believe that we can restrict group names to the same rules as destinations (and perhaps move the destination check to be a core feature). While it may reduce the flexibility somehow, it will help maintaining consistency across implementations. @garyrussell @markfisher - wdyt?

**Comment by sobychacko** [comment]
This issue is no longer a requirement and out of scope. Closing the issue.
