### ISSUE TITLE
Pattern-based topic names breaks Kafka healthchecks (KafkaBinderHealthIndicator.java)

### ISSUE THREAD

**Issue by ngbalk** [spring-cloud/spring-cloud-stream-binder-kafka#430]
The health checks fail in the KafkaBinderHealthIndicator.java because this topic name is not valid when using a pattern-based topic name (i.e. .*myDynamicTopicName).

error: "org.apache.kafka.common.errors.InvalidTopicException: Topic '.*myDynamicTopicName' is invalid"

This happens because we fetch partitionData from the kafka cluster for these dynamic topics and the `Fetcher` can't handle these patterns.

https://github.com/apache/kafka/blob/4f25f1fb7118825384f89ed9d00c08a54870e3aa/clients/src/main/java/org/apache/kafka/clients/consumer/internals/Fetcher.java#L297

**Comment by sabbyanandan** [comment]
Thanks for reporting this.

We should either make the health-checks and the pattern based binding mutually exclusive or look into why the health-indicator is relying on the topic. It should only be looking to make sure the connection can be successfully established.

**Comment by garyrussell** [comment]
Maybe a combination of the two - if consumer property `destinationIsPattern` is `true`, just use the admin to check if the broker is accessible.

**Comment by sobychacko** [comment]
@ngbalk Did you try what @garyrussell suggested? Are there any further updates to this issue?

**Comment by garyrussell** [comment]
? 

My comment was about the code changes we should make.

**Comment by sobychacko** [comment]
@garyrussell My bad. I misunderstood. Please ignore.
