### ISSUE TITLE
Binding level key serde not working for me

### ISSUE THREAD

**Issue by elvisols** [spring-cloud/spring-cloud-stream-binder-kafka#431]
So I have this configuration:

`# Define root config
spring.cloud.stream.kafka.streams.binder.application-id=eltstream
spring.cloud.stream.kafka.streams.binder.configuration.enable.idempotence=true
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms=1000
spring.cloud.stream.kafka.streams.binder.configuration.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.kafka.streams.binder.configuration.default.value.serde=com.code.challenge.backend.util.TransactionSerde

# oraclesource
spring.cloud.stream.bindings.oraclesource.destination=oraclesource
spring.cloud.stream.bindings.oraclesource.producer.header-mode=raw
spring.cloud.stream.bindings.oraclesource.producer.use-native-encoding=true
spring.cloud.stream.kafka.streams.bindings.oraclesource.producer.key-serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.kafka.streams.bindings.oraclesource.producer.value-serde=com.code.challenge.backend.util.StatSerde

# oraclesource
spring.cloud.stream.bindings.oraclesourcein.destination=oraclesource
spring.cloud.stream.bindings.oraclesourcein.group=oraclesourceingrp
spring.cloud.stream.bindings.oraclesourcein.producer.header-mode=raw
`

So from the console output, the default key/value were updated to StringSerde and TransactionSerde respectively, as expected. However, the **binding level key/value serde were still using the ByteArray Serializer**
`...
2018-08-22 11:15:22.079  INFO 21348 --- [  restartedMain] o.a.k.clients.producer.ProducerConfig    : ProducerConfig values: 
	acks = 1
	batch.size = 16384
	bootstrap.servers = [localhost:9092]
	buffer.memory = 33554432
	client.id = oraclesourceingrp-dba6b472-db3c-4526-b668-78dc61e42f44-StreamThread-1-producer
	compression.type = none
	connections.max.idle.ms = 540000
	enable.idempotence = true
	interceptor.classes = null
	key.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
	linger.ms = 100
	max.block.ms = 60000
	max.in.flight.requests.per.connection = 5
	max.request.size = 1048576
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	receive.buffer.bytes = 32768
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 10
	retry.backoff.ms = 100
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	send.buffer.bytes = 131072
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	transaction.timeout.ms = 60000
	transactional.id = null
	value.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
...
`

Please what possibly could I be doing wrong.

**Comment by sobychacko** [comment]
@elvisols Is this issue resolved? I think we already chatted on gitter on this same issue and you were able to resolve the problem. If so, feel free to close the issue.
