### ISSUE TITLE
renew Kerberos tickets 

### ISSUE THREAD

**Issue by raiusa** [spring-cloud/spring-cloud-stream-binder-kafka#439]
Can anyone explain how spring cloud stream Kafka binder renew Kerberos tickets?

**Comment by sobychacko** [comment]
@raiusa Kafka binder in spring cloud stream does not do anything for renewing Kerberos tickets. I don't think its a binder concern at all. If the broker is secured, then the binder provides mechanisms to communicate with that broker, but how the broker is secured is outside of the binder's responsibilities.

**Comment by sabbyanandan** [comment]
This is outside of the scope of the kafka binder. Closing it as invalid.
