### ISSUE TITLE
autoCommitOffset set to false does not allow manual acknowledgment

### ISSUE THREAD

**Issue by mnadelson** [spring-cloud/spring-cloud-stream-binder-kafka#44]
When I set spring.cloud.stream.kafka.bindings.<channel>.consumer.autoCommitOffset = false I am getting errors trying to manually acknowledge the message:

Caused by: java.lang.IllegalStateException: A manual ackmode is required for an acknowledging listener
	at org.springframework.util.Assert.state(Assert.java:392)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer$ConsumerAcknowledgment.acknowledge(KafkaMessageListenerContainer.java:991)

It looks like in KafkaMessageChannelBinder messageListenerContainer.getContainerProperties().setAckOnError is being set but not messageListenerContainer.getContainerProperties().setAckMode is not being set.

**Comment by mnadelson** [comment]
I cloned the code base ad added the following code to KafkaMessageChannelBinder.createConsumerEndpoint 

if (!properties.getExtension().isAutoCommitOffset())
	messageListenerContainer.getContainerProperties().setAckMode(AbstractMessageListenerContainer.AckMode.MANUAL);

This seemed to work.  Can I do a pull request and add the fix?

**Comment by mbogoevici** [comment]
Hi Mark, thanks for the feedback and contribution! The offer is very welcome!
We are looking at releasing this tonight - so if you can do a PR in that timeframe, we'd be happy to merge it.

**Comment by mbogoevici** [comment]
Fixed via https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/546fe6934683844668bb84bfce80aac4d27bf309
