### ISSUE TITLE
Consider using ImportBeanDefinitionRegistrar in the binder

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream-binder-kafka#445]
See this comment: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/441#discussion_r216783978

**Comment by sobychacko** [comment]
Closing this issue as this is addressed as part of the PR mentioned above.

**Comment by artembilan** [comment]
Don't we have similar problem in other places of the project?
For example: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/search?q=beanfactorypostprocessor&unscoped_q=beanfactorypostprocessor

**Comment by artembilan** [comment]
I mean that this issue could be used to address those problem and mentioned PR may be used as a reference how to proceed.

**Comment by sobychacko** [comment]
`ImportBeanDefinitionRegistrar` should be used in both `KStream` and `KTable` configurations where we currently check on a `Conditional` for a bean named `outerContext`. Refer to the `GlobalKTableConfiguration` where this change is already implemented.
