### ISSUE TITLE
Kafka Streams binder- application id checking precedence order

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream-binder-kafka#448]
When checking for application id - the binder currently gives the highest precedence to `group` set at the consumer binding level.  This has to be restructured as below.

If there is an application ID set at the individual binding level, use that. For example,  `spring.cloud.stream.kafka.streams.bindings.input.conusumer.applicationId`. If there are multiple bindings within a single processor (`StreamListener`), then the applications need to ensure that the same `applicationId` is used for all the bindings. 

If there is only a single processor (`StreamListener`) within the app, then in order to avoid repetition, it should be able to configure `applicationId` through a default configuration. For instance, `spring.cloud.stream.kafka.streams.default.consumer.applicionId`. 

Binder currently allows to set `applicationId` using a global binder level property (`spring.cloud.stream.kafka.streams.binder.applicationId`). This may not be needed because of the default mechanism mentioned above. However, in order to preserve backward compatibility, we may want to keep it as it is. 

If the user doesn't provide an `applicationId` through any of the mechanisms mentioned above, the binder uses a default one, but keep in mind that this will have unexpected behavior if there are multiple `StreamListeners` in the application. 

With these changes, we can avoid relying on `group` property on consumer bindings to infer `applicaitonId`. The `group` configuration can still be used, where it is needed per core spring cloud stream requirements, but kafka streams binder will not require it from applications.

**Comment by garyrussell** [comment]
Also consider boot 2.1 streams auto configuration.

At the global boot level, if there is no app id, we fall back to the spring.application.name.

In 2.1, the boot streams config should be considered the lowest priority, but should be used, as we do with the other binders.
