### ISSUE TITLE
Add support for wiring a custom rebalance listener

### ISSUE THREAD

**Issue by ghilainm** [spring-cloud/spring-cloud-stream-binder-kafka#453]
Could you please explain how to achieve exactly once delivery with Spring Cloud Stream and Kafka as binder?

I see two approaches:
- Idempotency of messages (store message identifiers and query DB in order to know if message has already been handled) 
- Manual offsets management and storing offsets in the same database as the one storing the results of the message consumption

For the first one I don't need any support. For the second one is it possible with the current design of Spring Cloud Stream?

It would be nice if there would be a topic explaining the different strategies in order to achieve the desired guarantees of delivery when using Spring Cloud Stream.

**Comment by sobychacko** [comment]
@ghilainm Can't you use the `Transactional` API support provided in the Kafka binder for achieving exactly-once-delivery guarantee? Here is a basic sample that shows how this can be done: https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/transaction-kafka-samples

Refer to the docs for the following properties for more info: `spring.cloud.stream.kafka.binder.transaction.transactionIdPrefix`
`spring.cloud.stream.kafka.binder.transaction.producer.*`.
The descriptions for these properties link to some other documentation.

See if that fits your needs.

**Comment by ghilainm** [comment]
@sobychacko  I want transaction which can span to my PostgreSQL database therefore the Kafka support for transaction is not useful. The offset would need to be stored in PostgreSQL and not Kafka to achieve what I need. But there could be some support for such use case in STS.

**Comment by garyrussell** [comment]
This is supported in spring-kafka - simply wire a `ConsumerAwareRebalanceListener` into the listener container so the app can perform seeks based on the database values. for the assigned partitions when the app starts up (or after a rebalance).

The binder currently does not support wiring in a custom rebalance listener; we should add that capability.

**Comment by garyrussell** [comment]
However, you still need to deal with idempotency (but rarely) since it will still be possible to get duplicates - e.g. DB txn commits and the server crashes before committing the Kafka offset.
