### ISSUE TITLE
Kafka Streams and Spring Cloud Stream Schema Registry

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream-binder-kafka#469]
With the new header support in Kafka Streams, we can now use Spring Cloud Stream provided Schema Registry with the Kafka Streams binder (#456). However, one that is addressed, the downstream Kafka Streams topology still needs to use an `Avro Serde` that can talk to the Spring Cloud Stream Schema Registry. This means that we need to expose our internal schema registry based `Avro` converter wrapped inside a `Serde`.

**Comment by maddenj-ie** [comment]
Hi @sobychacko Will this approach allow the use of the avro SpecificRecordBase class or SpecificRecord interface to be used as the target class of the input binding and consequently allow the topology to handle different avro types from a single kafka topic (Binding Destination)?  
This is probably out of scope for this PR but may be worth considering if an acceptable use case.

**Comment by sobychacko** [comment]
@maddenj-ie It should be possible to do what you are suggesting. Please try it out with the latest changes (the PR for this issue has just been merged). Closing this issue now, if you are still having problems with avro conversion, please raise another issue.
