### ISSUE TITLE
Documentation doesn't explain how `startOffsets` works for anon groups

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream-binder-kafka#48]
Implies it's always `earliest` by default but in fact anonymous groups start at `latest`.

**Comment by ilayaperumalg** [comment]
It looks like the `startOffset` property from `KafkaConsumerProperties` is not being used at all. The `auto.offset.reset` for the consumer is explicitly set to `earliest` or `latest` based on the consumer group. May be we depend on the `configuration` property for overriding this?

Also, there are few other properties `resetOffsets`, `recoveryInterval` also not used by the binder.

**Comment by mbogoevici** [comment]
Regarding `resetOffsets`, see https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/67

**Comment by gallaharsha** [comment]
Is version 1.1.2.RELEASE affected with this bug ? I'm trying to set: spring.cloud.stream.kafka.binder.configuration: startOffset: latest
to avoid consumer receiving processed messages after kafka restart. Please advise

**Comment by sobychacko** [comment]
Hi @gallaharsha 1.1.2 is a very old release. Any chance you can upgrade to the latest? The latest GA is `2.0.1.RELEASE` (`Elmhurst.SR1`). 

Consumer properties like `startOffset` etc. need to be applied at the binding level. For example, `spring.cloud.stream.kafka.bindings.input.conumser.startOffset`. 

When using `configuration` property on `spring.cloud.stream.kafka.binder`  as you have above, you need to directly provide kafk broker properties which will be passed down to the broker as they are.
