### ISSUE TITLE
Broken logic in resetOffsets() in KafkaMessageChannelBinder

### ISSUE THREAD

**Issue by scoof** [spring-cloud/spring-cloud-stream-binder-kafka#481]
Boolean not has moved inside the string "latest"
if (!"earliest".equals(resetTo) && "!latest".equals(resetTo)) {

I will try to submit a PR if/when time allows me to write a test

**Comment by sobychacko** [comment]
@scoof Thank you for reporting this issue. Created a PR: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/485
