### ISSUE TITLE
spring.cloud.stream.kafka.binder.autoCreateTopics false is not honored

### ISSUE THREAD

**Issue by estenwig** [spring-cloud/spring-cloud-stream-binder-kafka#497]
The property spring.cloud.stream.kafka.binder.autoCreateTopics: false is not honored in org.apache.kafka.clients.consumer.KafkaConsumer.partitionsFor(String, topic) . The method issues a call to issues a call to 
boolean allowAutoTopicCreation = true;
fetcher.getTopicMetadata(
                    new MetadataRequest.Builder(Collections.singletonList(topic), allowAutoTopicCreation), timeoutMs);

Discovered this on a broker with only access to Describe and Read permissions

Using Spring boot 2.1.0, spring clodu stream Fishtown.RC1

The stack is as follows:
```
partitionsFor:1774, KafkaConsumer (org.apache.kafka.clients.consumer)
partitionsFor:1742, KafkaConsumer (org.apache.kafka.clients.consumer)
lambda$getPartitionInfo$4:667, KafkaMessageChannelBinder (org.springframework.cloud.stream.binder.kafka)
call:-1, 1671184759 (org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder$$Lambda$751)
lambda$getPartitionsForTopic$2:394, KafkaTopicProvisioner (org.springframework.cloud.stream.binder.kafka.provisioning)
doWithRetry:-1, 881659641 (org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner$$Lambda$752)
doExecute:287, RetryTemplate (org.springframework.retry.support)
execute:164, RetryTemplate (org.springframework.retry.support)
getPartitionsForTopic:393, KafkaTopicProvisioner (org.springframework.cloud.stream.binder.kafka.provisioning)
getPartitionInfo:663, KafkaMessageChannelBinder (org.springframework.cloud.stream.binder.kafka)
processTopic:474, KafkaMessageChannelBinder (org.springframework.cloud.stream.binder.kafka)
createConsumerEndpoint:383, KafkaMessageChannelBinder (org.springframework.cloud.stream.binder.kafka)
createConsumerEndpoint:132, KafkaMessageChannelBinder (org.springframework.cloud.stream.binder.kafka)
doBindConsumer:353, AbstractMessageChannelBinder (org.springframework.cloud.stream.binder)
doBindConsumer:91, AbstractMessageChannelBinder (org.springframework.cloud.stream.binder)
bindConsumer:132, AbstractBinder (org.springframework.cloud.stream.binder)
lambda$rescheduleConsumerBinding$0:160, BindingService (org.springframework.cloud.stream.binding)
run:-1, 1708075462 (org.springframework.cloud.stream.binding.BindingService$$Lambda$758)
run:54, DelegatingErrorHandlingRunnable (org.springframework.scheduling.support)
call:511, Executors$RunnableAdapter (java.util.concurrent)
run$$$capture:266, FutureTask (java.util.concurrent)
run:-1, FutureTask (java.util.concurrent)
 - Async stack trace
<init>:151, FutureTask (java.util.concurrent)
<init>:209, ScheduledThreadPoolExecutor$ScheduledFutureTask (java.util.concurrent)
schedule:532, ScheduledThreadPoolExecutor (java.util.concurrent)
schedule:325, ThreadPoolTaskScheduler (org.springframework.scheduling.concurrent)
scheduleTask:326, BindingService (org.springframework.cloud.stream.binding)
rescheduleConsumerBinding:158, BindingService (org.springframework.cloud.stream.binding)
lambda$rescheduleConsumerBinding$0:164, BindingService (org.springframework.cloud.stream.binding)
run:54, DelegatingErrorHandlingRunnable (org.springframework.scheduling.support)
call:511, Executors$RunnableAdapter (java.util.concurrent)
run$$$capture:266, FutureTask (java.util.concurrent)
run:-1, FutureTask (java.util.concurrent)
 - Async stack trace
<init>:151, FutureTask (java.util.concurrent)
<init>:209, ScheduledThreadPoolExecutor$ScheduledFutureTask (java.util.concurrent)
schedule:532, ScheduledThreadPoolExecutor (java.util.concurrent)
schedule:325, ThreadPoolTaskScheduler (org.springframework.scheduling.concurrent)
scheduleTask:326, BindingService (org.springframework.cloud.stream.binding)
rescheduleConsumerBinding:158, BindingService (org.springframework.cloud.stream.binding)
doBindConsumer:146, BindingService (org.springframework.cloud.stream.binding)
bindConsumer:121, BindingService (org.springframework.cloud.stream.binding)
createAndBindInputs:234, BindableProxyFactory (org.springframework.cloud.stream.binding)
doStartWithBindable:54, InputBindingLifecycle (org.springframework.cloud.stream.binding)
forEach:608, LinkedHashMap$LinkedValues (java.util)
start:47, AbstractBindingLifecycle (org.springframework.cloud.stream.binding)
start:33, InputBindingLifecycle (org.springframework.cloud.stream.binding)
doStart:182, DefaultLifecycleProcessor (org.springframework.context.support)
access$200:53, DefaultLifecycleProcessor (org.springframework.context.support)
start:360, DefaultLifecycleProcessor$LifecycleGroup (org.springframework.context.support)
startBeans:158, DefaultLifecycleProcessor (org.springframework.context.support)
onRefresh:122, DefaultLifecycleProcessor (org.springframework.context.support)
finishRefresh:879, AbstractApplicationContext (org.springframework.context.support)
finishRefresh:161, ServletWebServerApplicationContext (org.springframework.boot.web.servlet.context)
refresh:549, AbstractApplicationContext (org.springframework.context.support)
refresh:140, ServletWebServerApplicationContext (org.springframework.boot.web.servlet.context)
refresh:775, SpringApplication (org.springframework.boot)
refreshContext:397, SpringApplication (org.springframework.boot)
run:316, SpringApplication (org.springframework.boot)
run:1260, SpringApplication (org.springframework.boot)
run:1248, SpringApplication (org.springframework.boot)
main:13, App (my.app)
invoke0:-2, NativeMethodAccessorImpl (sun.reflect)
invoke:62, NativeMethodAccessorImpl (sun.reflect)
invoke:43, DelegatingMethodAccessorImpl (sun.reflect)
invoke:498, Method (java.lang.reflect)
run:49, RestartLauncher (org.springframework.boot.devtools.restart)
```

**Comment by sobychacko** [comment]
@estenwig Can you be more specific as to where the boolean value for `allowAutoTopicCreation`  is set to `true`? It is not entirely clear where that happens. It doesn't seem like `KafkaConsumer` or `Fetcher` does that.

**Comment by garyrussell** [comment]
@sobychacko It's a `KafkaBinderConfigurationProperties` property.

It is used to prevent creating topics (and it does that), but this is error is when the binder is trying to determine the current partitions for the topic in `getPartitionInfo()`.

It looks like he doesn't have permissions for `KafkaConsumer. partitionsFor()`.

It looks like this is just for the health indicator; so maybe we could catch the exception in the binder?

**Comment by garyrussell** [comment]
No it is not; we don't attempt to create them if the boolean is false.

See here: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka-core/src/main/java/org/springframework/cloud/stream/binder/kafka/provisioning/KafkaTopicProvisioner.java#L293

**Comment by estenwig** [comment]
> No it is not; we don't attempt to create them if the boolean is false.
> 
> See here: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka-core/src/main/java/org/springframework/cloud/stream/binder/kafka/provisioning/KafkaTopicProvisioner.java#L293

This code is not called in this case. Rather https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka-core/src/main/java/org/springframework/cloud/stream/binder/kafka/provisioning/KafkaTopicProvisioner.java#L394 
It executes a callable provided i the input to KafkaTopicProvisioner.getPartitionsForTopic

From the stack here:
`partitionsFor:1774, KafkaConsumer (org.apache.kafka.clients.consumer)
partitionsFor:1742, KafkaConsumer (org.apache.kafka.clients.consumer)
lambda$getPartitionInfo$4:667, KafkaMessageChannelBinder (org.springframework.cloud.stream.binder.kafka)
call:-1, 1671184759 (org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder$$Lambda$751)
lambda$getPartitionsForTopic$2:394, KafkaTopicProvisioner (org.springframework.cloud.stream.binder.kafka.provisioning)
doWithRetry:-1, 881659641 (org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner$$Lambda$752)
doExecute:287, RetryTemplate (org.springframework.retry.support)
execute:164, RetryTemplate (org.springframework.retry.support)
getPartitionsForTopic:393, KafkaTopicProvisioner (org.springframework.cloud.stream.binder.kafka.provisioning)
getPartitionInfo:663, KafkaMessageChannelBinder (org.springframework.cloud.stream.binder.kafka)
`

In turn I arrive at partitionsFor:1774, KafkaConsumer (org.apache.kafka.clients.consumer) There you can see it does not take in to account the properties :)

**Comment by garyrussell** [comment]
>(org.springframework.cloud.stream.binder.kafka.provisioning) getPartitionInfo:663, KafkaMessageChannelBinder (org.springframework.cloud.stream.binder.kafka)

As I said, it is not part of provisioning, it is getting the partitions for the health indicator - this needs to be fixed. 

It is not clear, however, if you have describe permissions, that this operation is disallowed.

**Comment by estenwig** [comment]
Okay, I think i understand now :)
I have the permissions Read and Describe.

**Comment by sobychacko** [comment]
@estenwig While addressing the fix for this issue (adding log warning for the health check), we realized that it needs some more fixing in the way the binder treats listened partitions. Unfortunately, since we are already in an RC phase, we can't make this change at this point. Need to wait until a patch release. Created another [issue](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/512) for addressing the issues with listened partitions.

**Comment by sobychacko** [comment]
@estenwig [This PR ](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/514) added the warning statement for the health check. Closing this issue. Please re-open if you see further issues. Thank you!
