### ISSUE TITLE
Allow setting a message key for the Kafka binder

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-kafka#51]
_From @Jacuo on July 28, 2016 14:55_

Sending message to kafka topic, when cleanup.policy=compact causes error. It looks that problem is with key= null. I tried to set key using

```
MessageBuilder.withPayload(message)
                            .setHeader(KafkaHeaders.MESSAGE_KEY, key)
```

but with no effect.
Is there any way to set key value ?

_Copied from original issue: spring-cloud/spring-cloud-stream#602_

**Comment by sabbyanandan** [comment]
_From @mbogoevici on July 28, 2016 15:21_

Hi,

Thanks for pointing that out. We are currently mistakingly setting the key to null always, which is not working with compacted topics.

**Comment by sabbyanandan** [comment]
_From @Jacuo on August 17, 2016 7:57_

Is there any prediction, when it will be fixed ?

**Comment by sabbyanandan** [comment]
@Jacuo: Could you please upgrade to [Brooklyn.RELEASE](https://spring.io/blog/2016/09/23/spring-cloud-stream-brooklyn-release-is-available) and retry?

**Comment by ilayaperumalg** [comment]
Hi @Jacuo I am able to send/receive messages with key/value set with appropriate serializer/de-serializer configs. Please re-open this ticket if you still see any issue. Thanks!

**Comment by MinhTranQuang258** [comment]
Hi @ilayaperumalg,
Can you illustrate a sample serializer/de-serializer configuration ?
