### ISSUE TITLE
spring.application.name seems to always override the consumer group in 2.1.0.RC2

### ISSUE THREAD

**Issue by davidmelia** [spring-cloud/spring-cloud-stream-binder-kafka#517]
HI,

Creating a super simple eclipse spring stream kafka starter app with:

```
spring.application.name=kafka-issue
spring.cloud.stream.bindings.input.destination=input
spring.cloud.stream.bindings.input.group=mygroup
```

```
public interface Channels {

	String INPUT = "input";

	@Input(INPUT)
	KStream<String, String> newsIn();
}
```
```
@SpringBootApplication
@EnableBinding({ Channels.class })
public class KafkaIssueApplication {

	public static void main(String[] args) {
		SpringApplication.run(KafkaIssueApplication.class, args);
	}

	@StreamListener
	public void process(@Input(Channels.INPUT) final KStream<String, String> newsEventStream) {
		newsEventStream.foreach((key, value) -> System.out.println("KStream:" + key + "=" + value));
	}
}
```

Then with Spring Boot 2.1.1 and Spring Cloud Greenwich.RC1 you can see in the log that the group is ignored and spring.application.name seems to be used instead of spring.cloud.stream.bindings.input.group:

`o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=kafka-issue-8f4c156a-c0be-4a55-bdf2-2335209fb3a4-StreamThread-1-consumer, groupId=kafka-issue] Discovered group coordinator localhost:9092 (id: 2147483646 rack: null)`

However in the same project if you downgrade to Spring Boot 2.0.6 and Spring Cloud Finchley.SR2 you get the correct groupId of 'mygroup'

`2018-12-14 20:24:48.612  INFO 22833 --- [-StreamThread-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=mygroup-71aff101-0249-44d5-a485-6cd6536e9058-StreamThread-1-consumer, groupId=mygroup] Discovered group coordinator localhost:9092 (id: 2147483646 rack: null)`

Any ideas?

Thanks

**Comment by sobychacko** [comment]
@davidmelia Closing this issue. If you are still having issues, please re-open.
