### ISSUE TITLE
Lots of obsolete logging when perfoming health checks

### ISSUE THREAD

**Issue by wblancqu** [spring-cloud/spring-cloud-stream-binder-kafka#52]
We monitor our spring boot applications by accessing /health (every 30sec). A lot of logging occurs because of this. Looks like the health check for Kafka recreates a consumer every time causing to produce lots of logging like:

> 2016-09-28 14:44:01,963+0200 INFO [DiscoveryClient-InstanceInfoReplicator-0] config.AbstractConfig (AbstractConfig.java:178) - ConsumerConfig values: 
>   metric.reporters = []
>   metadata.max.age.ms = 300000
>   partition.assignment.strategy = [org.apache.kafka.clients.consumer.RangeAssignor]
>   reconnect.backoff.ms = 50
>   sasl.kerberos.ticket.renew.window.factor = 0.8
>   max.partition.fetch.bytes = 1048576
>   bootstrap.servers = [localhost:9092]
>   ssl.keystore.type = JKS
>   enable.auto.commit = true
>   sasl.mechanism = GSSAPI
>   interceptor.classes = null
>   exclude.internal.topics = true
>   ssl.truststore.password = null
>   client.id = consumer-51
>   ssl.endpoint.identification.algorithm = null
>   max.poll.records = 2147483647
>   check.crcs = true
>   request.timeout.ms = 40000
>   heartbeat.interval.ms = 3000
>   auto.commit.interval.ms = 5000
>   receive.buffer.bytes = 65536
>   ssl.truststore.type = JKS
>   ssl.truststore.location = null
>   ssl.keystore.password = null
>   fetch.min.bytes = 1
>   send.buffer.bytes = 131072
>   value.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
>   group.id = 
>   retry.backoff.ms = 100
>   sasl.kerberos.kinit.cmd = /usr/bin/kinit
>   sasl.kerberos.service.name = null
>   sasl.kerberos.ticket.renew.jitter = 0.05
>   ssl.trustmanager.algorithm = PKIX
>   ssl.key.password = null
>   fetch.max.wait.ms = 500
>   sasl.kerberos.min.time.before.relogin = 60000
>   connections.max.idle.ms = 540000
>   session.timeout.ms = 30000
>   metrics.num.samples = 2
>   key.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
>   ssl.protocol = TLS
>   ssl.provider = null
>   ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
>   ssl.keystore.location = null
>   ssl.cipher.suites = null
>   security.protocol = PLAINTEXT
>   ssl.keymanager.algorithm = SunX509
>   metrics.sample.window.ms = 30000
>   auto.offset.reset = latest

Maybe the health check should not log this? I see there's a boolean doLog available in the constructor of org.apache.kafka.common.config.AbstractConfig.

Kind regards

**Comment by mbogoevici** [comment]
Hi @wblancqu,

thanks for reporting this.

**Comment by ltalhouarne** [comment]
@wblancqu,

We are using the same strategy for health checking our applications. 

However, I don't believe the KafkaConsumer API allows for passing the aforementioned boolean that the `AbstractConfig` utilizes. 

In the meantime, we've decided to change the logging level for the `ConsumerConfig` as well as the `ProducerConfig` to `ERROR`. We lose the initial logging on boot up but our logs don't get clustered for each health check.

```
logging.level.org.apache.kafka.clients.consumer.ConsumerConfig=ERROR      
logging.level.org.apache.kafka.clients.producer.ProducerConfig=ERROR
```

**Comment by wblancqu** [comment]
Hi @ltalhouarne,

Thanks for your reply. We did indeed the same trick:

Configuration:
  packages: "org.whatever"
  Appenders:
    Console:
      name: console
      target: SYSTEM_OUT
      ThresholdFilter:
        level: debug
        onMatch: ALLOW
      PatternLayout:
        pattern: '%d [%p] [%t] [%c{1.}] (%F:%L) %m%n'
  Loggers:
    # Avoid superfluous logging due to health checks
    Logger:
      - name: org.apache.kafka
        additivity: false
        level: warn
        AppenderRef:
          - ref: console
      - name: kafka
        additivity: false
        level: warn
        AppenderRef:
          - ref: console
      - name: org.springframework.cloud.config.client
        additivity: false
        level: warn
        AppenderRef:
          - ref: console
    Root:
      level: info
      AppenderRef:
        - ref: console

**Comment by elnur** [comment]
I'm at `1.2.0.RELEASE` and still seeing all this excessive logging.

**Comment by laur89** [comment]
If you still want the `ConsumerConfig` to how up in logs upon startup, you could decrease log level just after kafka binder is started: https://gist.github.com/laur89/bef122a936996d83554353e0601916ae
