### ISSUE TITLE
Multiple error loggers installed by default

### ISSUE THREAD

**Issue by Walliee** [spring-cloud/spring-cloud-stream-binder-kafka#528]
Currently, if an exception is thrown from a message handler (streaming consumer) while processing an inbound message, the error is logged by two logging handlers.

1.  `org.springframework.integration.handler.LoggingHandler` -  installed by `DefaultConfiguringBeanFactoryPostProcessor` on the default error channel (`errorChannel`) 
2. `org.springframework.kafka.listener.LoggingErrorHandler` - installed by default on `ConcurrentMessageListenerContainer` 

This causes each exception to be logged twice. While there is a way to prevent `LoggingHandler` from being registered, I actually like it over `LoggingErrorHandler` but there is no way to disable it. 

Should `LoggingErrorHandler` be disabled by default or should there at least exist a way to disable it?

**Comment by garyrussell** [comment]
If you define your own `errorChannel` bean (`PublishSubscribeChannel`), the default logging handler won't be subscribed to it.

**Comment by Walliee** [comment]
Yes, I saw that but I’d like to keep that one.

There is no way to remove org.springframework.kafka.listener.LoggingErrorHandler right now.

**Comment by Walliee** [comment]
Actually, going through the 2.1.0 release notes, I realized that I should be able to customize the `ConcurrentMessageListenerContainer` providing a `ListenerContainerCustomizer` bean. 

Let me try it out.

**Comment by Walliee** [comment]
I was able to install a no-op error handler on `ConcurrentMessageListenerContainer` using `ListenerContainerCustomizer`. Closing this issue.
