### ISSUE TITLE
Investigate the difference in InteractiveQueryService.WindowStore between v2.0 and v2.1 releases

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-kafka#532]
As a user, while querying from the WindowStore, I see a difference in the results between 2.0 vs. 2.1 Kafka Streams binder.

In 2.0, I'm used to getting the windowed aggregate grouped nicely for all the available unique buckets in the `WindowStore`. 

![image](https://user-images.githubusercontent.com/1562654/51405391-11e01880-1b0b-11e9-8fd7-6d64f93da6ef.png)

In 2.1 however, I see the results duplicated and spread throughout the window. They don't group for the available buckets as noticed in the previous release.

![image](https://user-images.githubusercontent.com/1562654/51405442-33d99b00-1b0b-11e9-896f-4c9b5e990674.png)

The [code](https://github.com/sabbyanandan/eda/blob/master/userconsumer/src/main/java/com/example/consumer/Application.java) remains the same in both the versions except the renaming of the service from `QueryableStoreRegistry` to `InteractiveQueryService`.

**Comment by sobychacko** [comment]
In the newer version of Kafka Streams, the order of the data that is fetched from the window store seems to be different from what it was before in the previous versions. [This call](https://github.com/sabbyanandan/eda/blob/master/userconsumer/src/main/java/com/example/consumer/Application.java#L74) now puts the same keys from the different windows one after the other as below
```
[{"region":"US-CA","count":20,"start":1548187320000,"end":1548187350000},{"region":"US-CA","count":37,"start":1548187350000,"end":1548187380000},{"region":"US-CA","count":14,"start":1548187380000,"end":1548187410000},{"region":"US-CA","count":5,"start":1548187410000,"end":1548187440000},{"region":"US-HI","count":6,"start":1548187320000,"end":1548187350000},{"region":"US-HI","count":5,"start":1548187350000,"end":1548187380000},{"region":"US-HI","count":2,"start":1548187410000,"end":1548187440000},{"region":"US-IL","count":22,"start":1548187320000,"end":1548187350000},{"region":"US-IL","count":17,"start":1548187350000,"end":1548187380000},{"region":"US-IL","count":10,"start":1548187380000,"end":1548187410000},{"region":"US-IL","count":2,"start":1548187410000,"end":1548187440000},{"region":"US-NY","count":21,"start":1548187320000,"end":1548187350000},{"region":"US-NY","count":14,"start":1548187350000,"end":1548187380000},{"region":"US-NY","count":7,"start":1548187380000,"end":1548187410000},{"region":"US-NY","count":5,"start":1548187410000,"end":1548187440000},{"region":"US-PA","count":5,"start":1548187320000,"end":1548187350000},{"region":"US-PA","count":5,"start":1548187350000,"end":1548187380000},{"region":"US-PA","count":3,"start":1548187380000,"end":1548187410000},{"region":"US-PA","count":1,"start":1548187410000,"end":1548187440000}]
```

. This is why the UI seems to be off a little bit. In order to restore the previous behavior, we need to sort the windows by the start time so that multiple windows with the same start time (and different keys) appear in the same order as it was before. 

Use something like the following before returning from the method:
`usersByRegionCounts.sort(Comparator.comparingLong(o -> o.start));`

This will force the ordering as before. 
```
[{"region":"US-CA","count":19,"start":1548186960000,"end":1548186990000},{"region":"US-HI","count":4,"start":1548186960000,"end":1548186990000},{"region":"US-IL","count":6,"start":1548186960000,"end":1548186990000},{"region":"US-NY","count":8,"start":1548186960000,"end":1548186990000},{"region":"US-PA","count":1,"start":1548186960000,"end":1548186990000},{"region":"US-CA","count":27,"start":1548186990000,"end":1548187020000},{"region":"US-HI","count":2,"start":1548186990000,"end":1548187020000},{"region":"US-IL","count":15,"start":1548186990000,"end":1548187020000},{"region":"US-NY","count":24,"start":1548186990000,"end":1548187020000},{"region":"US-PA","count":4,"start":1548186990000,"end":1548187020000},{"region":"US-CA","count":2,"start":1548187020000,"end":1548187050000},{"region":"US-NY","count":2,"start":1548187020000,"end":1548187050000}]
```
