### ISSUE TITLE
Kafka binder seems to ignore group property.

### ISSUE THREAD

**Issue by pociot** [spring-cloud/spring-cloud-stream-binder-kafka#533]
Hi,

There seems to be problem with Kafka binder in version 2.1.0.RC4, but also in RELEASE I believe. In older versions when I was setting group property on binding it was populated to Kafka properties as well so I could have multiple input bindings. Now binder seems to ignore it and sets group.id as spring.application.name. I created a repo to visualise the issue.

https://github.com/pociot/spring-cloud-stream-demo/tree/group-name-issue

I look forward hearing from you!
Kamil Pociot

**Comment by olegz** [comment]
@sobychacko this is a potential regression. Can you please take a look?

**Comment by sobychacko** [comment]
@pociot We revamped the way `application.id` is propagated in 2.1.0.  Earlier, it was working through the group property, however, the proper way to address that in Kafka Streams is by using the application id. You can set the applicaion id in two ways.
 1. By setting at the binder level. This is a global strategy and only works if you only have one StreamListener. You set this using `spring.cloud.stream.kafka.streams.binder.applicationId`.
2. By setting at per binding. This should be used if you have multiple StreamListener methods. You need to set the property `spring.cloud.stream.kafka.streams.bindings.<binding-name>.consumer.applicationId`.

The binder will fall back to `spring.application.name` if neither of the above properties are found in the application.

**Comment by pociot** [comment]
I see. Thanks a lot for clarification.

**Comment by sobychacko** [comment]
@pociot Feel free to close this issue if you are clear on how to proceed.
