### ISSUE TITLE
Documentation Error about Kafka Binder Properties

### ISSUE THREAD

**Issue by HassankSalim** [spring-cloud/spring-cloud-stream-binder-kafka#534]
First part of the [Readme](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka#configuration-options) and [Docs](https://cloud.spring.io/spring-cloud-static/spring-cloud-stream-binder-kafka/2.1.0.RC3/single/spring-cloud-stream-binder-kafka.html#_configuration_options) the prefix **spring.cloud.stream.kafka.binder** should be 
**spring.cloud.stream.kafka.streams.binder**

**Comment by HassankSalim** [comment]
If this is an issue can i provide a fix.

**Comment by olegz** [comment]
Please do. Any contributions are welcomed!

**Comment by HassankSalim** [comment]
I have made changes to README.md [Pull request](https://github.com/HassankSalim/spring-cloud-stream-binder-kafka/pull/1). Please review

**Comment by sobychacko** [comment]
@HassankSalim there are two binders, one is the `MessageChannel` based Kafka binder and the Kafka Streams binder. For the former, we need the `spring.cloud.stream.kafka.binder` and the latter requires `spring.cloud.stream.kafka.streams.binder`. I wonder if you are mixing the two.

**Comment by HassankSalim** [comment]
Sorry @sobychacko it was my fault, as a beginner writing a stream job, it was difficult to config the brokers.
Thanks for clearing it up
