### ISSUE TITLE
KTable as input binding doesn't work if @input is not specified at parameter level

### ISSUE THREAD

**Issue by tambre** [spring-cloud/spring-cloud-stream-binder-kafka#536]
For KStream we can specify binding as

@StreamListener("input")
public void process (KStream inputStream)

However, this doesnt work for KTable. Throws Illegal Argument Exception "Method must be declarative". I had to explicitly specify as follows to make the binding work.

@StreamListener
public void process(@input("input") KTable inputTable)

is this expected behavior?

Code I am attempting is something like this:

**This is working fine:**
`
@EnableBinding(TradeMsgReaderTopics.class)
public class TradeMsgReaderProcessor
{
private static final Logger logger = LoggerFactory.getLogger(TradeMsgReaderProcessor.class);

@StreamListener
public void process(@Input(TradeMsgReaderTopics.INPUT) KTable<String, TradeMessageEvent> inputTable)
{
    inputTable.toStream().foreach((key, value) -> logger.debug("key: {} :: value: {}", key, value));
}
}`

**This is not working:**

`@EnableBinding(TradeMsgReaderTopics.class)
public class TradeMsgReaderProcessor
{
private static final Logger logger = LoggerFactory.getLogger(TradeMsgReaderProcessor.class);

@StreamListener(TradeMsgReaderTopics.INPUT)
public void process(KTable<String, TradeMessageEvent> inputTable)
{
    inputTable.toStream().foreach((key, value) -> logger.debug("key: {} :: value: {}", key, value));
}
}`

**The binding interface is:**

`@configuration
public interface TradeMsgReaderTopics
{
String INPUT = "tradeMsgEventStore";

@Input("tradeMsgEventStore")
KTable<String, TradeMessageEvent> tradeMsgEventStore();
}`

**Comment by sobychacko** [comment]
@tambre The fix for this issue is pushed to master and backported to 2.1.x.
