### ISSUE TITLE
Actuator health for Kafka Streams binder

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream-binder-kafka#544]
Provide support for actuator health endpoints in the Kafka Streams binder.

**Comment by kavukcutolga** [comment]
Hi @sobychacko 

I see that you have added support for KafkaStream binder HealthCheck. I am facing an issue related to that. When create a binding with KStream binder and if there is no other bindings for kafkaBinder KafkaBinderHealthIndicator returns status as Unhealth beacuse it assumes that there should be at least 1 binding. With only KStream binder implementations,is this commit reolves this issue as well? https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/d80e66d9b8466607c40ec009108f592901358507

Cheers

**Comment by sobychacko** [comment]
@kavukcutolga Do you use both binders? If you have both binders (regular kafka binder and the kafka streams binder) then you are required to use them in your application if health check needs to work properly. We had a similar situation the other day. See [this issue](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/552). If you don't need the regular kafka binder in the application, you might want to remove that as a dependency. On the other hand, if you need it, you probably want to provide a binding through this binder.
