### ISSUE TITLE
Support wiring in a custom (or non-default) ErrorHandler

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream-binder-kafka#545]
See https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/542

Something lile `@KafkaConsumerErrorHandler` meta-annotated with `@Bean`.

**Comment by bono007** [comment]
@garyrussell is this covered by https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/53d32c2332983679eca0699f77468a76461c20fd (sans the convenience of the annotation) ?

**Comment by garyrussell** [comment]
Yes; indeed it is.
