### ISSUE TITLE
Is it possible to use multiple stream processor?

### ISSUE THREAD

**Issue by mseMB** [spring-cloud/spring-cloud-stream-binder-kafka#548]
I have following Binder Configuration:
```
@Input("Input1")
  KStream<Object, TeamEvent> TeamKstreamIn();

@Input("Input2")
  KStream<Object, TestEvent> TestKstreamIn();
```

Then i want to use this two bindings in two different interactive queries

```
@StreamListener("Input1")
  public void process (KStream<Object, TeamEvent> input) {
 input
  .map(...)
  .groupByKey()
  .aggregate(
    TeamEvent::new,
    (s, TeamEvent, vr) -> {
      return vr;
    },
    Materialized.<String, TeamEvent, KeyValueStore<Bytes, byte[]>>as(STORE_NAME).withKeySerde(Serdes.String()).
      withValueSerde(Serdes.String())
  );
}
```

```
@StreamListener("Input2")
  public void process (KStream<Object, TestEvent> input) {
input
  .map(...)
  .groupByKey()
  .aggregate(
    TestEvent::new,
    (s, TestEvent, vr) -> {
      return vr;
    },
    Materialized.<String, TestEvent, KeyValueStore<Bytes, byte[]>>as(STORE_NAME).withKeySerde(Serdes.String()).
      withValueSerde(Serdes.String())
  );
}
```
Is that possible, because os get following error:
`Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.support.BeanDefinitionOverrideException: 
Invalid bean definition with name 'stream-builder-process' defined in null: 
Cannot register bean definition [Generic bean: class [org.springframework.kafka.config.StreamsBuilderFactoryBean]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] for bean 'stream-builder-process': 
There is already [Generic bean: class [org.springframework.kafka.config.StreamsBuilderFactoryBean]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] bound.`

**Comment by sobychacko** [comment]
@mseMB It is possible to do so. See this recent [SO discussion](https://stackoverflow.com/questions/54522918/multiple-enablebinding-with-kafka-spring-cloud-stream/54524930).

**Comment by mseMB** [comment]
@sobychacko Thank you. I have now a working example.
For people that have the same issue like me, you must name the methods of the @StreamListener Annotation differently, in my example i named them both **process**, after renaming them the application started. The underlying KafkaStreams object name consists of this method name.
 I also added for every stream binding an application-id.
