### ISSUE TITLE
KafkaStreamsStateStore annotation when using multiple consumer binders

### ISSUE THREAD

**Issue by razorcd** [spring-cloud/spring-cloud-stream-binder-kafka#551]
@KafkaStreamsStateStore is creating a "state store" for each consumer input.

Example:
```
@StreamListener
		@SendTo("output")
		@KafkaStreamsStateStore(name="statestore1", type= KafkaStreamsStateStoreProperties.StoreType.KEYVALUE)
		public KStream<String, String> process(@Input("input11") KStream<String, String> input1,
                                                       @Input("input22") KStream<String, String> input2) {
    ...
}
```
When using multiple consumers it tries to create a "state store" for each input consumer and fail with:

```
Caused by: org.apache.kafka.streams.errors.TopologyException: Invalid topology: StateStore statestore1 is already added.
```

Sourcecode: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/02e1fec3b4520125e2f4c6d8d3e79a9c87d1744b/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/KafkaStreamsStreamListenerSetupMethodOrchestrator.java#L463

**Comment by razorcd** [comment]
also it is worth to consider allowing multiple StateStores per annotation "@KafkaStreamsStateStore"

**Comment by sobychacko** [comment]
@razorcd We put a fix for this error in the binder. It is on 2.2.0 snapshot and backported to 2.1.x as well. The release for the binder next week (2.1.3.RELEASE) will have this fix.
As to your second request for allowing multiple state stores per annotation, can you create a separate issue for that if you don't mind?

**Comment by razorcd** [comment]
Thank you for adding this change!
I have opened another issue for having multiple Stores per annotation: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/556
