### ISSUE TITLE
KafkaBinderHealthIndicator with KafkaMessageChannelBinder when only KStream Binder

### ISSUE THREAD

**Issue by kavukcutolga** [spring-cloud/spring-cloud-stream-binder-kafka#554]
Hi,

When using KStream Binder with spring-cloud-stream, somehow KafkaMessageChannelBinder and KafkaBinderHealthIndicator also initialized. Because of that KafkaBinderHealthIndicator returns DOWN, it expects at least 1 binding to return UP status see:

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/b4a2950acd88df0f96178ca7ea2ba31e9cff43da/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderHealthIndicator.java#L112

Also new Health Indicator for Kstream binder recently added. https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/544

I think KafkaMessageChannelBinder  and KafkaBinderHealthIndicator  should not be initiated at all if there is only KStream binding inside context. Is this a bug or config issue.

**Comment by sobychacko** [comment]
@kavukcutolga I moved this issue from core Spring Cloud Stream over here. We have the 
`KafkaStreamsBinderHelthIndicator` on the master branch and thus on the latest snapshot. As to the problems that you are running into, see the comments I added [here](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/544#issuecomment-468823500). Basically, why do you add the regular Kafka binder (`spring-cloud-stream-bindef-kafka`) as a dependency of your application unless you are planning to use it in the application? If you are intending to use it, then I suggest add some bindings for it using the `EnableBinding` and the health check should work.

**Comment by kavukcutolga** [comment]
@sobychacko does makes sense to me, I will see whats will the output

**Comment by sobychacko** [comment]
@kavukcutolga Closing this issue. Please feel free to re-open it, if you are still experiencing issues with this.
