### ISSUE TITLE
KafkaStreamsStateStore annotation when using multiple Stores per consumer binder

### ISSUE THREAD

**Issue by razorcd** [spring-cloud/spring-cloud-stream-binder-kafka#556]
@KafkaStreamsStateStore is limited to creating only one `state store` for each consumer input:
example:
```
@StreamListener("input")
@SendTo("output")
@KafkaStreamsStateStore(name="statestore", type=KafkaStreamsStateStoreProperties.StoreType.KEYVALUE)
public KStream<String, String> process(KStream<String, String> input) {
    ...
}
```

Adding multiple `state stores`, each with it's own configuration would be very useful.

**Comment by razorcd** [comment]
A not so clean workaround would be:

```

**Comment by sobychacko** [comment]
@razorcd Another approcah you can do is to use the `StreamsBuilderFactoryBeanCustomizer` from Spring for Apache Kafka 2.3. See [here](https://docs.spring.io/spring-kafka/docs/2.3.0.BUILD-SNAPSHOT/reference/html/#streams-config). That way, you can provide a bean with the customizations and it gets automatically picked up. Keep in mind that, we haven't updated the binder to the 2.3 snapshot of Spring Kafka yet, but will do so soon. Anyways, this is a strategy that you can use. 

We can do something like the following on the annotation.
```
@KafkaStreamsStateStore({name="statestore-1", type=KafkaStreamsStateStoreProperties.StoreType.KEYVALUE},
{name="statestore-2", type=KafkaStreamsStateStoreProperties.StoreType.KEYVALUE}
)
````
However, I am afraid that this could potentially become messy and not readble. Generally, we are trying to reduce the number of annotations that the binder has to maintain. `KafkaStreamsStateStore` annotation will not be deprecated, but will be maintained for simpler use cases (i.e - single state store) and anything beyond that as your use case requires, use this customizer approach starting with the new versions of the binder. What do you think?

**Comment by razorcd** [comment]
Thank you for the suggestion.

Yes, having an array of stateStores for @KafkaStreamsStateStore is great idea. But I agree that using the 
 `StreamsBuilderFactoryBeanCustomizer` for specific cases is also practical. So let's keep it simple and not add multiple stores to the annotation way.

I will try the new approach once it's released.

**Comment by sobychacko** [comment]
@razorcd Here is a similar [issue](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/627). Please find the [suggested solution](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/627#issuecomment-481061587) provided there. If that workaround helps in your situation, please feel free to close this issue.
