### ISSUE TITLE
Spring Cloud Stream + Kafka application fails to start when spring.cloud.stream.kafka.binder.required-acks is set to 'all'

### ISSUE THREAD

**Issue by Walliee** [spring-cloud/spring-cloud-stream-binder-kafka#558]
The `spring.cloud.stream.kafka.binder.required-acks` property in the `KafkaBinderConfigurationProperties` is impacted by an [issue](https://github.com/spring-projects/spring-boot/issues/16206) in Spring Boot's Binder.

The `acks` property in Kafka producer properties allows for value to be 'all' and to support that `KafkaBinderConfigurationProperties` has the requiredAcks field is of type `String` but along with the regular `String` setter, there is a setter with `int` parameter as well.

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/02e1fec3b4520125e2f4c6d8d3e79a9c87d1744b/spring-cloud-stream-binder-kafka-core/src/main/java/org/springframework/cloud/stream/binder/kafka/properties/KafkaBinderConfigurationProperties.java#L376-L382

This confuses the Boot Binder and the application fails to start up.
Interestingly, it doesn't happen every single time.

I think the setter with the `int` param is not being used anywhere and can be safely removed?

**Comment by garyrussell** [comment]
Looks like a bug to me https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/0a59b4c6287234d5f9608fe8d11aa01875e04753

**Comment by Walliee** [comment]
Apologies, I closed this accidentally.
