### ISSUE TITLE
Reuse  Kafka consumer in KafkaBinderMetrics

### ISSUE THREAD

**Issue by iNikem** [spring-cloud/spring-cloud-stream-binder-kafka#560]
This issue is similar to https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/231 only in `KafkaBinderMetrics`. Currently it creates new Kafka consumer every time actuator metrics are accessed. E.g. in our case of Prometheus scraping metrics from Boot application - every 10 seconds. Please consider reusing single Kafka consumer for this.

**Comment by garyrussell** [comment]
What version are you using? The class has used a [shared consumer since 2.0](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/3450b4b3600b8ec8d8e406a90b1704180177072b).

**Comment by iNikem** [comment]
2.0.0.RELEASE

**Comment by iNikem** [comment]
Judging by dates, the earliest version where this could be fixed, is 2.0.1.RELEASE :)

**Comment by garyrussell** [comment]
Yeah, for some reason the tag doesn't show in the commit. Sorry.

However, it's generally a good idea to keep up-to-date on versions.

**Comment by iNikem** [comment]
I will certainly update the version now, that I know this is already fixed :)
