### ISSUE TITLE
Add the ability to configure the DLQ producer properties

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream-binder-kafka#58]
Identify what properties we want the users to set and propagate over to the DLQ configuraiton. (eg., we don't want to set serde)

**Comment by ilayaperumalg** [comment]
Currently, the DLQ uses the default producer properties [here](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java#L287) and it would be better we provide support for all the Kafka producer properties for producing into DLQ topic rather than choosing specific properties.

**Comment by aldex32** [comment]
Hi guys, any update about this issue? It's very important for people who are using `Confluent` serializer/deserializer.

Thanks in advance,
Aldo

**Comment by sobychacko** [comment]
@aldex32 I want to understand your use case a bit further. We are definitely adding the way to configure dlq producer. However, I have one question about the usage of serde on dlq. The data that you are receiving on `dlq` is whats already coming from Kafka `ConsumerRecord` which is the `byte[]` representation. So, lets say that you used `nativeEncoding` on your producer, which means that Kafka used a serializer to serialize the data you provided. Then on the receiving side, some error happened, and the data is sent to `dlq`. This data is the same `byte[]` representation of what was originally encoded by the serializer natively in Kafka. Why do you want to re-serialize that same information? Or does it mean that you want to use a different `Serializer` at that point for `dlq`? Can you please clarify? Thanks!

**Comment by garyrussell** [comment]
@sobychacko When using native (de)serialization, the inbound payload is not `byte[]`, it's whatever the deserializer created (probably a POJO). So, we need to be able to re-serialize that POJO back to a `byte[]` for kafka; hence the need to specify a value (and possibly key) serializer.
