### ISSUE TITLE
Kafka streams binder - multiple input bindings and Json Serde

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream-binder-kafka#634]
When multiple input bindings are used on a Kafka Streams application and each of those inputs is a different type, then there doesn't seem to have a simple way to use [JsonSerde](https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/support/serializer/JsonSerde.java) from Spring for Apache Kafka project. Applications have to explicilty provide separate configuration for each of the inputs. It will be nicer, if the binder can provide a better mechanism to avoid this boilerplate. For more information, see this [gitter chat](https://gitter.im/spring-cloud/spring-cloud-stream?at=5caced93016a930a458fd68b) and the conversation that follows.

**Comment by johnnywiller** [comment]
One way of avoid boilerplate Serdes classes, is using StringSerdes and converting back to POJO inside the stream processing. But I think this isn't a good idea mainly because isn't idiomatic, and also two serializations are necessary.

```
 void ingestFoo(KStream<String, String> fooStream) {
    input.mapValues(value -> {
        try {
            return mapper.readValue(value, Foo.class);
        } catch (IOException e) {
            return null;
        }
    })
    .// do whatever
 }
```

**Comment by garyrussell** [comment]
`ByteArraySerde` is more efficient since it avoids the intermediate `byte[]/String` conversion. `ObjectMapper` can read a `byte[]`.

**Comment by garyrussell** [comment]
See [4.1.6. Serialization, Deserialization, and Message Conversion](https://docs.spring.io/spring-kafka/reference/html/#serdes).

The serde can use information in record headers to determine the target type for payload conversion.

**Comment by sobychacko** [comment]
@johnnywiller On the latest snapshot on master (for 3.0.0), we introduced many improvements on how `Serde`s are inferred by the binder. First of all, for Kafka Streams binder, deserialization and serialization are going to be done natively using the `Serde`s provided by Kafka Streams. If it can't infer any such `Serde` types, then it will fall back to the `JsonSerde` provided by Spring Kafka. Since, in your case, you have a processor with multiple inputs and they are of different value types, it will be transparently inferred to `JsonSerde` by the binder. For. e.g. imagine, you have the following,

``` 
@StreamListener
public void process(@Input("input1") KStream<Object, Value1> stream1, 
@Input("input2") KStream<Object, Value2> stream2)
```
Then you don't need to do anything in configuration since they will be automatically mapped to `JsonSerde`.

**Comment by sobychacko** [comment]
@johnnywiller Closing this issue. Please feel free to re-open if you find issues.
