### ISSUE TITLE
REST API for spring cloud stream consumer of Kafka Topic

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-kafka#64]
_From @vsrahul82 on July 14, 2016 19:44_

The consumer example in documentation polls the Kafka topic and returns  instantly when a message arrives on the topic. If i wanted the message to be read from queue only when i invoke the consume method, kind of like provide a REST API that will return a message from Kafka topic  when invoked how can i do that?  Please provide code example.

_Copied from original issue: spring-cloud/spring-cloud-stream#591_

**Comment by sabbyanandan** [comment]
_From @mbogoevici on July 14, 2016 21:25_

Spring Cloud Stream is currently entirely message-driven. We do not currently support pollable bindings. Can you describe your use case and we could perhaps introduce a new feature.

**Comment by sabbyanandan** [comment]
@vsrahul82: Thoughts?

**Comment by mbogoevici** [comment]
Closing for now. @vsrahul82 - please get back to us if you have an update on this.
