### ISSUE TITLE
Could not intercept message  in ChannelInterceptor while using Kstream Type

### ISSUE THREAD

**Issue by desertTown** [spring-cloud/spring-cloud-stream-binder-kafka#654]
hi
I got a problem when I want to intercept the message using ChannelInterceptor 
It work while I use SubscribableChannel type as input channel

`    @Input(MESSAGE_EVENTS_IN)`
`    SubscribableChannel input();`

but if I use KStream as input channel and I cannot  intercept the message in ChannelInterceptor's preSend method. It seems ChannelInterceptor  cannot intercept message type of KStream.

`@Input(MESSAGE_EVENTS_IN)`
`    KStream<?, ?> input();`

is there any suggestion to intercept the KStream message and add some common header?

Thanks

**Comment by sabbyanandan** [comment]
Duplcates https://github.com/spring-cloud/spring-cloud-stream/issues/1704
