### ISSUE TITLE
Allow InteractiveQueryService used in external applications

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream-binder-kafka#656]
Currently, you can only use `InteractiveQueryService` within the same `SCSt` Kafka Streams application. It should be able to access as a regular RPC application from external applications.

Request on SO: https://stackoverflow.com/questions/56073231/queryablestoreregistry-is-used-to-query-state-store-in-spring-cloud-stream-i-am

**Comment by sabbyanandan** [comment]
Issue moved to [spring-cloud/spring-cloud-stream-samples #148](https://github.com/spring-cloud/spring-cloud-stream-samples/issues/148) via [**ZenHub**](https://www.zenhub.com/)
