### ISSUE TITLE
stream-binder-kafka 1.3.2 can not get Acknowledgment

### ISSUE THREAD

**Issue by wangqingfan** [spring-cloud/spring-cloud-stream-binder-kafka#662]
I'm in the configuration center, configured autoCommitOffset: false,This Acknowledgment is null, however

**Comment by sobychacko** [comment]
@wangqingfan 1.3.2 is an old release. Can you upgrade to the latest GA release and see if that resolves the issue? `2.2.1` is the latest GA release. If you are still having issues, please re-open this issue or create a new one.
