### ISSUE TITLE
Sleuth trace not working when using native way

### ISSUE THREAD

**Issue by t0il3ts0ap** [spring-cloud/spring-cloud-stream-binder-kafka#667]
I have a stream processor written using native kstream 
```
@Slf4j
@EnableBinding(KafkaStreamsProcessor.class)
@RequiredArgsConstructor
@Component
public class SomeWorker extends BaseStream<SomePojo> {

    @StreamListener(Sink.INPUT)
    @SendTo(Source.OUTPUT)
    public KStream<?, SomePojo> process(KStream<?, SomePojo> pojoObj) {
                     //stream processing
}
```

pom.xml 
` <spring-cloud.version>Greenwich.SR1</spring-cloud.version>`
```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-sleuth</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-binder-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-binder-kafka-streams</artifactId>
        </dependency>
```

properties
```
#kafka stream properties
spring.cloud.stream.kafka.binder.brokers=localhost
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms=1000
spring.cloud.stream.kafka.streams.binder.configuration.default.key.serde=org.springframework.kafka.support.serializer.JsonSerde
spring.cloud.stream.kafka.streams.binder.configuration.default.value.serde=org.springframework.kafka.support.serializer.JsonSerde
spring.cloud.stream.bindings.input.contentType=application/json
spring.cloud.stream.bindings.output.contentType=application/json
spring.cloud.stream.kafka.streams.bindings.input.consumer.application-id=dedup-metric-worker
spring.cloud.stream.bindings.input.destination=split-metrics3
spring.cloud.stream.bindings.output.destination=cleaned-metrics9

```

Sleuth trace keys in MDC(`X-B3-TraceId, X-B3-SpanId`) are missing when logging. 

Do I have to use non-native for it to work ? And in readme, I dont see simultaneous producing feature of kafka stream with it.
```
 @StreamListener(Sink.INPUT)
 public void process(Message<?> message) {
```

**Comment by garyrussell** [comment]
What version of the binder?
What version is the Kafka broker?

Show your stream config (.yml or .properties)

**Comment by t0il3ts0ap** [comment]
I have updated the original post. Using `Greenwich.SR1` for `org.spring.cloud` and latest dependencies for everything else.

**Comment by garyrussell** [comment]
I suggest you turn on DEBUG logging for `org.springframework` and look at the messages as they flow through the application.

**Comment by t0il3ts0ap** [comment]
I tested with non-native approach
```
    @StreamListener(Sink.INPUT)
//    @SendTo(Source.OUTPUT)
    public void  process(Message<HealthMetric> healthMetricStream) {
        log.info(healthMetricStream.getHeaders().toString());
        log.info(healthMetricStream.getPayload().toString());
    }
```
@garyrussell I was able to see trace-ids in log using the above format. The issue is only with native-approach when using `KStream`. 
I will debug more and update here, if I find something. 
Please let me know, if there is any known issues with native approach & passing of headers.

**Comment by garyrussell** [comment]
The streams binder has no hooks into messaging and does not manipulate headers. I don't believe sleuth supports Kafka Streams (but I could be wrong).

Header support for KStreams is limited; you have to add your own processor(s) to the stream topology to add headers.

**Comment by t0il3ts0ap** [comment]
You are right, the header support is limited for KStream. I have raised a request over sleuth board to ask if kstream is supported.

But it raises another question. If non native approach doesn't support sending data(`@sendTo`) to a topic like native streams, Isnt it just a normal kafka consumer? 
There is no statestore, ktable either. I wonder what it adds over a regular kafka consumer.

**Comment by garyrussell** [comment]
I don't know what you mean by "native" in this context but, yes, if you are not using any advanced stream features, you can just use the message channel kafka-binder.

**Comment by t0il3ts0ap** [comment]
Putting [sleuth ticket](https://github.com/spring-cloud/spring-cloud-sleuth/issues/1363) here for reference. Please close if necessary.
