### ISSUE TITLE
[Feature request] Programatically set DLQ topic name

### ISSUE THREAD

**Issue by boonware** [spring-cloud/spring-cloud-stream-binder-kafka#673]
I have enabled the DLQ mechanism and would like to configure the destination/topic name automatically based on the input topic name. For example, my properties file contains the following:

```
spring.cloud.stream.bindings.input.destination=inputTopic
spring.cloud.stream.bindings.input.group=inputGroup
spring.cloud.stream.kafka.bindings.input.consumer.enableDlq=true
```

With the above configuration, I wish to automatically set the topic for the DLQ based on the input topic name, for example `inputTopicDlq`. As far as I can see, this capability is not supported.

**Comment by garyrussell** [comment]
You can specify `dlqName`; if not,  it's named `error.inputTopic.inputGroup`.

This works

    spring.cloud.stream.kafka.bindings.input.consumer.dlq-name=${spring.cloud.stream.bindings.input.destination}Dlq

Or, are you saying you want some kind of mechanism to generate the name, such as a binder property

    spring.cloud.stream.kafka.binder.dlq-pattern=#{destination}Dlq

?

**Comment by boonware** [comment]
The first example suits my needs perfectly. I didn't realize it was possible to reference other configuration values this way in the file; you learn something new every day! Thanks for the help :)
