### ISSUE TITLE
KafkaStreamsStateStore not working when the store value is an Avro SpecificRecord

### ISSUE THREAD

**Issue by codependent** [spring-cloud/spring-cloud-stream-binder-kafka#676]
The context for this issue can be gotten at this SO question, and was discussed with @sobychacko: https://stackoverflow.com/questions/56634598/kafkastreamsstatestore-not-working-when-the-store-value-is-an-avro-specificrecor

When dealing with Avro messages in KStream applications, Spring Cloud Stream doesn't rely on its own SerDes, but requires using the ones provided by confluent, e.g:

```
    @StreamListener
    @SendTo("output")
    fun process(@Input("input") input: KStream<Int, Customer>, @Input("order") orderEvent: KStream<Int, GenericRecord>): KStream<Int, OrderShippedEvent> {

        val serdeConfig = mapOf(
                AbstractKafkaAvroSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG to "http://localhost:8081")

        val intSerde = Serdes.IntegerSerde()
        val customerSerde = SpecificAvroSerde<Customer>()
        customerSerde.configure(serdeConfig, false)
        val orderCreatedSerde = SpecificAvroSerde<OrderCreatedEvent>()
        orderCreatedSerde.configure(serdeConfig, false)
        val orderShippedSerde = SpecificAvroSerde<OrderShippedEvent>()
        orderShippedSerde.configure(serdeConfig, false)

        val stateStore: Materialized<Int, Customer, KeyValueStore<Bytes, ByteArray>> =
                Materialized.`as`<Int, Customer, KeyValueStore<Bytes, ByteArray>>("customer-store")
                        .withKeySerde(intSerde)
                        .withValueSerde(customerSerde)
```

In the previous example I also had registered a `ConfluentSchemaRegistry` bean, that addressed deserialization of the input kstream, but inside the `StreamListener` I had to rely on Confluent's `SpecificAvroSerde`, which is kind of redundant, but allows us to do what we want.

However, in the case of `KafkaStreamsStateStore`, there's no way to serialize a keystore where the value is an Avro type.

Supposing I had this StreamListener:

```
    @KafkaStreamsStateStore(name = DEDUP_STORE, type = KafkaStreamsStateStoreProperties.StoreType.KEYVALUE,
            valueSerde = "io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde")
    @StreamListener
    @SendTo("output")
    fun process(@Input("input") input: KStream<String, TransferEmitted>): KStream<String, TransferEmitted> {
        val serdeConfig = mapOf(AbstractKafkaAvroSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG to "http://localhost:8081")
        return input
                .transform(TransformerSupplier { DeduplicationTransformer() }, DEDUP_STORE)
                .filter { _, value -> fraudDetectionService.isFraudulent(value) }
    }
```

I set up a value serde of type `SpecificAvroSerde` and this class has two constructors, a no-arg, and one that receives a `SchemaRegistryClient`. `KeyValueSerdeResolver.getValueSerde` instantiantes the serde without using the schema registry client, so it eventually fails, since it's null:
```
private Serde<?> getValueSerde(String valueSerdeString)
			throws ClassNotFoundException {
		Serde<?> valueSerde;
		if (StringUtils.hasText(valueSerdeString)) {
			valueSerde = Utils.newInstance(valueSerdeString, Serde.class);
		}
```

I thought we could work around this by passing the `SchemaRegistryClient ` bean into the other `SpecificAvroRecord` constructor.

This would require modifying these classes, passing the registry client bean:

**KafkaStreamsBinderSupportAutoConfiguration**

```
    @Bean
    @SuppressWarnings("unchecked")
    @ConditionalOnMissingBean
    public KeyValueSerdeResolver keyValueSerdeResolver(
            @Qualifier("streamConfigGlobalProperties") Object streamConfigGlobalProperties,
            KafkaStreamsBinderConfigurationProperties properties,
            Optional<SchemaRegistryClient> schemaRegistryClient) {
        if(schemaRegistryClient.isPresent()) {
            return new KeyValueSerdeResolver(
                    (Map<String, Object>) streamConfigGlobalProperties, properties, schemaRegistryClient.get());
        } else {
            return new KeyValueSerdeResolver(
                    (Map<String, Object>) streamConfigGlobalProperties, properties);
        }
    }
```

**KeyValueSerdeResolver**

```
    KeyValueSerdeResolver(Map<String, Object> streamConfigGlobalProperties,
                          KafkaStreamsBinderConfigurationProperties binderConfigurationProperties) {
        this.streamConfigGlobalProperties = streamConfigGlobalProperties;
        this.binderConfigurationProperties = binderConfigurationProperties;
        this.schemaRegistryClient = null;
    }
...
private Serde<?> getValueSerde(String valueSerdeString)
            throws ClassNotFoundException {
        Serde<?> valueSerde;
        if (StringUtils.hasText(valueSerdeString)) {
            if("io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde".equals(valueSerdeString)) {
                valueSerde = Utils.newParameterizedInstance(valueSerdeString, SchemaRegistryClient.class, schemaRegistryClient);
            }else {
                valueSerde = Utils.newInstance(valueSerdeString, Serde.class);
            }
        }
```

However this is really naive, because `SpecificAvroSerde` is expecting an `io.confluent.kafka.schemaregistry.client.SchemaRegistryClient` in the constructor, not Spring's `org.springframework.cloud.stream.schema.client.SchemaRegistryClient`.

So, my initial idea isn't valid... Offhand I can think of other approaches, such as providing Spring's own Avro SerDes that take into account Spring's SchemaRegistryClient, or maybe creating the confluent SpecificAvroSerde manually, not invoking the constructor through reflection, something like:

`KeyValueSerdeResolver.getValueSerde`:
```
    private Serde<?> getValueSerde(String valueSerdeString)
            throws ClassNotFoundException {
        Serde<?> valueSerde;
        if (StringUtils.hasText(valueSerdeString)) {
            if("io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde".equals(valueSerdeString)) {
                val serdeConfig = mapOf(
                AbstractKafkaAvroSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG to registryUrl)
                valueSerde = SpecificAvroSerde<xxx>()
                valueSerde.configure(serdeConfig, false)
            } 
```

**Comment by sobychacko** [comment]
@codependent Thank you for this detailed report. Here is another idea that we can consider. How about the application creates a bean of type `StoreBuilder` and then the `StreamListener` processor injects the store when it builds the `StreamsBuilder`? That way, the application can bring whatever dependencies the `Serde` requires. This avoids the need for the binder to include dependencies to Confluent Serde classes explicitly or through reflection. 

3.0 version of the binder (basically, the current master) embraces the functional model of writing Kafka Streams application fully using the `java.util.function.Function` approach. The initial support for this is already introduced in 2.2.0 (`Germantown`). In this model, it does not support the usage of `KafkaStreamsStateStore` annotation at all and requires the strategy I just mentioned above. [Here](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka-streams/src/test/java/org/springframework/cloud/stream/binder/kafka/streams/function/KafkaStreamsFunctionStateStoreTests.java#L137), you can find such an approach. Although `StreamListener` doesn't support this currently, we can introduce it there as well. In fact, I was thinking to deprecate the use of `KafkaStreamsStateStore` annotation in 3.0, in favor of the functional model and the state store beans. 
We can certainly consider this approach for `StreamListener` in 3.0. What do you think?

**Comment by codependent** [comment]
That will definitely do and that sounds way better that what I said. It'll provide the flexibility we need to configure the StateStore tweaking the Serdes as needed. 

Will it be available starting with `Horsham` or are you planning to backport it to `Germantown`as well?

**Comment by sobychacko** [comment]
We can definitely add that as part of `StreamListener` in `Horsham`. I wasn't thinking to backport that to `Germantown`, but might not be a bad idea to incorporate that with `StreamListener` there.
