### ISSUE TITLE
Booting up application without Kafka or Zookeeper

### ISSUE THREAD

**Issue by ahmednasir91** [spring-cloud/spring-cloud-stream-binder-kafka#68]
Is it possible to configure the stream in such a way, that at the time of application boot (context loading) if zookeeper or kafka nodes are down, then it doesn't fail and keep re-trying?

**Comment by mbogoevici** [comment]
The Kafka new consumer client - available since v. 1.1 of the Kafka binder - can be configured to wait and retry until Kafka/ZK are up - however, the application will crash after a while.

**Comment by mbogoevici** [comment]
Hi @ahmednasir91  - closing this, as the question has been answered, but feel free to reopen if you have more questions.
