### ISSUE TITLE
Spring Cloud Stream Kafka Streams produces complicated topologies when using Scs serializer/deserializers

### ISSUE THREAD

**Issue by codependent** [spring-cloud/spring-cloud-stream-binder-kafka#682]
The context for this issue can be found in [this SO question](https://stackoverflow.com/questions/55929162/spring-cloud-stream-generates-unnecessary-complex-kafka-topologies-why/55943420#55943420) and in the [lattest comments](https://github.com/spring-cloud/spring-cloud-stream-samples/issues/149) of this issue in the samples repository.

Summing up, Scs Kafka Streams applications generate complex topologies in contrast with the ones generated by native Kafka Streams applications.

Check [this comment](https://github.com/spring-cloud/spring-cloud-stream-samples/issues/149#issuecomment-503759982) that shows an example from one of the spring-cloud-stream-samples, pointing at some strange processors that are added to the topology.

**Comment by sobychacko** [comment]
@codependent With native decoding being the default starting with version 3.0, the complicated topologies generated is now reduced. There was one unnecessary step that was generating an extra processor which got addressed the commit mentioned ^^. At this point, if you are on the latest snapshot, and are not changing the default native decoding, then you should get the same exact topology generated by a native Kafka Streams applications.

**Comment by codependent** [comment]
Awesome, thanks @sobychacko !
