### ISSUE TITLE
Improve InteractiveQueryService.getQueryableStore handling of InvalidStateStoreException

### ISSUE THREAD

**Issue by codependent** [spring-cloud/spring-cloud-stream-binder-kafka#706]
This issue refers to two problems regarding `InteractiveQueryService.getQueryableStore`:

```
	public <T> T getQueryableStore(String storeName, QueryableStoreType<T> storeType) {
		for (KafkaStreams kafkaStream : this.kafkaStreamsRegistry.getKafkaStreams()) {
			try {
				T store = kafkaStream.store(storeName, storeType);
				if (store != null) {
					return store;
				}
			}
			catch (InvalidStateStoreException ignored) {
				// pass through
			}
		}
		return null;
	}
```

1. The catch block is hiding the exception, which is a bad practice and could be confusing. Would you consider using a logger.warn() statement so that users are aware of the underlying problem?

2. When the state store is not ready due to a [rebalancing or whatever](https://docs.confluent.io/current/streams/faq.html#handling-invalidstatestoreexception-the-state-store-may-have-migrated-to-another-instance), users are expected to retry, doing something like: 

```
while (true) {
    try {
      return streams.store(storeName, queryableStoreType);
    } catch (InvalidStateStoreException ignored) {
      // store not yet ready for querying
      Thread.sleep(100);
    }
  }
```

`InteractiveQueryService.getQueryableStore`returns null when the state store is not ready and we could always retry while it's null. However, the `InteractiveQueryService` could offer a `getQueryableStore()` method that include this auto retry logic, maybe specifying a timeout? Do you think this makes sense?

**Comment by sobychacko** [comment]
@codependent Suggestions make sense. PR's are welcomed addressing this :-) Otherwise, we will get to it in the 3.0 timeframe.
