### ISSUE TITLE
Add a test to verify an output binding participates in an input binding transaction

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream-binder-kafka#713]
See https://stackoverflow.com/questions/57379575/spring-cloud-stream-multi-topic-transaction-management/57379903#57379903

There is a work-around, so no need to backport, I think.

**Comment by garyrussell** [comment]
It turns out that this is already fixed in SIK 3.1.2 which was released in April!!!!!

For some reason the binder is still pulling in 3.1.0. It should now be upgraded to 3.1.4.RELEASE.

I will add a test in .a PR for this.

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/2721fe4d0539efabf2cc84579cba6523d6e6235f.
