### ISSUE TITLE
Support sendTimeoutExpression for synchronous producer

### ISSUE THREAD

**Issue by Walliee** [spring-cloud/spring-cloud-stream-binder-kafka#724]
`KafkaProducerMessageHandler` supports SpEL expression for specifying send timeout when synchronous publishing is enabled but SCS doesn't provide a hook to configure it.

**Comment by Walliee** [comment]
Hey @olegz, any way I could convince you to include this in 2.2.x? 

I realize that this is technically new functionality but I was hoping to get this before **Horsham.RELEASE**. 

Thanks!

**Comment by olegz** [comment]
@sobychacko what do you think?

**Comment by sobychacko** [comment]
@Walliee Sure, we can backport to 2.2.x.

**Comment by sobychacko** [comment]
@olegz @Walliee Backported the commit to 2.2.x branch.

**Comment by Walliee** [comment]
Thanks @sobychacko @olegz !

**Comment by saluca2** [comment]
@olegz , @sobychacko, is there any date defined for releasing 2.2.x branch with this change?
