### ISSUE TITLE
Support Boot 1.5 configuration properties for Kafka

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream-binder-kafka#73]
Spring Boot 1.5 is introducing Kafka support, so we should be able to support the Kafka autoconfiguration the same way as we do with Rabbit.

**Comment by mbogoevici** [comment]
This should maintain backwards compatibility with 1.4 - so if Boot 1.4 is on the classpath instead of Boot 1.5, we should fall back to the current configuration options. The typical use case is a Spring Cloud user using Dalston with Spring Boot 1.4.

**Comment by ilayaperumalg** [comment]
Based on some [preliminary work](https://github.com/ilayaperumalg/spring-cloud-stream-binder-kafka/commit/aebd9ebf23f9ff75efd539d9a59dfaba4990a04e) on this, I realised that we need to have `common` default values for SCSt Kafka Producer/Consumer properties and `KafkaProperties` from auto configuration. For instance, SCSt KafkaProducerProperties has  `keySerializer` default value `ByteArraySerializer`whereas the spring-boot `keySerializer` default value `StringSerializer`. It is difficult to know if the values comes out of default or user sets it explcitly.

May be we don't set any default values in the AutoConfiguration KafkaProperties at all?

**Comment by mbogoevici** [comment]
We may override Spring Boot defaults and document how that happens in order to preserve the current behaviour of Spring Cloud Stream. What is important is for users to be able at least, to use the same property names for configuration.

**Comment by ilayaperumalg** [comment]
I think overriding Spring Boot defaults may not be a better option as we may not know whether the Spring Boot `KafkaProperties` carries the defaults or the user specified ones.

Let's consider the following scenario:

We set the kafka producer key/value serialiser to `ByteArraySerializer` by default at SCSt while KafkaProperties form Spring Boot has the default value `StringSerializer`. If we want to override the `KafkaProperties`, we wouldn't be sure if `StingSerializer` is coming the `default` value or is it from the value set by the user.

**Comment by mbogoevici** [comment]
We definitely cannot use `StringSerializer` as the default.

**Comment by ilayaperumalg** [comment]
Yeah, that's the reason I am thinking it would be better to completely remove the defaults in Spring Boot KafkaProperties.

**Comment by artembilan** [comment]
You can use `EnvironmentPostProcessor` to override `spring.kafka.producer.keySerializer` if it doesn't exist in the `Environment` yet.

**Comment by ilayaperumalg** [comment]
@artembilan that's a good idea. I will check that out. Thank you!
