### ISSUE TITLE
KafkaBindingProperties has no documentation (so no popup help in IDE)

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-stream-binder-kafka#739]
Also related nested objects: `KafkaConsumerProperties` and `KafkaProducerProperties`.

**Comment by sobychacko** [comment]
@dsyer `KafkaBindingProperties` is a pojo used in a map from `KafkaExtendddBindingProperties` [here](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka-core/src/main/java/org/springframework/cloud/stream/binder/kafka/properties/KafkaExtendedBindingProperties.java#L46). Per @snicoll map of pojo won't get metadata support in IDE, but there is an issue to support that in boot. It lists the available properties, but no pop-up docs help. Or are you referring to something else here? Thanks!

**Comment by dsyer** [comment]
I see them in the IDE with "no description". That suggests to me that the IDE would happily add a description if there was one. Whether the AP can generate them is another question (but I don't really see why not).

**Comment by snicoll** [comment]
There never was documentation for Maps of POJO, see https://github.com/spring-projects/spring-boot/issues/9945

**Comment by dsyer** [comment]
Maybe the IDE would display Javadocs if they were available in the POJO (that's what the popup in Eclipse suggests to me at least)? The properties need to be documented IMO anyway, so it's worth doing. The only question is whether to do it in a format acceptable to the AP, in case one day it decides to support this as well.

**Comment by dsyer** [comment]
OK, so I tested it. Eclipse (STS) will show the Javadocs from the getter method (not the field) in a POJO. I think we should put some docs in there. And maybe when the AP catches up it can look there as well.

**Comment by sobychacko** [comment]
@dsyer Is it only for the POJO's inside the map that Javadocs need to be added on the getter methods and not on the fields? We usually add Javadocs on the fields only.

**Comment by dsyer** [comment]
Yes. Fields is what the AP supports. But the AP does not support mapped POJOs currently.
