### ISSUE TITLE
Consider making the default `DefaultKafkaHeaderMapper` a bean

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-stream-binder-kafka#749]
in Sleuth we'll need to add wrapping of `DefaultKafkaHeaderMapper` implementations. Unfortunately the default `DefaultKafkaHeaderMapper` object is not a bean so Sleuth can't wrap it.

It would be great to consider making the default `DefaultKafkaHeaderMapper` instance as a bean.

related issue https://github.com/spring-cloud/spring-cloud-sleuth/issues/1430

**Comment by garyrussell** [comment]
There is an existing binder property `headerMapperBeanName` which defaults to `null`, allowing users to configure a customized mapper.

https://cloud.spring.io/spring-cloud-static/spring-cloud-stream-binder-kafka/2.2.1.RELEASE/spring-cloud-stream-binder-kafka.html#_configuration_options

>**spring.cloud.stream.kafka.binder.headerMapperBeanName**

>The bean name of a KafkaHeaderMapper used for mapping spring-messaging headers to and from Kafka headers. Use this, for example, if you wish to customize the trusted packages in a DefaultKafkaHeaderMapper that uses JSON deserialization for the headers.

>Default: none.

Perhaps we could check for a bean under a well known name if none is provided by the user configuration.

**Comment by marcingrzejszczak** [comment]
I think that would do. If the bean name would be set to e.g. `headerMapper`, then I could check if there is such a bean and if that's not the case, then I would register my, default one, under that name.

**Comment by garyrussell** [comment]
I think this will be useful.

But I am also going to make some changes in Spring Kafka:

- Outbound: Don't JSON encode String-valued headers, use a special marker in the JSON metadata
- Inbound: Handle both JSON encoded Strings and raw Strings
- Add a boolean to control this behavior (default true).

This will mean that sleuth will not need any changes.
