### ISSUE TITLE
Consume standardized additional kafka properties from Boot

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-kafka#75]
As a developer, I'd like to add additional kafka client properties inherited from Boot via https://github.com/spring-projects/spring-boot/issues/7646.

**Acceptance:**
- Boot version upgrade (with the additions) brings in the additional properties
- docs include the new property

**Comment by mbogoevici** [comment]
Closing as it was tracking Spring Boot effort.
