### ISSUE TITLE
Failed to create consumer binding

### ISSUE THREAD

**Issue by imbaq123** [spring-cloud/spring-cloud-stream-binder-kafka#751]
Failed to create consumer binding; retrying in 30 seconds org.springframework.cloud.stream.provisioning.ProvisioningException: provisioning exception; nested exception is org.apache.kafka.common.errors.UnknownServerException: internal error.

kafka client version is spring cloud stream kafka 2.0.2
kafka server version is 0.10.x

**Comment by olegz** [comment]
There is not enough information for us to act on
