### ISSUE TITLE
Support CloudEvents Kafka Transport Binding Spec

### ISSUE THREAD

**Issue by mhyeon-lee** [spring-cloud/spring-cloud-stream-binder-kafka#759]
I am wondering if there are any plans to support the CloudEvents specification.

There is a Kafka Transport Binding Specification in CloudEvents v0.3.

There is also a java-sdk that implements this specification.
https://github.com/cloudevents/sdk-java/blob/master/kafka/README.md

**Comment by sabbyanandan** [comment]
Hi, everyone. Thanks for your interest in this subject. @olegz recently published a few blogs (see: [part-1](https://spring.io/blog/2020/12/10/cloud-events-and-spring-part-1) / [part-2](https://spring.io/blog/2020/12/23/cloud-events-and-spring-part-2)) to highlight the spec compatibility. 

Please review them and the samples, and let us know if this addresses your use-cases. If you see gaps, feel free to raise specific issues.
