### ISSUE TITLE
Allow custom configuration of partition metadata producer

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream-binder-kafka#76]
Moved from: https://github.com/spring-cloud/spring-cloud-stream/issues/744.

From @PedroAlvarado

> At the moment, we use the DefaultKafkaProducerFactory to create a new producer to fetch partition metadata. This producer uses a combination of hard-coded and default producer configuration making it difficult to tailor its configuration.
> 
> A sample use-case for this feature is the case of local development where we want to fail fast when, say, the kafka broker is not working correctly. In this scenario, currently and out-of-the-box, spring cloud stream will wait 10 minutes (60000ms=max.block.ms * 10=SimpleRetryPolicy.maxAttempts) to fail. Moreover, there is not indication that retries are taking place, hence, the logs look like the application may have started successfully.

**Comment by sobychacko** [comment]
@PedroAlvarado With the recent provisioning changes, the issue mentioned here has become somewhat defunct. Prior to provisioning, we were using the `DefaultProducerFactory` for fetching partition metadata in both producer and consumer endpoint wiring and not allowing to configure that producer factory. 

Now it is changed in such a way that the partition metadata fetching in  `createProducerMessageHandler` is using the common producer factory used for other operations in this method. Therefore, you can pass in various kafka producer properties and they will be honored by the producer factory when the partition info is fetched as it is no longer using a dedicated non-configurable producer factory. 

In a similar vein, the partition metadata fetching logic in `createConsumerEndpoint` alsoe uses the common consumer factory. This consumer accepts any kafka consumer properties and will be honored during the partition metadata fetching as well. 

See these changes for more details:
https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java#L148

and

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java#L210

**Comment by PedroAlvarado** [comment]
@sobychacko This makes sense. That code reads much better now. I agree that we can call this issue obsolete. Thank you!

**Comment by sobychacko** [comment]
@PedroAlvarado Closing this issue now. Thanks!
