### ISSUE TITLE
Kafka Streams DLQ - more fine grained partitions control

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream-binder-kafka#763]
Right now in Kafka Streams binder, it expects that the DLQ has the same number of partitions as the input topic. That is true if the provisioner creates the topic, but if it doesn't, then the app needs to ensure that the DLQ is created with the right number of partitions. In order to address this, we should make the creation of DLQ topic more flexible. Maybe something like dlqPartitionExpression evaluated against the CR, with the default being cr.partition(); if it evaluates to null, Kafka will choose the partition, or the expression could simply evaluate to 0, 1, 2, etc.

**Comment by y-manish** [comment]
Yeah, having control on DLQ partition count will be helpful. Thank you.
For now, is there some work around way for this as of now(version : 2.1.x).

**Comment by garyrussell** [comment]
There is no work around; sorry.
