### ISSUE TITLE
Kafka Streams binder fails to bind with default naming convention

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-stream-binder-kafka#766]
With recently added support for functions with multiple inputs/outputs it appears that KafkaStreams binder only handles cases where bindings were explicitly mapped. 
For example:
Given the following function bean
```
@Bean
public Function<KStream<Long, Order>, 
        Function<GlobalKTable<Long, Customer>,
                Function<GlobalKTable<Long, Product>, KStream<Long, EnrichedOrder>>>> process() {
    . . .
}
```
. . . it would only work if the following properties were defined

```
"--spring.cloud.stream.function.bindings.process-in-0=1order",
"--spring.cloud.stream.function.bindings.process-in-1=2customer",
"--spring.cloud.stream.function.bindings.process-in-2=3product",
"--spring.cloud.stream.function.bindings.process-out-0=enriched-order",
"--spring.cloud.stream.bindings.1order.destination=orders",
"--spring.cloud.stream.bindings.2customer.destination=customers",
"--spring.cloud.stream.bindings.3product.destination=products",
"--spring.cloud.stream.bindings.enriched-order.destination=enriched-order",
```
However, properties above are *only* required for cases where inputs and outputs have to be explicitly mapped to the existing destinations. In other words for simple cases (e.g., auto-provisioning), non of the properties declared above are needed and the application should function without them.

**Comment by sobychacko** [comment]
This issue is already resolved by the following commits.

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/c7fa1ce275d3546cc9f9e309c2dc302c1ca58afd

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/9d708f836a6b319b5e7eebbfa0bcbab0ef785476
