### ISSUE TITLE
Replication factor option for Kafka Stream binder

### ISSUE THREAD

**Issue by boonware** [spring-cloud/spring-cloud-stream-binder-kafka#769]
The documentation states that the property `spring.cloud.stream.kafka.binder.replicationFactor` for the Kafka binder sets the replication factor for auto-created topics; there is no mention of a similar property for the Kafka Streams binder.

I have an application using a KStream. I can only successfully set the replication factor for the KStream topic when I use the option `spring.cloud.stream.kafka.streams.binder.replicationFactor` (note the word "streams"). This option is not explicitly documented for the Kafka Streams binder.

Perhaps such plain Kafka binder options can be re-used for the Kafka Streams binder, but if this is the case it is not entirely clear. Can you clarify?

Documentation: https://cloud.spring.io/spring-cloud-stream-binder-kafka/spring-cloud-stream-binder-kafka.html

**Comment by sobychacko** [comment]
@boonware All the properties available in `KafkaBinderConfigurationProperties` for topic creation (such as the replication factor) is available for the Kafka Streams binder also. However, as you already noticed, when used in the context of Kafka Streams types, you need to prefix the configuration with `spring.cloud.stream.kafka.streams.binder`. Maybe we should be more clear on the docs about this. Contributions are welcomed.

**Comment by boonware** [comment]
Thanks for the info, however I've still only had limited success by setting those options. My application "myApp" attempts to create a materialized view "myView" with a KStream, and in response Spring Cloud Stream attempts to create the topic `myApp-myView-repartition`. Howevere, this fails with the following exception:

> Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.PolicyViolationException: Replication factor valid but must be set to 3
> 	at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
> 	at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
> 	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
> 	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:262)
> 	at org.apache.kafka.streams.processor.internals.InternalTopicManager.makeReady(InternalTopicManager.java:122)

I'm not sure where the policy is coming from, perhaps from the Kafka cluster I am using (it's shared, but none-the-less even when I set the replication factor to 3 with the option above it is still throwing this exception.

Is there a bug here in the replication factor value to being set for internal topic creation? Or is there something else I'm missing here?

**Comment by sobychacko** [comment]
@boonware Can you share a small app where we can reproduce what you are seeing?

**Comment by boonware** [comment]
@sobychacko I've created a sample application [here](https://github.com/boonware/spring-cloud-stream-binder-kafka_769). Let me know if you have any issues using the sample.

**Comment by sobychacko** [comment]
@boonware Thank you for the sample. I tried to run your app after removing all the jass config. I think here is what's going on.  The following 2 properties are only applied during the topic creation by the topic provisioner in the binders. 
```
spring.cloud.stream.kafka.binder.replicationFactor = 3
spring.cloud.stream.kafka.streams.binder.replicationFactor = 3
```
Internal topics in Kafka Streams such as the repartition topics are not created by the binder provisioner and they are created internally by Kafka Streams. The replication factor specified above will not be delegated for these topics. For that, you still need to provide that as below.
```
spring.cloud.stream.kafka.streams.binder.configuration.replication.factor=3
```
If its a common use case, we can consider delegating this internally by the binder somehow. 

Please see if this takes care of your issue. 

I also found another problem with your configuration. I think the following properties are wrong.

```
spring.cloud.stream.kafka.streams.bindings.inputStream.destination = DELETE_ME
spring.cloud.stream.kafka.streams.bindings.inputStream.group = myInputStreamGroup
spring.cloud.stream.kafka.streams.bindings.inputStream.contentType = application/json
```

These are core Spring Cloud Stream properties and should be specified as any other types of bindings. This is the proper usage.
```
spring.cloud.stream.bindings.inputStream.destination = DELETE_ME1
spring.cloud.stream.bindings.inputStream.group = myInputStreamGroup
spring.cloud.stream.bindings.inputStream.contentType = application/json
```
Hope this helps!

**Comment by sobychacko** [comment]
@boonware did it address your issues?

**Comment by boonware** [comment]
@sobychacko Thanks for the help, that fixed it!!! I'm happy to close this if you are. We can follow up separately if this needs to go into the codebase; at least we know that configuration works.

**Comment by sobychacko** [comment]
@boonware Yep. Please feel free to close it. Ping here again if there are further changes required.
