### ISSUE TITLE
`s.c.st.k.bindings.producer.bufferSize` is ignored 

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream-binder-kafka#77]
It seems like we ignore the Boot-bound property and default to 16384 instead.

**Comment by sobychacko** [comment]
I think this line is the culprit. https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java#L250

However, as a work around, end users can force batch size by using this property. Aren't they the same?: `spring.cloud.stream.bindings.producer...configuration.batch.size`

**Comment by mbogoevici** [comment]
Yes, but apps migrating from 1.0 might find this an issue. We also document that property.
