### ISSUE TITLE
Availability for version 3.0

### ISSUE THREAD

**Issue by pm-ayan-bose** [spring-cloud/spring-cloud-stream-binder-kafka#787]
Documentation says:
Starting with version 3.0, when spring.cloud.stream.binding.<name>.consumer.batch-mode is set to true, all of the records received by polling the Kafka Consumer will be presented as a List<?> to the listener method.

When we can expect 3.0 version to be available for public consumption?

**Comment by sobychacko** [comment]
@pm-ayan-bose Spring Cloud Stream `Horsham` release train (which contains the `3.0.0` versions) will become GA next month. We had the first release candidate (RC1) out yesterday, but the announcement on it will happen early next week. For questions like this, it will be best to use the [gitter channel](https://gitter.im/spring-cloud/spring-cloud-stream) for Spring Cloud Stream. You will get a faster response there. Please use GH only for filing bug reports or new feature requests.
