### ISSUE TITLE
Producer converterBeanName support

### ISSUE THREAD

**Issue by 51systems** [spring-cloud/spring-cloud-stream-binder-kafka#790]
The `converterBeanName` (eg: `spring.cloud.stream.kafka.bindings.input.consumer.converterBeanName`) allows the end user to specify the `RecordMessageConverter` for the consumer. 

`RecordMessageConverter` have a `toMessage` and a `fromMessage` method (consumers only use the `toMessage` method). There does not appear to be a way to make a producer use the `fromMessage` method to create the `ProducerRecord`.

Background: I'm trying to develop a binding that can properly convert Messages with a CloudEvent payload to/from ProducerRecords and ConsumerRecords

**Comment by garyrussell** [comment]
3.0.0.RC1 introduced the `ProducerMessageHandlerCustomizer`. Using that you can do this...

```java
@Bean
public ProducerMessageHandlerCustomizer<KafkaProducerMessageHandler<byte[], byte[]>> templateCustomizer() {
	return (handler, dest) -> {
		handler.getKafkaTemplate().setMessageConverter(...));
	};
}
```

**Comment by garyrussell** [comment]
Oops - sorry, yes, you are correct.

Please open an issue against [spring-integration-kafka](https://github.com/spring-projects/spring-integration-kafka/issues); we should support a custom `RecordMessageConverter` there.

**Comment by garyrussell** [comment]
>Background: I'm trying to develop a binding that can properly convert Messages with a CloudEvent payload to/from ProducerRecords and ConsumerRecords

Another solution for that is to set `useNativeEncoding` and create a Kafka Serializer to convert your event as needed.

**Comment by garyrussell** [comment]
SIK now provides a hook for customizing the creation of `ProducerRecord`s; when it realeased (Monday is the plan), we will upgrade to that version prior to GA.
