### ISSUE TITLE
Stream Binder Health Indicator creates Admin client every times

### ISSUE THREAD

**Issue by Delorien84** [spring-cloud/spring-cloud-stream-binder-kafka#791]
Hi,
 we are testing Hoxton.RC1 and we notice that our logs are spawned by AdminClient creation. It is caused by Health indicator changes introduced in #773. The health check creates kafka admin client every time the health check needs to be calculated.

We have several services that calls health endpoint causing to create admin client every few seconds.

The admin client should be cached. Eg. `org.springframework.cloud.stream.binder.kafka.KafkaBinderHealthIndicator` does it.

Cloud Version: Hoxton.RC1

**Comment by sobychacko** [comment]
@Delorien84 This issue is addressed in the latest snapshots. We will release an `RC2` next week. Could you confirm if the issues you raised have been addressed? Thanks!
