### ISSUE TITLE
Allow Kafka Streams binding to use Kotlin lambdas

### ISSUE THREAD

**Issue by yonigibbs** [spring-cloud/spring-cloud-stream-binder-kafka#795]
Currently (version 3.0) Kafka Streams binding functional support requires `java.util.function` types. It would be good to allow Kotlin lambdas to be used directly without the need for these types.

For an example of this, see here: https://stackoverflow.com/questions/58732683/spring-cloud-stream-function-kotlin-lambdas-without-the-use-of-java-function-bi/

**Comment by sabbyanandan** [comment]
Closing this in favor of https://github.com/spring-cloud/spring-cloud-stream/issues/1935.
