### ISSUE TITLE
Missing Spring core version

### ISSUE THREAD

**Issue by Mwea** [spring-cloud/spring-cloud-stream-binder-kafka#8]
I just cloned the project and tried to open it in Intellij Idea, I get this error on each pom xml on this project : For artifact {org.springframework:spring-core:null:jar}: The version cannot be empty
Any solution ?

**Comment by mbogoevici** [comment]
Hi,

Closing this as it is most likely related to the Maven version: see http://stackoverflow.com/questions/39620099/springcloudstream-failing-on-spring-core-version for details.
