### ISSUE TITLE
Actuator checks for binders fail

### ISSUE THREAD

**Issue by am-wr** [spring-cloud/spring-cloud-stream-binder-kafka#803]
When I run [`kafka-streams-word-count`](https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/kafka-streams-samples/kafka-streams-word-count) example.

Actuator's health check fail
http://localhost:8080/actuator/health

```json
{
  "status": "DOWN",
  "components": {
    "binders": {
      "status": "DOWN",
      "components": {
        "globalktable": {
          "status": "DOWN",
          "details": {
            "No topic information available": "Kafka broker is not reachable"
          }
        },
        "kstream": {
          "status": "DOWN",
          "details": {
            "No topic information available": "Kafka broker is not reachable"
          }
        },
        "ktable": {
          "status": "DOWN",
          "details": {
            "No topic information available": "Kafka broker is not reachable",
            "error": "java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: The AdminClient thread is not accepting new calls."
          }
        }
      }
    },
    "diskSpace": {
      "status": "UP",
      "details": {
        "total": 250685575168,
        "free": 25818120192,
        "threshold": 10485760
      }
    },
    "ping": {
      "status": "UP"
    }
  }
}
```

I run kafka locally this way:

docker run -e ADV_HOST=127.0.0.1 -e EULA="https://dl.lenses.io/d/?id=..." --rm -p  3030:3030 -p 9092:9092 lensesio/box

**Comment by vitjouda** [comment]
Hi, I have the same actuator output, it seems to be caused by this error

`java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Double (java.lang.Long and java.lang.Double are in module java.base of loader 'bootstrap')
        at org.springframework.cloud.stream.binder.kafka.streams.KafkaStreamsBinderMetrics$1.lambda$toDoubleFunction$0(KafkaStreamsBinderMetrics.java:92)`

**Comment by am-wr** [comment]
It is caused but inappropriate usage of `adminClient`, which is closed on the first call. Second time will fail on `adminClient.listTopics()` as connection is closed. 

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/KafkaStreamsBinderHealthIndicator.java#L120

**Comment by am-wr** [comment]
PR: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/804/files

**Comment by simsibimsiwimsi** [comment]
Hi @am-wr, we have encountered an issue with the current fix: if the health endpoint is called with an insufficient request timeout (i.e. k8s readiness probe requestTimeout default of 1 sec) with multiple components (ktable, globalktable, kstream, ...) it can happen that a java.lang.InterruptedException is encountered in line. Subsequently the component's health is reported DOWN, but really it is UNKNOWN.
