### ISSUE TITLE
Ability to map to complex object while batching

### ISSUE THREAD

**Issue by kamilolszewski-nekken** [spring-cloud/spring-cloud-stream-binder-kafka#807]
Regarding spring-cloudGH-70 by @garyrussell 

In the test KafkaBinderTests.java of mentioned issue I can see that messages are bound to `List<byte[]>` is it possible to use complex objects like `List<SomeEventMessage>`?

If I try to use it with consumer.batch-mode=true with such listener:
```
    @StreamListener("eventsIn")
    fun processEvents(messages: List<SomeEventMessage>) {
```

commands are still mapped internally to ArrayList<byte[]> and that breaks further code.

Seems that such messages fall into SmartPayloadArgumentResolver.conversionNotRequired where being marked with "true", therefore they stay as byte arrays.

Sorry if I miss some technial restrictions that prevent this - is there any workaround then?
Yet it seems to be possible in Spring Kafka if I look at this gist: https://gist.github.com/prabhakar349/e5965ac441f747e2fbedcbc42682aec6

**Comment by kamilolszewski-nekken** [comment]
version: 3.0.0 RC2

**Comment by garyrussell** [comment]
In Spring Cloud Stream, batching support is only available with the newer function-based bindings and not with `@StreamListener`.

In java, such a listener would be 

```java
@Bean
public Consumer<List<SomeEventMessage>> listener() {
    return list -> { .. }
}
```

Yes, it's supported in Spring for Apache Kafka itself, using `@KafkaListener`.

**Comment by kamilolszewski-nekken** [comment]
I still cannot figure out how to simply send messages like with MessageChannels in this new functional approach.

Still, Cosumer works great with batching just like you mentioned. Thank you.
