### ISSUE TITLE
Enhancement: Support Coercing `replication-factor` when default and Broker defines a policy

### ISSUE THREAD

**Issue by derrick-anderson** [spring-cloud/spring-cloud-stream-binder-kafka#808]
Use Case:
When using the spring cloud stream binder, I would like to be able to auto-provision topics with minimal boilerplate code. When connecting to a broker that defines a policy for items like `replication-factor` i would like the binder to coerce the default selection (in this case 1) to the required selection (in this case 3). 

Reproduction:
When using Confluent Cloud as my Kafka provider, I can connect to the broker successfully by attaching my `configuration` set to the `spring.cloud.stream.kafka.binder.configuration`.  However, if spring attempts to create a Topic that does not exist the following error will be thrown.

```
ERROR 19109 --- [           main] o.s.c.s.b.k.p.KafkaTopicProvisioner      : Failed to create topics
org.apache.kafka.common.errors.PolicyViolationException: Topic replication factor must be 3 
```
Preventing topic creation and ultimately application startup.

Solutions:
I see that the Kafka Topic provisioner does have a feature currently that coerces the partition tolerance down if allowed by the configuration properties and notifies the user as such.  Can we include a default override for policy violations such as this?  For example, knowing that I set the value as 2 means that i would see an error but leaving the default as 1 would allow the system to coerce it to the broker defined policy value of 3.

Thanks for reading, I look forward to input.
-Derrick

**Comment by sobychacko** [comment]
@derrick-solstice Have you tried setting the replication factor as a binding level topic property? `spring.cloud.stream.kafa.bindings.input.consumer.topic.replicationFactor` (change `input` to the actual binding name) will be used by the provisioner. If you set that to `3`, then I think the binder will create the topic with a replication factor of `3`.

**Comment by derrick-solstice** [comment]
@sobychacko Thanks for the response,  yes I was able to modify my `replication-factor` property on the binder.  

My enhancement proposal was more toward providing a method for respecting policies at the broker level.  Particularly when they just change the default setting and have no functionality impact.  The reason i believe there is precedent here is that it's already supported for partitions through a tolerate flag.

In this particular scenario, if Confluent was to change their broker policy after i've deployed DataFlow, I would suddenly stop connecting as no new topics would be provisioned.

Further, this was originally encountered while implementing Spring Cloud Data Flow on GKE and it is quite hard to change the service map properties after deployment without a full re-creation.

**Comment by sobychacko** [comment]
@derrick-solstice Please feel free to submit a PR with this enhancement, which we can then review. is that a possibility?

**Comment by garyrussell** [comment]
I think it might be difficult to do this; presumably there are more policy violations than just this one; I think it would be too brittle to parse the exception message to figure out that the violation was due to insufficient replicas requested.

**Comment by garyrussell** [comment]
I think it might be difficult to do this; presumably there are more potential policy violations than just this one; I think it would be too brittle to parse the exception message to figure out that the violation was due to insufficient replicas requested.

Furthermore `create.topic.policy.class.name` server configuration says:

>The create topic policy class that should be used for validation. The class should implement the `org.apache.kafka.server.policy.CreateTopicPolicy` interface.

There do not appear to be any standard implementations and so the exception message is entirely user-defined.

**Comment by derrick-solstice** [comment]
@garyrussell  Do you know if there is a way to request the Current Policies from the broker?

**Comment by garyrussell** [comment]
@derrick-solstice I don't see how that would be possible, given that the policy is not simply configuration, it is implemented in user-provided code that is wired into the broker with property 

`create.topic.policy.class.name=com.example.demo.MyPolicy` 

(see my example above). Presumably the group that manages your broker(s) have implemented such a policy.

**Comment by derrick-solstice** [comment]
No problem @garyrussell , I'll bring this feedback back to the Confluent team.  They may discuss either changing their policy for compatibility or maybe proposing a change to their documentation. 

Secondary question:  I wasn't able to infer from the implementation, but does the Topic provision code *require* a replication-factor?  I'm wondering if maybe we could omit the default and that the Broker could decide in its absence.

Thanks for the input team!  If the replication-factor is required we can just shut this conversation down and i'll work with Confluent on making their configuration easier to interface with.  Happy Holidays!

**Comment by garyrussell** [comment]
@derrick-solstice I just looked at the code on trunk and it looks like the upcoming 2.4 version supports sending `-1` to signal the default should be used...

```scala
        val resolvedReplicationFactor = if (topic.replicationFactor == NO_REPLICATION_FACTOR)
          defaultReplicationFactor else topic.replicationFactor
```

The current client has no such logic.

**Comment by derrick-solstice** [comment]
OH!  So the default value for `replication-factor` will be changing from `1` to `-1` to indicate to the broker that the default at the broker level should be used?  Fantastic Find!

I would love to try this out has that been published to a Snapshot build yet?

**Comment by garyrussell** [comment]
I didn't dig further regarding the default, but it looks to me like you have to explicitly create the `NewTopic` passed to the `AdminClient` with -1. The only constructors take either a replication factor or replicate assignments.

Unfortunately, they don't currently publish snapshots; I have built the clients locally in preparation for spring-kafka 2.4 (the new clients are not binary compatible with code compiled against 2.3) but I have not built a 2.4 broker yet. Last time I looked, Kafka 2.4 is scheduled for release 11/30 and we will follow with Spring for Apache Kafka 2.4 release candidate shortly thereafter. 

Using 2.4 with Boot 2.2 will require a bunch of version overrides in user POMs.

**Comment by garyrussell** [comment]
KIP: https://cwiki.apache.org/confluence/display/KAFKA/KIP-464%3A+Defaults+for+AdminClient%23createTopic

Pull Request: https://github.com/apache/kafka/pull/6728

Commit: https://github.com/apache/kafka/commit/8e161580b859b2fcd54c59625e232b99f3bb48d0

**Comment by garyrussell** [comment]
I've tested it with a 2.4 broker and setting the binder property to -1.

    spring.cloud.stream.kafka.binder.replication-factor=-1

has the desired effect.

The kafka server.properties needs 

    default.replication.factor=2

So, we're all set when the 2.4 broker is available.

**Comment by garyrussell** [comment]
We might want to keep this open and track for 3.1; it may make sense to change the default to `-1`.
