### ISSUE TITLE
KafkaBinderMetrics.computeUnconsumedMessages blocks prometheus actuator

### ISSUE THREAD

**Issue by robwruck** [spring-cloud/spring-cloud-stream-binder-kafka#809]
Currently, the metric `spring.cloud.stream.binder.kafka.offset` is implemented as a Gauge. That means that every request for `/actuator/prometheus` triggers a synchronous call to `computeUnconsumedMessages` which in turn waits for up to 60 seconds (DEFAULT_TIMEOUT) for a result from Kafka.
A Gauge is not meant to run lengthy or asynchronous computations. When a Kafka broker becomes temporarily unavailable, this Gauge will cause `/actuator/prometheus` to respond with a 60 seconds delay, which might be too much for the Prometheus scraper resulting in **no metrics** being recorded until the broker is available again.
Since you are already spawning a new ThreadPoolExecutor on every call to `computeUnconsumedMessages`, it would be more efficient to use a single ThreadPoolExecutor to periodically calculate this metric in the background and use the Gauge to retrieve the most recent value.

**Comment by sobychacko** [comment]
@robwruck Thank you for the suggestion. That sounds like a reasonable approach to me. You are most welcomed to contribute a PR with these enhancements which we can then review!
