### ISSUE TITLE
KafkaStreamsBinderMetrics throws ClassCastException

### ISSUE THREAD

**Issue by matus753** [spring-cloud/spring-cloud-stream-binder-kafka#814]
on the start up of application, when metrics is binded to MeterRegistry by `org.springframework.cloud.stream.binder.kafka.streamsKafkaStreamsBinderMetrics.` I am getting following error: 
`
java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Double (java.lang.Long and java.lang.Double are in module java.base of loader 'bootstrap') 	at org.springframework.cloud.stream.binder.kafka.streams.KafkaStreamsBinderMetrics$1.lambda$toDoubleFunction$0(KafkaStreamsBinderMetrics.java:92) ~[spring-cloud-stream-binder-kafka-streams-3.0.0.RELEASE.jar!/:3.0.0.RELEASE] 	at io.micrometer.core.instrument.internal.DefaultGauge.value(DefaultGauge.java:54) ~[micrometer-core-1.3.1.jar!/:1.3.1] 	at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$newGauge$3(PrometheusMeterRegistry.java:245) ~[micrometer-registry-prometheus-1.3.1.jar!/:1.3.1] 	at io.micrometer.prometheus.MicrometerCollector.collect(MicrometerCollector.java:69) 	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:190) ~[simpleclient-0.7.0.jar!/:na] 	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:223) 	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:144) 	at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22) ~[simpleclient_common-0.7.0.jar!/:na] 	at org.springframework.boot.actuate.metrics.export.prometheus.PrometheusScrapeEndpoint.scrape(PrometheusScrapeEndpoint.java:50) ~[spring-boot-actuator-2.2.1.RELEASE.jar!/:2.2.1.RELEASE] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java) ~[na:na] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:566) 	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:279) ~[spring-core-5.2.1.RELEASE.jar!/:5.2.1.RELEASE] 	at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.j.
--
`

**Comment by ToddAHughes** [comment]
I encountered the same issue.  For my case it was specifically related to app.info.start.time.ms which was added for kafka 2.3.0 and described [here](https://cwiki.apache.org/confluence/display/KAFKA/KIP-436%3A+Add+a+metric+indicating+start+timel).  At first I thought this exception might be the cause of other issues I've noticed with missing metrics, but instead found that is a separate issue relating to metrics of the same name not being added (eg from multiple consumers) and I'll report that separately soon if no one beats me to it.

**Comment by sobychacko** [comment]
@matus753 @ToddAHughes Is it happening all the time that you are trying to access the metrics? Could you provide any instructions to reproduce this issue?

**Comment by matus753** [comment]
it's hapenning every time when first message is read from input after application strated
it's write only WARN message: 
`2019-12-18T06:50:47,558Z | [XNIO-1 task-2] WARN  i.m.c.i.internal.DefaultGauge - Failed to apply the value function for the gauge 'app.info.start.time.ms'. Note that subsequent logs will be logged at debug level.`

i am running on this versions:
spring boot -> 2.2.1.RELEASE
spring cloud -> Hoxton.RELEASE
spring-cloud-stream-binder-kafka -> 3.0.0.RELEASE

for metrics I am using micrometer with prometheus so basic instraction for reproduce would be app reading messages from kafka by spring cloud stream binder (in my case using Kstream) and with active prometheus endpoint by micrometer

**Comment by sobychacko** [comment]
@matus753 Can you provide the dependencies in your build (maven pom)?

**Comment by Schwurbel** [comment]
The error occurs with the following dependencies:

org.springframework.boot:spring-boot-starter-webflux:2.2.2.RELEASE
org.springframework.kafka:spring-kafka:2.3.4.RELEASE
org.springframework.cloud:spring-cloud-stream:3.0.1.RELEASE
org.springframework.cloud:spring-cloud-stream-binder-kafka:3.0.1.RELEASE

**Comment by simsibimsiwimsi** [comment]
In https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/KafkaStreamsBinderMetrics.java there is a cast to Double which causes the exception:

`
if (metric.metricValue() instanceof Number) {
    return (Double) metric.metricValue();
}
`

Programmatically it is probably not a good idea to check for Number and cast to Double instead as mentioned in https://stackoverflow.com/questions/32757565/java-lang-long-cannot-be-cast-to-java-lang-double. Instead I would suggest: 

`
if (metric.metricValue() instanceof Number) {
    return ((Number) metric.metricValue()).doubleValue();
}
`
