### ISSUE TITLE
Kafka partitions do not get created if non-native apps used

### ISSUE THREAD

**Issue by mshalak-nix** [spring-cloud/spring-cloud-stream-binder-kafka#818]
I use Kubernetes cluster and Kafka. My goal is to have several instances of an app in a stream properly load balanced.
When I create a stream with provided Spring starters (trigger->log) and specify 3 instances of the log sink, messages to these log pods get balanced properly via three partitions of a Kafka topic.
But looks like this is not supported for non-native apps out of the box. When I do the same using my own sink, which is a Docker container with Python inside, only one partition gets created for a Kafka topic, so all the messages arrive to the same pod only.
Is there any configuration I should do on my own to setup load balancing properly?

**Comment by mshalak-nix** [comment]
Got an answer: this is our responsibility to wire everything together if we use non-native apps with SCDF. Details here: https://stackoverflow.com/a/59349117/2070861

**Comment by sabbyanandan** [comment]
Closing this as a duplicate.
