### ISSUE TITLE
Update Kafka Client compatibility matrix

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-kafka#823]
The [matrix in the wiki](https://github.com/spring-cloud/spring-cloud-stream/wiki/Kafka-Client-Compatibility) is stale and very outdated. Let's revise it in the lens of the latest Spring Kafka, SI Kafka, and Kafka binder releases perspective.

**Comment by sobychacko** [comment]
The wiki is updated.
