### ISSUE TITLE
Sleuth headers get lost at the KStream output

### ISSUE THREAD

**Issue by JavierGB** [spring-cloud/spring-cloud-stream-binder-kafka#826]
Hello my friends,
I have the following functional style topology:

1. KStream input
2. filter
3. flapMap
4. aggregate
5. filter
6. map
7. KStream output

Input records comes with sleuth headers, but they get lost in the kafka stream.
FlapMap split one record into N Records.
**I need every output record has same sleuth headers that the input record.**
¿ what is the right way to do this ? ¿kafka streams binder has support for this requirement?

Dependency Versions:

- spring-cloud-stream-binder-kafka-streams:3.0.1.RELEASE
- spring-cloud-starter-sleuth:2.2.1.RELEASE

StackOverflow question: https://stackoverflow.com/questions/59635408/sleuth-with-spring-cloud-stream-binder-kafka-streams

thanks

**Comment by sobychacko** [comment]
@JavierGB Is this still a problem in your application? We had some [recent discussion](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/1025) about slueth instrumentation in the binder. Have you found a workaround for your requirements?

**Comment by sobychacko** [comment]
Kafka Streams binder's integration with Spring Cloud Sleuth is documented [here](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/main/docs/src/main/asciidoc/kafka-streams.adoc#tracing-using-spring-cloud-sleuth).  Closing this issue. Feel free to re-open if necessary.
