### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by ncheema** [spring-cloud/spring-cloud-stream-binder-kafka#827]
Kafka binder documentation(`API` and `Doc`) links are broken on [cloud.spring.io](https://cloud.spring.io/spring-cloud-stream-binder-kafka/)

**example of broken links:** 
- https://cloud.spring.io/spring-cloud-stream-binder-kafka/reference/html/
- https://cloud.spring.io/spring-cloud-static/spring-cloud-stream-binder-kafka/3.0.1.RELEASE/reference/html/
- https://cloud.spring.io/spring-cloud-stream-binder-kafka/2.1.x/reference/html/

**Comment by sabbyanandan** [comment]
Thanks for pointing this out, @ncheema! We will get this fixed asap.

**Comment by sabbyanandan** [comment]
Now that I have had a chance to review, we are going to default to the primary [Spring Cloud Stream](https://spring.io/projects/spring-cloud-stream)-site going forward, and the binder-specific sites will be removed. 

The docs for the Kafka-binder can be found from the aggregate docs page: https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/3.0.3.RELEASE/reference/html/
