### ISSUE TITLE
Sporadic `TopicExistsException` at start with 0.10.1.1 cluster

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream-binder-kafka#83]
Using the Kafka binder with a 0.10.1.0 library version pointing at a 0.10.1.1. cluster results in startup failures with:

```
org.springframework.context.ApplicationContextException: Failed to start bean 'outputBindingLifecycle'; nested exception is org.apache.kafka.common.errors.TopicExistsExce
ption: Topic "ticktock.time" already exists.
```

Reproduced by both @trisberg and @sobychacko. 

Note: this could be the possible result of a race condition between two separate applications (producer and consumer) starting simultaneously as it has been observed only in Spring Cloud Data Flow deployments.

**Comment by trisberg** [comment]
So far I have been able to reproduce with a new kafka cluster using versions 0.10.1.0 and 0.10.1.1
