### ISSUE TITLE
Make InteractiveQueryService be able to return all metadata for specific store

### ISSUE THREAD

**Issue by sserhii-95** [spring-cloud/spring-cloud-stream-binder-kafka#833]
The current implementation of InteractiveQueryService provides only one method to retrieve metadata for a specific key, but there is no easy wat to retrieve metadata ща all hosts for a specific store.

It will be useful for cases when we should return data for all or some range of keys from state store without moving this logic out of the service.

It would be great to have something like this.

```java
public class InteractiveQueryService { 
 // ...

/**
 * Gets the list of {@link HostInfo} where the provided store is hosted on. 
 * It also can include current host info.  
 * Kafka Streams will look through all the consumer instances under the same application id 
 * and retrieves all hosts info
 *
 * Note that the end-user applications must provide `applicaiton.server` as a configuration property
 * for all the application instances when calling this method. If this is not available, then the empty list will be returned.
 *
 * @param store store name
 * @return the list of {@link HostInfo} where provided store is hosted on
 */
public List<HostInfo> getAllHostsInfo(String store){
    return kafkaStreamsRegistry.getKafkaStreams()
            .stream()
            .flatMap(k -> k.allMetadataForStore(store).stream())
            .filter(Objects::nonNull)
            .map(StreamsMetadata::hostInfo)
            .collect(Collectors.toUnmodifiableList())
}

```

**Comment by sobychacko** [comment]
@sserhii-95 That sounds like a good idea. Would you be willing to submit a PR with this addition to the `InteractiveQueryService` API? Thank you!

**Comment by sserhii-95** [comment]
@sobychacko please review
https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/854

**Comment by sobychacko** [comment]
This PR addressed this issue: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/854
