### ISSUE TITLE
Backport Kafka auth issue fixes to 2.x.x

### ISSUE THREAD

**Issue by lukasz-kaminski** [spring-cloud/spring-cloud-stream-binder-kafka#835]
Could you please backport GH-831 to 2.0.x, 2.1.x and 2.2.x?

**Comment by sobychacko** [comment]
@lukasz-kaminski We can do the backports on some of those branches. Is there any particular reason why you want it on `2.0.x` and `2.1.x`? `2.0.x` is already `EOL'ed (based on [boot EOL](https://spring.io/blog/2019/02/15/spring-boot-2-1-3-available-now)) and we largely moved on from both `2.0.x` and `2.1.x`. We can certainly do a release for`2.2.x`.

**Comment by lukasz-kaminski** [comment]
We have a lot of apps that use 2.1.x and some using 2.2.x. I've included 2.0.x just because it's also vulnerable to the bug that mentioned PR resolves, but if it's EOL'ed then that's ok.

I would be grateful for 2.1.x and 2.2.x, though :)

**Comment by sabbyanandan** [comment]
Hi, @lukasz-kaminski. Thank you for your contribution! I just wanted to let you know that we will cherry-pick and backport the commit to both 2.1.x and 2.2.x branches. We have plans to cut a point release on 2.2.x shortly afterward. 

As for 2.1.x, however, there's no planned release of Spring Cloud's Greenwich release-train in the future, so we will be on standby, and when there's a scope of an SRx release in the future, we will revisit it. Besides that, the [Boot 2.1.x line is slated for EOL](https://spring.io/blog/2019/12/10/spring-boot-2-1-x-eol-november-1st-2020) later this year.

In the meantime, please try to upgrade to the latest and actively maintained release branches.

**Comment by lukasz-kaminski** [comment]
@sabbyanandan Thank you!

**Comment by sobychacko** [comment]
@lukasz-kaminski @sabbyanandan After doing some analysis, I realized that backporting this fix to `2.2.0` (`Germantown`) is not trivial. This is because Spring Kafka version that is used there is `2.2.x`. The corresponding [authorization changes](https://github.com/spring-projects/spring-kafka/blob/2.3.x/spring-kafka/src/main/java/org/springframework/kafka/listener/ConsumerProperties.java#L321) are not backported to Spring Kafka 2.2.x. It is only introduced in 2.3.5. Why was it not backported there? It needs to be either backported there first and have a release. Or the other option is to patch it on the Kafka binder directly. If you prefer the latter option, feel free to submit separate PR's into both `2.2.x` and `2.1.x` branches of Kafka binder. cc/ @garyrussell

**Comment by lukasz-kaminski** [comment]
> Why was it not backported there?

I guess @garyrussell is more capable of answering that. It would be great if it could be backported to 2.2.x.

**Comment by garyrussell** [comment]
>Why was it not backported there?

Because it was a new feature (i.e. not considered a bug) and we made an exception to backport it to 2.3.x.

We could make another exception, I suppose; but I'd rather not, especially if there is some other workaround.

>Or the other option is to patch it on the Kafka binder directly.

@sobychacko Please explain what you mean by this.

**Comment by sobychacko** [comment]
@garyrussell I meant porting that entire feature somehow to the binder itself in 2.2.x (of the binder). However, after looking through the original PR, I realize that it is not possible to do so without the support from spring kafka. Sorry for the confusion.

**Comment by garyrussell** [comment]
It's a relatively easy backport (although it was not trivial), but I don't see a schedule for Boot 2.1.13 - if you update the binder to use a new 2.2.x spring-kafka version, won't that cause issues with the app starters, since they get their S-K version from boot?

**Comment by sobychacko** [comment]
Ya, without a new Boot version that picks up this new SK release, it will be a problem. However, we have some ways to force a new SK version at the app level, again not a trivial effort with testing etc. @lukasz-kaminski Given that Boot 2.1 is EOL'ed later this year, I wonder if it is worth that we are going through all these efforts to backport these changes to both SCSt and SK?

**Comment by lukasz-kaminski** [comment]
Definitely not, this seems to be too much of a hassle. We'll find a way to make teams upgrade their Boot and Cloud. Nevertheless, thank you for the help and assistance with this :)
