### ISSUE TITLE
Value serde not properly initialized when using @KafkaStreamsStateStore

### ISSUE THREAD

**Issue by adrianotr** [spring-cloud/spring-cloud-stream-binder-kafka#836]
I've noticed an issue when using the `@KafkaStreamsStateStore` annotation, if you use `SpecificAvroSerde` as your `valueSerde`.

Apparently the `KeyValueSerdeResolver.getValueSerde` method does not call the `Serde.configure` method to initialize the Serde object after its creation, unlike the `KeyValueSerdeResolver.getKeySerde` method.

As a result, the value Serde does not have the right Schema Registry url.

**Comment by adrianotr** [comment]
I can create a PR for this, unless there's was a reason for the value serde not to be initialized as opposed to the key serde. Please let me know.

**Comment by olegz** [comment]
@adrianotr you should always create a PR since it would be much simpler to reason about it, polish, improve etc. So yes please do it.
