### ISSUE TITLE
Consider changing the default serdes of @KafkaStreamsStateStore

### ISSUE THREAD

**Issue by adrianotr** [spring-cloud/spring-cloud-stream-binder-kafka#837]
I would like to bring this up for discussion.

`@KafkaStreamsStateStore` currently defaults the `keySerde` and `valueSerde` properties to `org.apache.kafka.common.serialization.Serdes$StringSerde`.

How do we feel about changing it to be the application configured default serde instead? Using String as the default seems like a very big assumption to me.

**Comment by sobychacko** [comment]
@adrianotr Which version of the binder are you using? There is a better way you can control the metadata for state store now directly providing a `StoreBuilder` bean in the application. Take a look here: https://cloud.spring.io/spring-cloud-static/spring-cloud-stream-binder-kafka/3.0.1.RELEASE/reference/html/spring-cloud-stream-binder-kafka.html#_state_store.
Let us know if that satifsfies your requirements.

**Comment by adrianotr** [comment]
Hey @sobychacko, thanks for the quick response.

I am using version '2.2.2.RELEASE'.

I tried to use the StoreBuilder bean, but because I have multiple topologies defined in this project I noticed it ends up creating and assigning one state store for each @StreamListener.

It would be great if I could specify which method should use the builder, like:

```
    @StreamListener
    @KafkaStreamsStateStore(storeBuilder = "myStoreBuilder")
    public void process(...) {
        ....
    }

    @Bean
    public StoreBuilder myStoreBuilder() {
        ...
    }

What do you think of that idea?
```

**Comment by sobychacko** [comment]
@adrianotr Sure, that can be done. Generally speaking, we are discouraging the use of the `KafkaStreamsStateStore` annotation on non `StreamListener` methods starting with 3.x. Since you are on `2.2.x` and using `StreamListener`, I think what you are suggesting is doable. Do you want to work on a pull request with the changes and contribute to the project? Then we can review the changes.

**Comment by adrianotr** [comment]
Sure, I can contribute.

I also prefer the StoreBuilder solution to the annotation.

But we need a way to qualify the state stores and apply them to the right topologies for projects with more than one @StreamListener method.

We'll have to come up with a few design decisions before we implement a solution.

1) Should we use the existing @KafkaStreamsStateStore annotation or create a new one?

2) What about the existing behaviour of binding the state store to all topologies? Should that be changed? If not, how should we keep backwards compatibility?

We can think of different ways to do that, but the example above is the most intuitive way I could think of so far.

I'm looking forward to hearing what you think.

**Comment by sobychacko** [comment]
@adrianotr I think the fact that the state store getting assigned to all the topologies in an application is a side effect. As long as we provide a way to attach that to a particular topology, that should be backward compatible. With that said, starting with the 3.0 release, Kafka Streams binder largely promotes the functional model of writing a processor as opposed to `StreamListener`, but `StreamListener` is still supported. We suggest adding any new feature level changes to the new model. Please keep that in mind when you work on the PR.

**Comment by adrianotr** [comment]
@sobychacko Ok, so for a backwards compatible implementation I could try to implement something like:

```
    @StreamListener
    @MyTopology
    public void process(...) {
        ...
    }
    
    @Bean
    @MyTopology
    public StoreBuilder<?> buildStore() {
        ...
    }

    @Qualifier
    @Retention(RUNTIME)
    public @interface MyTopology {}

```

**Comment by sobychacko** [comment]
Sounds good. If you can start with a basic PR, then we can start reviewing it and incrementally add further changes to it.

**Comment by sobychacko** [comment]
@adrianotr Any update on this issue? Did you get a chance to work on this yet? Please let us know. If you can't get to it, we can try to come up with some solution.

**Comment by sobychacko** [comment]
@adrianotr As using the functional model for writing Kafka Streams binder based applications is the norm now, I think we can close this issue. Moreover, we are deprecating `StreamListener` in the `3.1.0` version of Spring Cloud Stream core in preference to the functional model.  I think providing a `StoreBuilder` bean in the application and customizing it is the way to go to address your original use case (granted that you can convert your `StreamListener` based processors to `Function` based ones). I will leave this issue open for a few more days before closing it.

**Comment by sobychacko** [comment]
@adrianotr Closing the issue. Please feel free to re-open if you still have a need for this use case.
