### ISSUE TITLE
spring-integration-kafka included twice

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-stream-binder-kafka#85]
https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka/pom.xml#L40

and

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka/pom.xml#L64

**Comment by mbogoevici** [comment]
Thanks @dsyer. This is likely innocuous as spring-integration-kafka has no dependency on Avro anymore (since 2.x), but this is wrong and we should fix.
