### ISSUE TITLE
branch method publishes to only one topic

### ISSUE THREAD

**Issue by sumitbaurai** [spring-cloud/spring-cloud-stream-binder-kafka#852]
Hi, 

I have a requirement to publish the same stream to two topics ( one of the topics is compacted whereas the other is not). To accomplish this I created two predicates that always return true. 

```
Predicate<String,S_LIQ_FFD> pushtoDataTopic = (s, s_liq_ffd) -> true;

 Predicate<String,S_LIQ_FFD> pushtoEventTopic = (s, s_liq_ffd) -> true;
```

However, when I try to use the same in my branch like this
`.branch(pushtoDataTopic, pushtoEventTopic);`

with `@SendTo({"output-2", "output-1"})`

and     
 ```
  @Output("output-1")
        KStream<String, S_LIQ_FFD> PushToDataTopic();
        @Output("output-2")
        KStream<String, S_LIQ_FFD> PushToEventTopic();
```

only the first output binding in `@SendTo` is receiving the message. I tried to turn around the order there and verified this as well.

**Comment by sumitbaurai** [comment]
I just tested this without the spring kafka streams binder via just kafka streams api and observe that the behaviour is the same....

**Comment by sobychacko** [comment]
@sumitbaurai That is how Kafka Streams branching works in general. The first matched predicate will win. If you have to send this to multiple topics at one, you probably have to programmatically send them using the `to` method. We will explore further, if we can relax it from the binder perspective. Thank you!
