### ISSUE TITLE
Metrics Issue with Multiple Consumer Threads and Partitions

### ISSUE THREAD

**Issue by 16chlj48** [spring-cloud/spring-cloud-stream-binder-kafka#862]
**PROBLEM**: consumer_fetch_manager_metrics_records_consumed_total (The total number of records consumed) is incorrect. It chooses one consumer thread rather than the sum of all the threads. Most of the time, Thread-1 is chosen and displayed only - even when there are messages in other consumer threads

I created a small project to show what is happening with the metrics.

**Steps to recreate**:
1) Start Kafka and Zookeeper
2) Run This App
[cloud_demo1.zip](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/files/4319251/cloud_demo1.zip)

Make sure there are multiple partitions in the input and output topic. This project has a default setup for 12 partitions and 4 consumer threads.

To verify the number of partitions in each topic:
```
bin/kafka-topics.sh --describe --bootstrap-server localhost:9092 --describe --topic input
bin/kafka-topics.sh --describe --bootstrap-server localhost:9092 --describe --topic output
```
If there are not multiple partitions, add them in manually:
```
./bin/kafka-topics.sh --bootstrap-server localhost:9092 --alter --topic input --partitions 12
./bin/kafka-topics.sh --bootstrap-server localhost:9092 --alter --topic output --partitions 12
```

3) Produce key:value message to topic input using different partitions:

`kafkacat -P -b localhost:9092 -K: -t input -p4`
Key-1:Message-1
Key-2:Message-2
`kafkacat -P -b localhost:9092 -K: -t input -p9`
Key-3:Message-3
Key-4:Message-4
Key-5:Message-5

The application console should output:
Key: Key-1        Value: Message-1        Message Count: 1
Key: Key-2        Value: Message-2        Message Count: 2
Key: Key-3        Value: Message-3        Message Count: 3
Key: Key-4        Value: Message-4        Message Count: 4
Key: Key-5        Value: Message-5        Message Count: 5

4) Show all messages in the output topic with formatting (partition, key, value)
`kafkacat -b localhost:9092 -t output -o beginning -f "%p %k %s\n"`
5) Locate the prometheus endpoint: http://localhost:9000/actuator/prometheus

**EXAMPLE 1**:

kafka_consumer_records_consumed_total_records_total{client_id="StreamInputProcessor-process-applicationId-13a8d7a2-1550-4399-9fc3-1a9ab02fd725-StreamThread-1-consumer",topic="input",} 2.0
kafka_consumer_records_consumed_total_records_total{client_id="StreamInputProcessor-process-applicationId-13a8d7a2-1550-4399-9fc3-1a9ab02fd725-StreamThread-3-consumer",topic="input",} 0.0
kafka_consumer_records_consumed_total_records_total{client_id="StreamInputProcessor-process-applicationId-13a8d7a2-1550-4399-9fc3-1a9ab02fd725-StreamThread-2-consumer",topic="input",} 0.0
kafka_consumer_records_consumed_total_records_total{client_id="StreamInputProcessor-process-applicationId-13a8d7a2-1550-4399-9fc3-1a9ab02fd725-StreamThread-4-consumer",topic="input",} 5.0

consumer_fetch_manager_metrics_records_consumed_total{client_id="StreamInputProcessor-process-applicationId-13a8d7a2-1550-4399-9fc3-1a9ab02fd725-StreamThread-1-consumer",} **2.0**

**EXAMPLE 2:**

kafka_consumer_records_consumed_total_records_total{client_id="StreamInputProcessor-process-applicationId-8d47c1a2-4cd2-4305-a16c-228f35b28004-StreamThread-1-consumer",topic="input",} 0.0
kafka_consumer_records_consumed_total_records_total{client_id="StreamInputProcessor-process-applicationId-8d47c1a2-4cd2-4305-a16c-228f35b28004-StreamThread-4-consumer",topic="input",} 3.0
kafka_consumer_records_consumed_total_records_total{client_id="StreamInputProcessor-process-applicationId-8d47c1a2-4cd2-4305-a16c-228f35b28004-StreamThread-3-consumer",topic="input",} 0.0
kafka_consumer_records_consumed_total_records_total{client_id="StreamInputProcessor-
process-applicationId-8d47c1a2-4cd2-4305-a16c-228f35b28004-StreamThread-2-consumer",topic="input",} 2.0

consumer_fetch_manager_metrics_records_consumed_total{client_id="StreamInputProcessor-process-applicationId-8d47c1a2-4cd2-4305-a16c-228f35b28004-StreamThread-1-consumer",} **0.0**

Note: kafka_consumer_records_consumed_total_records_total shows the correct number of messages for each consumer. Please reference this and the application output console when fixing consumer_fetch_manager_records_consumed_total

**Comment by sobychacko** [comment]
@16chlj48 Thank you for the very detailed explanation and the demo app attached. I ran your app and saw the issue. You are using `Hoxton.SR1` which brings Spring Cloud Stream `Horsham.SR1`. We made some changes to the metrics code since then. I upgraded your app to use `Hoxton.SR3`. Then I am seeing the correct total for `consumer_fetch_manager_metrics_records_consumed_total`. Could you verify it? You can either update your spring cloud dependency to `Hoxton.SR3` or the following dependency itself to the latest release (`3.0.3.RELEASE`). 
```
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-stream-binder-kafka-streams</artifactId>
	<version>3.0.3.RELEASE</version>
</dependency>
```

**Comment by 16chlj48** [comment]
@sobychacko I just tried it with the upgrades and it worked for me. Thank you!
