### ISSUE TITLE
Manual commit - acknowledge() returns void and CommitFailedException happens after acknowledge() has already been called

### ISSUE THREAD

**Issue by jskim1991** [spring-cloud/spring-cloud-stream-binder-kafka#864]
Hello,

I am currently trying to write some code to prevent duplicate processing on the consumer side as mentioned in #858.

> On the consumer side, there are no exactly once guarantees; you are on your own to implement idempotency; but this is relatively easy, just store the topic/partition/offset along with the data and check that you haven't already processed this record. The topic/partition/offset are available in the Message<?> headers.

So I am implementing using manual commit.
As per spring cloud stream kafka binder documentation, I am doing something very similar:
```
 @StreamListener(Sink.INPUT)
 public void process(Message<?> message) {
     Acknowledgment acknowledgment = message.getHeaders().get(KafkaHeaders.ACKNOWLEDGMENT, Acknowledgment.class);
     if (acknowledgment != null) {
         System.out.println("Acknowledgment provided");
         acknowledgment.acknowledge();
     }
 }
```

When I am debugging (on IDE) through my `@StreamListener` and manual acking, I sometimes see `CommitFailedException` due to rebalancing some time after `acknowledgement.acknowledge()` has already been stepped through. I know that `CommitFailedException` is related to configuration such as `max.poll.interval.ms` and others. I am going to set proper configs. But at the same time, I want to be able to handle this in code as well. And I am not using `batch-mode`, so I am processing 1 record at a time.

Knowing that `acknowledge()` method returns void, Is it possible to catch Exceptions that happen during/after `acknowledge()` ?

I think it would be nice and easy to do something like
```
try {
   ack.acknowledge();
}
catch (Exception e) {
    ... handle exception ...
}
```

**Comment by garyrussell** [comment]
This is already supported.

Add a `ListenerContainCustomizer` bean:

```java
	@Bean
	public ListenerContainerCustomizer<ConcurrentMessageListenerContainer<?, ?>> cust() {
		return (container, destination, group) -> 
			container.getContainerProperties().setAckMode(AckMode.MANUAL_IMMEDIATE);

	}
```

The commit will be performed on the calling thread and you can catch any exeptions; see the javadocs for `KafkaConsumer.commitSync()`.

The container property `syncCommits` is true by default.

**Comment by jskim1991** [comment]
@garyrussell thanks for your input. I am trying the code you provided but with spring cloud stream kafka's autoCommitOffset: false, ackMode is still MANUAL. I checked by putting a breakpoint in ContainerProperties.java line 261.

**Comment by garyrussell** [comment]
The customizer is applied here

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/65f8cc5660183317d61c66baa7fb9c26676280f8/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java#L691

**Comment by jskim1991** [comment]
@garyrussell I was still seeing CommitFailedException after stepping through try-catch statement for acknowlegde() though. I will try to create a sample and share.

**Comment by garyrussell** [comment]
My mistake; sorry, it's

```java
	@Bean
	public ListenerContainerCustomizer<AbstractMessageListenerContainer<?, ?>> cust() {
		return (container, destination, group) ->
			container.getContainerProperties().setAckMode(AckMode.MANUAL_IMMEDIATE);

	}
```

**Comment by jskim1991** [comment]
@garyrussell here is my sample I have been testing all day just for reference.
https://github.com/jskim1991/kafka-test-manual-commit/tree/master

**Comment by jskim1991** [comment]
@garyrussell Using AbstractMessageListenerContainer allows me to catch exceptions after calling acknowledge().
