### ISSUE TITLE
DefaultAfterRollbackProcessor retries are not limited to 10 by default

### ISSUE THREAD

**Issue by jskim1991** [spring-cloud/spring-cloud-stream-binder-kafka#866]
Hello,
I am trying to find a way to set a number of retries for Kafka consumers.
Without transactional.id, I was able to control it by setting max-attempts in RetryTemplate. However, when using transaction-id-prefix, I cannot seem to control max-attempts per channel.

Looking at the spring-kafka doc, by default DefaultAfterRollbackProcessor retries 10 times.
`
Starting with version 2.2, the DefaultAfterRollbackProcessor can now recover (skip) a record that keeps failing. By default, after ten failures, the failed record is logged (at the ERROR level). You can configure the processor with a custom recoverer (BiConsumer) and maximum failures. Setting the maxFailures property to a negative number causes infinite retries.
`

However, when I actually test it, it seems to retry more than 10 times.
My [code](https://github.com/jskim1991/kafka-test-manual-commit) is here: 

Steps on how to reproduce:
1. Start Zookeeper
2. Start Kafka
3. Produce an event to the topic named 'test-topic' (use console producer like
     $ ./kafka-console-producer.sh --broker-list localhost:9092 --topic test-topic )
4. Let @StreamListener do the work (it will result in CommitFailedException, so it will retry)
5. On the console, look for 'log this message'. There will be more than 10 tries.

My question is this
1. This behavior seems different compare to the document. Which one is the intended result?
2. Based on my business requirements, I need to set max retries per channel. How can this be done when using transaction-id-prefix? I prefer doing it in application.yml in spring-cloud-stream-binder-kafka way (global max-attempts as well as overriding per channel) rather than within the code.

**Comment by garyrussell** [comment]
When using transactions, you should disable retry in the binder (`max-attempts: 1`). Otherwise you'll get 30 attempts. (10x3).

**Comment by jskim1991** [comment]
@garyrussell does that mean if I want to set retries per channel, I have to go in multiples of 10? Would that be the only possible option?

**Comment by garyrussell** [comment]
You can configure a custom `AfterRollbackProcessor` with a different number of attempts to the default (10). However, container-based retries are applied to all channels; you can't set a different value for each channel.

**Comment by garyrussell** [comment]
Let me correct that - you can indeed configure a different AfterRollbackProcessor for each channel; the `ListenerContainerCustomizer`bean is provided with the destination name and and group.

**Comment by jskim1991** [comment]
@garyrussell Could you please share a sample of `ListenerContainerCustomizer` and also, what could possibly go wrong by setting max-attempts for each channel assuming retry happens max-attempts * 10 times? 
If I remember correctly from #858 , transactions do not use RetryTemplate but based on your comment, it does make use of max-attempts?

Overriding such bean would be very burdening when a user has many different topic-channel bindings

**Comment by garyrussell** [comment]
Sorry, you are correct; the `max-attempts` is used to configure the default ARP and should override the default 10. 

I will take a look at your project to see why you are getting too many retries.

BTW, this would be how you could configure a DARP for each channel, but it should not be necessary because the retry properties should be used.


```java
	@Bean
	public ListenerContainerCustomizer<AbstractMessageListenerContainer<?, ?>> cust() {
		return (container, destination, group) -> container.setAfterRollbackProcessor(
				new DefaultAfterRollbackProcessor<>(new FixedBackOff(1000L, 3L)));

	}
```

**Comment by jskim1991** [comment]
@garyrussell 

> Sorry, you are correct; the max-attempts is used to configure the default ARP and should override the default 10.

> BTW, this would be how you could configure a DARP for each channel, but it should not be necessary because the retry properties should be used.

So `max-attempts` can be configured per channel. Do I have to take into account that max retries will be `max-attempts` * 10 still?

**Comment by garyrussell** [comment]
No; that was my mistake; sorry the default (10) is not used; the binder builds a DARP based on the retry properties.

**Comment by garyrussell** [comment]
So, after testing your application, the retry will work for **user exceptions** but not for just this one exception (commit failed due to rebalance).

>Caused by: org.apache.kafka.clients.consumer.CommitFailedException: Commit cannot be completed since the group has already rebalanced and assigned the partitions to another member. This means that the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time message processing. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records.

Since a rebalance occurred, the same record will be redelivered when the partition is re-assigned to us (or another instance).

So I believe this is working as expected. We should never "lose" a record simply due to a rebalance (or several rebalances).

**Comment by jskim1991** [comment]
@garyrussell 

just to make sure if I understand you correctly,

> the retry will work for user exceptions

this means it will retry up to `max-attempts` for user exceptions.

> but not for just this one exception (commit failed due to rebalance

because we don't want to lose any record, re-seek is happening which is the expected outcome.

> the DefaultAfterRollbackProcessor can now recover (skip) a record that keeps failing. By default, after ten failures, the failed record is logged (at the ERROR level)

Is this still true then?

**Comment by garyrussell** [comment]
>Is this still true then? 

No; with the binder, the retry properties will be used instead of the default (10).

>re-seek is happening which is the expected outcome.

There is no re-seek in this case (when retries are exhausted) it is simply that the offset was not committed so the record is redelivered after the partition is re-assigned.

**Comment by garyrussell** [comment]
However, there is a bug, when using transactions, we shouldn't be calling `commitSync()` on the consumer at all, we should be sending the offset to the transaction (in which case, I don't think the `acknowledge()` will get an exception; the exception will occur when the transaction is committed.

We never really planned for using manual acks with transactions.

**Comment by garyrussell** [comment]
Having fixed the bug; I see two behaviors:

- if there is only one instance of the application, the offset is sent successfully to the transaction and it commits ok
- if there is another instance of the application, it is assigned the partition and the `acknowledge()` call fails with a `ProducerFencedException` as expected.

**Comment by jskim1991** [comment]
@garyrussell 
> We never really planned for using manual acks with transactions.

See I think I am in a very stuck situation.
All I need is at-least once consumer. 

Assuming there are 3 sets of data in my topic and my consumer will process `a -> b -> c`, something bad happened so that CommitFailedException happened.
In my sample code, the good thing for me that you mentioned was

> So, after testing your application, the retry will work for user exceptions but not for just this one exception (commit failed due to rebalance).

because it will just retry on `a` until it is good again.

If you were to run that sample app without `transaction-id-prefix` and consumer `isolation.level`, you will see it will 
1. receive `a` and retry up to `max-attempts`
2. receive `b` and retry up to `max-attempts`
3. receive `c` and retry up to `max-attempts`
4. goes back to `a` and repeats 1~3. I m guessing this is where it does poll() again seeing `Re-)joining group` and `Successfully joined group with generation 7` in the app logs. And if things are good here, it will start process and send acks sequentially.

I think in this case, retry on `CommitFailedException` should stay at step 1 like it is happening when using `transaction-id-prefix`. Going through 2 and 3 would be dangerous in terms of data consistency.

**Comment by garyrussell** [comment]
When not using transactions, add a `SeekToCurrentErrorHandler` to the container.

Then, when `a` fails, we discard `b` and `c` and re-fetch a, b, c on the next poll.

**Comment by jskim1991** [comment]
@garyrussell that seems like what I been missing.

> configure the error handler with 0 retries to use the max-attempts via retry instead.

This would be ideal for me. I m guessing it would look like below:

```
SeekToCurrentErrorHandler errorHandler =
    new SeekToCurrentErrorHandler((record, exception) -> {
       
    }, new FixedBackOff(0L, 0L));
```

I will give it a shot.
Once I am all sorted out on these, I would love to enhance documentation.

**Comment by garyrussell** [comment]
Yes; that's correct.

>Once I am all sorted out on these, I would love to enhance documentation.

Sounds good; thanks.

**Comment by jskim1991** [comment]
Thank you for your help. I was able to verify that it is not a bug. And also, I learned how to use max-attempts and SeekToCurrentHandler. I will close it for now and I hope to contribue to improve documentation for other people.
