### ISSUE TITLE
Example in the Doc yields Exception

### ISSUE THREAD

**Issue by FrankR85** [spring-cloud/spring-cloud-stream-binder-kafka#867]
According to the docs `2.13.1`one could use to register a `globalStateStore`:
```
@Bean
public StreamsBuilderFactoryBeanCustomizer customizer() {
    return fb -> {
        try {
            final StreamsBuilder streamsBuilder = fb.getObject();
            streamsBuilder.addGlobalStore(...);
        }
        catch (Exception e) {

        }
    };
}
```
However, calling `fb#getObject` yields `org.springframework.beans.factory.FactoryBeanNotInitializedException: org.springframework.kafka.config.StreamsBuilderFactoryBean does not support circular references`

**Comment by sobychacko** [comment]
@FrankR85 I just tried a simple boot application and the factory bean is resolving fine. See below.

![image](https://user-images.githubusercontent.com/827682/77127110-b61c6280-6a21-11ea-82dc-594507060fec.png)

Can you describe how we can reproduce what you are seeing?

**Comment by FrankR85** [comment]
Very strange. I can't reproduce it also anymore!? Closing this therefore. Thank you for your effort!
