### ISSUE TITLE
Kakfa message is committed before database transaction

### ISSUE THREAD

**Issue by santhoshpt** [spring-cloud/spring-cloud-stream-binder-kafka#869]
I could not make spring-cloud-stream-binder-kafka work for following use case:

 Start @transaction (Rest controller)
         DB update/inserts
         Send Kafka message

Before the transaction is committed, the consumer (configured with @EnableBinding and @StreamListener) is able to read the record.  This consumer is already configured with read_committed isolation level.

I'm not sure is it an issue or any configuration from my sidel

**Comment by garyrussell** [comment]
Have you set `isolation.level=read_committed` on the consumer?

By default, consumers can see uncommitted records.

**Comment by santhoshpt** [comment]
Yes.  the read_committed setting is present before and after upgrade.  Having the following solved the issue.  But, I'm not sure how was it working in spring boot 2.1.11.

 ```
 @Bean(name = "chainedTransactionManager")
  @Primary
  public PlatformTransactionManager chainedTransactionManager(JpaTransactionManager jpaTM,
      BinderFactory binders) {
    Binder<MessageChannel, ?, ?> binder = binders.getBinder("kafka", MessageChannel.class);
    if (binder instanceof KafkaMessageChannelBinder) {
      ProducerFactory<byte[], byte[]> pf =
          ((KafkaMessageChannelBinder) binder).getTransactionalProducerFactory();
      KafkaTransactionManager<byte[], byte[]> ktm = new KafkaTransactionManager<>(pf);
      ktm.setTransactionSynchronization(
          AbstractPlatformTransactionManager.SYNCHRONIZATION_ON_ACTUAL_TRANSACTION);
      return new ChainedKafkaTransactionManager<Object, Object>(jpaTM, ktm);
    } else {
      return jpaTM;
    }
  }
```

**Comment by garyrussell** [comment]
Sorry for the delay in replying. I am not sure what you changed, you didn't show the before/after, but...

>`return new ChainedKafkaTransactionManager<Object, Object>(jpaTM, ktm);`

will commit the Kafka transaction first. See `ChainedTransactionManager`.

- `beginTransaction` is executed on the tm list (`jpaTM, ktm`) left-to-right
- `commitTransaction` and `abortTransaction` is executed on the tm list right to left:

```java
		for (PlatformTransactionManager transactionManager : reverse(transactionManagers)) {

			if (commit) {
...
```
(notice the `reverse` call).

However, you don't really need a `ChainedKafaTransactionManager` for this use case, you can just use normal transaction synchronization to synchronize the Kafka transaction with the JPA transaction. See this test case:

```java
	@Test
	public void testTransactionSynchronization() {
		MockProducer<String, String> producer = spy(new MockProducer<>());
		producer.initTransactions();

		@SuppressWarnings("unchecked")
		ProducerFactory<String, String> pf = mock(ProducerFactory.class);
		given(pf.transactionCapable()).willReturn(true);
		given(pf.createProducer(isNull())).willReturn(producer);

		KafkaTemplate<String, String> kafkaTemplate = new KafkaTemplate<>(pf);
		kafkaTemplate.setDefaultTopic(STRING_KEY_TOPIC);

		class DummyTM extends AbstractPlatformTransactionManager {

			@Override
			protected Object doGetTransaction() throws TransactionException {
				return new Object();
			}

			@Override
			public void doBegin(Object transaction, TransactionDefinition definition) throws TransactionException {
			}

			@Override
			public void doCommit(DefaultTransactionStatus status) throws TransactionException {
			}

			@Override
			protected void doRollback(DefaultTransactionStatus status) throws TransactionException {
			}

		}

		DummyTM tm = spy(new DummyTM());

                // Transaction could be started with @Transactional instead
		new TransactionTemplate(tm)
				.execute(s -> {
					kafkaTemplate.sendDefault("foo", "bar");
					return null;
				});

		assertThat(producer.history()).containsExactly(new ProducerRecord<>(STRING_KEY_TOPIC, "foo", "bar"));
		assertThat(producer.transactionCommitted()).isTrue();
		assertThat(producer.closed()).isTrue();

		InOrder inOrder = inOrder(producer, tm);
		inOrder.verify(tm).doBegin(any(), any());
		inOrder.verify(producer).beginTransaction();
		inOrder.verify(tm).doCommit(any());
		inOrder.verify(producer).commitTransaction();
	}
```

**Comment by santhoshpt** [comment]
Thanks @garyrussell.  I was not sure there is no code chance I just upgraded the dependencies and I see the side effect.  Its very long.  Let me test once.   

So I need to change the sequence so that first JPA transaction will be committed and later kafka.

**Comment by sabbyanandan** [comment]
Closing this due to no activit.
