### ISSUE TITLE
Spring Cloud Stream default config for manual commit does not work as described in the doc

### ISSUE THREAD

**Issue by jskim1991** [spring-cloud/spring-cloud-stream-binder-kafka#876]
Looking at the reference for Kafka Consumer properties and autoCommitOffset

> To avoid repetition, Spring Cloud Stream supports setting values for all channels, in the format of spring.cloud.stream.default.property=value.

> autoCommitOffset: When this property is set to false, Kafka binder sets the ack mode to org.springframework.kafka.listener.AbstractMessageListenerContainer.AckMode.MANUAL and the application is responsible for acknowledging records

However, if you set `autoCommitOffset` to false using `spring.cloud.stream.default.consumer.autoCommitOffset` to false, the container runs using `AckMode.BATCH` and `Acknowledgement` is null in `Message<?>` headers.

sample: https://github.com/jskim1991/kafka-binder-default-config-test
![스크린샷 2020-04-02 오후 11 11 36](https://user-images.githubusercontent.com/17305081/78260062-7cc31700-7538-11ea-8144-5c11619ec9b2.png)
![스크린샷 2020-04-02 오후 11 11 48](https://user-images.githubusercontent.com/17305081/78260076-80ef3480-7538-11ea-878d-297e5578553e.png)

**Comment by garyrussell** [comment]
`spring.cloud.stream.default....`

Should be

`spring.cloud.stream.kafka.default....`

**Comment by jskim1991** [comment]
@garyrussell `spring.cloud.stream.kafka.default` works. Seems like there is some work needed for updating the reference doc. Thanks!!
