### ISSUE TITLE
Deprecate/Rename autoCommitOffset - much confusion with enable.auto.commit

### ISSUE THREAD

**Issue by jskim1991** [spring-cloud/spring-cloud-stream-binder-kafka#877]
Looking at binder reference

> autoCommitOffset
The following properties are available for Kafka consumers only and must be prefixed with spring.cloud.stream.kafka.bindings.channelName.consumer..
...
Default: true.

Looking at spring-kafka reference
> Starting with version 2.3, the framework sets enable.auto.commit to false unless explicitly set in the configuration. Previously, the Kafka default (true) was used if the property was not set.

When using Spring Boot 2.2.5.RELEASE and Spring Cloud Hoxton.SR3, somehow `enable.auto.commit` seems to be always false

![스크린샷 2020-04-02 오후 11 27 40](https://user-images.githubusercontent.com/17305081/78261472-3e2e5c00-753a-11ea-98d4-65f7b78c0a90.png)
![스크린샷 2020-04-02 오후 11 26 06](https://user-images.githubusercontent.com/17305081/78261475-3ff81f80-753a-11ea-9508-b1ddd0810475.png)

**Comment by garyrussell** [comment]
They are different properties, unfortunately.

`autoCommitOffset` is a binder property that controls the container's ack mode.

`auto.commit.offset` is a Kafka consumer property which we always disable by default because we prefer to reliably manage the offsets by the container (or use code) rather than have the kafka-clients commit them in an indeterminate manner.

The name of the binder property is unfortunate.

**Comment by jskim1991** [comment]
@garyrussell due to the name, I have always thought that `autoCommitOffset` was a binder property which controls the Kafka consumer property `enable.auto.commit`. Thanks for the clarification.

**Comment by garyrussell** [comment]
Sorry, I had a typo in my answer.

I understand the confusion.

I think we should deprecate `autoCommitOffset` and allow direct control of the container `ackMode` via a property.

@sobychacko WDYT?

**Comment by sobychacko** [comment]
@garyrussell That sounds like a good idea to me. The binder property `autoCommitOffset` is always a source of confusion as it implies a Kafka property. We can deprecate that use `ackMode` as you suggested. Reopening the issue to track that. Thanks.
