### ISSUE TITLE
Allow the configuration of the Kafka producer close timeout

### ISSUE THREAD

**Issue by codependent** [spring-cloud/spring-cloud-stream-binder-kafka#891]
Context about this issue on StackOverflow: https://stackoverflow.com/questions/61205629/extremely-slow-startup-of-a-spring-cloud-stream-kafka-application-when-using-ena

**Comment by sobychacko** [comment]
Addressed through https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/f7767842932d0235d934b54541ac691a7023cc3f
