### ISSUE TITLE
StateStore Beans will only be added to function bindings having at least one KStream parameter

### ISSUE THREAD

**Issue by thake** [spring-cloud/spring-cloud-stream-binder-kafka#897]
I tried to create a function kafka stream binding that only uses KTable parameters. This kafka stream binding uses state stores configured with a `@Bean` annotation. This failed with a TopologyException due to missing the state store configured with the `@Bean` annotation.

By further debugging the application I noticed that AbstractKafkaStreamsBinderProcessor#addStateStoreBeans will only be called for a function binding if at least one parameter is a KStream (see line 249 KafkaStreamsFunctionProcessor#adaptAndRetrieveInboundArguments (version: 3.1.0.M1).

Should this use case be supported by the kafka streams binder?

**Comment by sobychacko** [comment]
@thake You are right. It's not calling `addStateStoreBeans` for table bindings. We will fix it. Thanks for pointing this out.

**Comment by sobychacko** [comment]
Addressed through https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/01caf3ae9b03432384b2924097324c8ea361553f
