### ISSUE TITLE
stream-binder-kafka 3.0.3 and spring kafka2.3.4.releasse conflict in Haxton.M3 release train

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-kafka#898]
@homerlsy commented on [Fri May 15 2020](https://github.com/spring-cloud/spring-cloud-stream/issues/1969)

in KafkaMessageChannelBinder 

```
MessageProducer createConsumerEndpoint(
			final ConsumerDestination destination, final String group,
			final ExtendedConsumerProperties<KafkaConsumerProperties> extendedConsumerProperties)

```
we are calling 
`containerProperties.setAuthorizationExceptionRetryInterval(this.configurationProperties.getAuthorizationExceptionRetryInterval());`

the method doesn't exist on `ContainerProperties`

**Comment by sobychacko** [comment]
@homerlsy You are using `Hoxton.M3` by the title of the issue. Can you update to the latest `Hoxton` release? (`Hoxton.SR4`). You are most likely using an older Spring Kafka version. Try upgrading to the latest `Hoxton` and see if that fixes the issue. I am closing this issue now, but feel free to re-open if you are still facing difficulties running it.
