### ISSUE TITLE
Spring Core null version

### ISSUE THREAD

**Issue by Mwea** [spring-cloud/spring-cloud-stream-binder-kafka#9]
I got this problem on each project from spring cloud... Is there any solution ? 
For artifact {org.springframework:spring-core:null:jar}: The version cannot be empty

Thanks

**Comment by mbogoevici** [comment]
Closing this as it is most likely related to the Maven version: see http://stackoverflow.com/questions/39620099/springcloudstream-failing-on-spring-core-version for details.
