### ISSUE TITLE
KafkaMessageChannelBinder DlqProducer doesn't work with SSL

### ISSUE THREAD

**Issue by trainings** [spring-cloud/spring-cloud-stream-binder-kafka#90]
A minimal set of properties for Kafka Producer:
`Map<String, Object> props = new HashMap<>();
props.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, this.configurationProperties.getKafkaConnectionString());
props.put(ProducerConfig.RETRIES_CONFIG, 0);
props.put(ProducerConfig.BATCH_SIZE_CONFIG, 16384);
						props.put(ProducerConfig.LINGER_MS_CONFIG, 1);
						props.put(ProducerConfig.BUFFER_MEMORY_CONFIG, 33554432);
						props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, ByteArraySerializer.class);
						props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, ByteArraySerializer.class);
						DefaultKafkaProducerFactory<byte[], byte[]> defaultKafkaProducerFactory =
								new DefaultKafkaProducerFactory<>(props);
						this.dlqProducer = defaultKafkaProducerFactory.createProducer();
`

**Comment by sabbyanandan** [comment]
Duplicates #58.
