### ISSUE TITLE
Consuming Batch documentation error

### ISSUE THREAD

**Issue by RobertoMatas** [spring-cloud/spring-cloud-stream-binder-kafka#902]
Hi,

under Consuming Batch section there is a "typo" error. It refers to control the size of the batch using 3 properties, but one is wrong and can be quite hard to discover it: 
When it says `min.fetch.bytes`, it should say `fetch.min.bytes`

Happy to make a pull request.

**Comment by sobychacko** [comment]
@RobertoMatas Thank you for spotting that. Yes, please make a PR.

**Comment by sobychacko** [comment]
Resolved through https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/af5778d157f54520cdeb71cc5c109b58dd33793b.
