### ISSUE TITLE
Micrometer Meters Missing with Boot 2.3

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-stream-binder-kafka#914]
Boot 2.3 switched from JMX scraping to native Micrometer meters in 2.3.

This is facilitated by adding a listener to the producer/consumer factory.

Since the binder creates its own factories; these meters are now missing.

https://stackoverflow.com/questions/62292889/kafka-consumer-metrics-gone-upon-upgrade-from-spring-boot-2-2-2-to-2-3-0

**Comment by blacksab** [comment]
We are also seeing this issue. 

The fix provided was for metrics to appear when spring-kafka is on the classpath. Our classpath does not have spring-kafka. It has:

`
+--- org.apache.kafka:kafka-streams:2.6.0
|    +--- org.apache.kafka:kafka-clients:2.6.0
`

We also set spring.jmx.enabled=true

Any suggestions as to getting the metrics back?

**Comment by garyrussell** [comment]
This was fixed in Boot 2.3.2 https://github.com/spring-projects/spring-boot/pull/21921

**Comment by garyrussell** [comment]
Boot only does auto configuration when spring-kafka is present.

**Comment by blacksab** [comment]
Thanks, @garyrussell. 

We ended up manually binding our KafkaStreams to the Micrometer registry.

```java
private void bind(
      org.apache.kafka.streams.KafkaStreams kafkaStreams, 
      io.micrometer.core.instrument.MeterRegistry meterRegistry
  ) {
    new KafkaStreamsMetrics(
        kafkaStreams,
        defaultTagSet()
    ).bindTo(
        meterRegistry
    );
  }
```

**Comment by dlipofsky** [comment]
I encountered this too, and I tried adding `org.springframework.kafka:spring-kafka:2.7.9` to my classpath but it did not help. In my case I am moving from SpringBoot 2.1.18 to 2.5.7, micrometer 1.6.9 to 1.7.6, and kafka 2.8.0 to 2.8.1.

**Comment by sobychacko** [comment]
@dlipofsky This is a closed issue. Could you please create a new issue and link to this one? Please provide more context as to what is not working, sample code, configuration, etc. Thanks!

**Comment by dlipofsky** [comment]
@sobychacko since it is closed, is there a solution? There's no milestone, and I was hoping someone on this thread would tell me what the actual fix is.

**Comment by sobychacko** [comment]
It was fixed before (see the commit above). I am not sure if the issues you are running into are the same or if there were some regressions that happened with the recent releases. That's why I suggested creating a new issue and then we can re-evaluate things. Looks like we missed adding a milestone marker on this issue. This change was originally part of the `3.0.6.RELEASE`.
