### ISSUE TITLE
Reference and API docs links broken on project page

### ISSUE THREAD

**Issue by mwmahlberg** [spring-cloud/spring-cloud-stream-binder-kafka#927]
Both the reference and API doc links are broken on the project page from 3.0.6 onwards.

**Steps to reproduce:**

1. Go to https://cloud.spring.io/spring-cloud-stream-binder-kafka/
2. Click on either "Reference" or "API" in the sidebar for any version above 2.2.1 (as of the time of this writing)
3. You get presented github's 404 page

**Comment by sobychacko** [comment]
@mwmahlberg I think you are looking at the old links. Can you try this link? https://spring.io/projects/spring-cloud-stream

**Comment by mwmahlberg** [comment]
> @mwmahlberg I think you are looking at the old links. Can you try this link? https://spring.io/projects/spring-cloud-stream

Yes, that works — but if you jump in via google, you often get to the link I shared. Furthermore, it is strange that the „old“ links are not updated, especially when not taken down.

**Comment by sobychacko** [comment]
@mwmahlberg We will fix that discrepancy. Thanks for pointing this out.

**Comment by sobychacko** [comment]
@mwmahlberg This is now fixed.  https://cloud.spring.io/spring-cloud-stream-binder-kafka is now redirecting to the new Spring Cloud Stream project site at https://spring.io/projects/spring-cloud-stream. From there, you can navigate to the Kafka binder docs.
