### ISSUE TITLE
Incompatibility between Spring Boot 2.2.8.RELEASE and Spring-Cloud Hoxton.SR6

### ISSUE THREAD

**Issue by ferblaca** [spring-cloud/spring-cloud-stream-binder-kafka#930]
When configuring a **spring-cloud-stream-binder-kafka**  project for **kafka**'s broker with **SB 2.2.8.RELEASE** and **spring-cloud Hoxton.SR6**, I have the following exception in runtime ([full stack-trace](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/files/4878617/java.lang.NoSuchMethodError.txt)):

> java.lang.reflect.InvocationTargetException
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
>     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke (Method.java:566)
>     at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run (AbstractRunMojo.java:564)
>     at java.lang.Thread.run (Thread.java:834)
> Caused by: org.springframework.context.ApplicationContextException: Failed to start bean 'outputBindingLifecycle'; nested exception is java.lang.NoSuchMethodError: 'void org.springframework.kafka.core.DefaultKafkaProducerFactory.setBeanName(java.lang.String)

Looks like the spring-kafka version is unbalanced:

```
[INFO] +- org.springframework.cloud:spring-cloud-stream-binder-kafka:jar:3.0.6.RELEASE:compile
[INFO]    +- org.springframework.kafka:spring-kafka:jar:2.3.9.RELEASE:compile
```

The method **org.springframework.kafka.core.DefaultKafkaProducerFactory.setBeanName(java.lang.String)** appears from version **org.springframework.kafka:spring-kafka:jar:2.5.0.RC1**.

Does Spring Cloud **Hoxton.SR6** not support **SB 2.2.8.RELEASE**?

**Comment by ferblaca** [comment]
I add a project example that reproduces the problem: [demo-streams2.zip](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/files/4878876/demo-streams2.zip)

**Comment by sobychacko** [comment]
@ferblaca We will look at this and get back to you.

**Comment by garyrussell** [comment]
This capability will be restored with Boot 2.2.9; sorry for the inconvenience.

**Comment by ferblaca** [comment]
Thank you very much @garyrussell !! Does version 2.2.9 have a release date yet?

**Comment by magnus-larsson** [comment]
This page indicates that 2.2.9 is planned to be released July 23, https://github.com/spring-projects/spring-boot/milestones.

**Comment by magnus-larsson** [comment]
I did a quick test with Spring Boot 2.2.9.BUILD-SNAPSHOT and Spring-Cloud Hoxton.SR6 but got the same error:

```
The following method did not exist:

    'void org.springframework.kafka.core.DefaultKafkaConsumerFactory.setBeanName(java.lang.String)'
```

Maybe the correction is not yet in place in Spring Boot 2.2.9?

**Comment by garyrussell** [comment]
Spring Boot currently does not pull in the spring-kafka snapshot; you need to override it's version to 2.3.10.BUILD-SNAPSHOT.

**Comment by garyrussell** [comment]
@magnus-larsson ^^

**Comment by magnus-larsson** [comment]
@garyrussell: Thanks for the clarification! 

Yes, that helped! Now it works again.

From the planned milestones for spring-kafka (https://github.com/spring-projects/spring-kafka/milestones) it seems like 2.3.10 is planned to be released July 22, so it should match the release of Spring Boot 2.2.9 :-)

**Comment by garyrussell** [comment]
Yes; we generally schedule our releases for the day before Boot's so they pick us up.
