### ISSUE TITLE
Enable zstd compression type

### ISSUE THREAD

**Issue by ncheema** [spring-cloud/spring-cloud-stream-binder-kafka#932]
As the default kafka-client version is > 2.1.0, we can enable `zstd` compression under [compressionType](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka-core/src/main/java/org/springframework/cloud/stream/binder/kafka/properties/KafkaProducerProperties.java#L307-L312) enum.
Please refer to comments in [compressionType](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka-core/src/main/java/org/springframework/cloud/stream/binder/kafka/properties/KafkaProducerProperties.java#L307-L312) enum(shared below) for more details 
```java
// /** // TODO: uncomment and fix docs when kafka-clients 2.1.0 or newer is the
// default
// * zstd compression
// */
// zstd
```

**Comment by sabbyanandan** [comment]
@ncheema: It seems like an easy change; please feel free to submit a PR with tests, we can collaborate.

**Comment by ncheema** [comment]
@sabbyanandan sounds good.

**Comment by aldex32** [comment]
Hi guys,

I wanted to contribute with this small change. Please have a look.
https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/950

Cheers,
Aldo
