### ISSUE TITLE
Healthcheck not working properly when used in reactive context (Webflux)

### ISSUE THREAD

**Issue by vitjouda** [spring-cloud/spring-cloud-stream-binder-kafka#939]
When `spring-cloud-stream-binder-kafka-streams` is used within Rx context, for example with Webflux, `KafkaStreamsBinderHealthIndicator` is not working properly. This is caused by optimization which uses `ThreadLocal<Status> healthStatusThreadLocal`. Since there is fixed thread pool, if there is some error once, it gets stored into threadlocal and never cleared. Therefore subsequent checks fail randomly, based on which thread is currently used to handle given request.

I have tried to fix this by replacing `HealthIndicator `bean with one which does not use `ThreadLocal`, but I have only limited knowledge on inner workings of `spring-cloud-stream` binders and quickly found out I cannot simply register another health indicator, since each binder has its own created as a part of binder specific configuration and therefore all injected dependencies are also specific to this context. Is there any other way to temporarily fix this?

**Comment by sobychacko** [comment]
@vitjouda Thanks for this report. We were not aware of this issue when used with a reactive stack. The `ThreadLocal` usage was introduced as an optimization which is not really necessary. Removing it as a solution for this problem. Here is the [PR](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/940).

**Comment by sobychacko** [comment]
Addressed through https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/940.
