### ISSUE TITLE
Upgrade KafkaStreams API usage for InteractiveQueryService 

### ISSUE THREAD

**Issue by kyrylo-novotarskyi** [spring-cloud/spring-cloud-stream-binder-kafka#941]
Noticed that in the latest Kafka Streams Binder the [InteractiveQueryService](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/InteractiveQueryService.java#L155) uses `metadataForKey` to retrieve the HostInfo. 
Latest binder release uses [2.5.0 Kafka Streams](https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-stream-binder-kafka-streams/3.0.6.RELEASE). As per [Apache Docs](http://kafka.apache.org/25/javadoc/org/apache/kafka/streams/KafkaStreams.html#metadataForKey-java.lang.String-K-org.apache.kafka.common.serialization.Serializer-):
```
@Deprecated
public <K> StreamsMetadata metadataForKey(String storeName,
                                                      K key,
                                                      Serializer<K> keySerializer)
Deprecated. Since 2.5. Use queryMetadataForKey(String, Object, Serializer) instead.
```

Would appreciate if interfaces would be upgraded to use `queryMetadataForKey` to align the consumption of the `StreamsMetadataState` API. There's been quite a few changes in the way MetadataState is managed/exposed lately, which could benefit our use-case. Right now we've decided to make our own  `InteractiveQueryService` wrapper, which has its implications (like the package-private `KafkaStreamsRegistry` interface), resulting in a series of direct `KafkaStreams` access points.  
Not sure how large is the demand for such a change, so would mark it as an `enhancement` proposal rather than anything else.

**Comment by sobychacko** [comment]
@kyrylo-novotarskyi Sounds good to me as potential enhancements. See my comments [here](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/942#issuecomment-666708869).

**Comment by sobychacko** [comment]
@kyrylo-novotarskyi The deprecated API is updated to use the correct one. See the commit mentioned above. The same change is [backported](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/82b19555a116e7b1b72a119f46b2894a1f7e021f) to `3.0.x` branch. 

Another API method is introduced to access the `KeyQueryMetadata` in `InteractiveQueryService`.
