### ISSUE TITLE
Misconfigured Kafka Micrometer for MultiBinder

### ISSUE THREAD

**Issue by ncheema** [spring-cloud/spring-cloud-stream-binder-kafka#943]
## Issue
[KafkaBinderMetricsConfigurationWithMultiBinder.KafkaMicrometer](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/config/KafkaBinderConfiguration.java#L242) is not being loaded for multi binder configuration. 

## Root Cause
In MultiBinder configuration  `MeterRegistery`  is loaded in the `outterContext`, hence the 
[@ConditionalOnBean(MeterRegistry.class)](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/config/KafkaBinderConfiguration.java#L241) is not a valid condition for `MultiBinder.KafkaMicrometer`.

## Possible Solution
Remove the `@ConditionalOnBean(MeterRegistry.class)` from [MultiBinder.KafaMicroMeter](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/config/KafkaBinderConfiguration.java#L241).

**Comment by sobychacko** [comment]
@ncheema Thanks for the report. Feel free to send a PR with the fix in.

**Comment by sobychacko** [comment]
This is addressed through the PR https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/34c4efb35c854801d5b675809187711cebefd618.
