### ISSUE TITLE
Verify Micrometer instrumentation for Kafka Streams with Spring Boot 2.3.x 

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-kafka#949]
- Test it end-to-end with channel-based binder and as well as Kstreams binder
- Document findings/gaps
- Update ref. guide with a sample (or maybe move it to SCSt samples repo)

**Comment by sobychacko** [comment]
Verified that Kafka Streams metrics are generated and exported to Prometheus using Micrometer instrumentation. [Here](https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/kafka-streams-samples/kafka-streams-metrics-demo) is a sample application that explains how this is done using Micrometer and Prometheus. This [README](https://github.com/spring-cloud/spring-cloud-stream-samples/blob/master/kafka-streams-samples/kafka-streams-metrics-demo/README.adoc) has relevant details of the steps needed to run this sample application.
