### ISSUE TITLE
KafkaMessageChannelBinder sets retries to 0

### ISSUE THREAD

**Issue by marbon87** [spring-cloud/spring-cloud-stream-binder-kafka#952]
In https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/5b3b92cdb9237e8a64707d4bd1395e9d97e90551/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java#L495 
retries for the producer is set to 0.
The default from kafka is MAX_INT (https://docs.confluent.io/current/installation/configuration/producer-configs.html#retries)

If there is no good reason to override the default from kafka, the configuration in KafkaMessageChannelBinder should be removed.

**Comment by garyrussell** [comment]
https://gitter.im/spring-cloud/spring-cloud-stream?at=5f3be18a750a27413029c0ca

**Comment by garyrussell** [comment]
The `BUFFER_MEMORY_CONFIG` setting looks suspicious too - it is currently the same as the default https://kafka.apache.org/documentation/#buffer.memory and unnecessary.
