### ISSUE TITLE
Clarification on autoCreateTopics

### ISSUE THREAD

**Issue by jeeftor** [spring-cloud/spring-cloud-stream-binder-kafka#954]
In our testing we have our broker setup so that `auto.create.topics` is false and we noticed that our java apps using Spring were still creating topics.

Reading through the documentation on: **spring.cloud.stream.kafka.binder.autoCreateTopics** it says:

> This setting is independent of the `auto.create.topics.enable` setting of the broker and does not influence it. If the server is set to auto-create topics, they may be created as part of the metadata retrieval request, with default broker settings.

What we are seeing in our testing is:

|kafka|spring|result|
|--|--|--|
|auto.create.topics=false|spring.cloud.stream.kafka.binder.autoCreateTopics=true|Makes new topics|
|auto.create.topics=false|spring.cloud.stream.kafka.binder.autoCreateTopics=unset (defaults to true)|Makes new topics|
|auto.create.topics=false|spring.cloud.stream.kafka.binder.autoCreateTopics=false|Does not Make new topics|

Is this really correct behavior? It seems the client should respect the broker setting ... no?

Thanks

**Comment by garyrussell** [comment]
What version are you using?

I get

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'spring.cloud.stream.kafka.binder.auto-create-topics' to boolean:

    Property: spring.cloud.stream.kafka.binder.auto-create-topics
    Value: unset
    Origin: class path resource [application.properties]:9:53
    Reason: failed to convert java.lang.String to boolean

Action:

Update your application's configuration
```

>It seems the client should respect the broker setting ... no?

There is no client API to detect the broker configuration for that property.

**Comment by jeeftor** [comment]
<img width="272" alt="image" src="https://user-images.githubusercontent.com/6491743/91084786-c1e00680-e609-11ea-9bee-7136f42e6b7d.png">

**Comment by garyrussell** [comment]
>`spring.cloud.stream.kafka.binder.autoCreateTopics=unset `

I assumed you meant that you set the property to `unset` but perhaps you meant to say that you didn't set it at all?

In that case, it's working as designed - as I said there is no way for the client to tell what the broker setting is.

**Comment by jeeftor** [comment]
Gotcha -> so if its not set defaults to true, if unset throws an error?
