### ISSUE TITLE
Duplicate messages while consuming events from kafka enabled azure event hub

### ISSUE THREAD

**Issue by deb-amit-84** [spring-cloud/spring-cloud-stream-binder-kafka#959]
Hi All,
I am getting duplicate messages while consuming events from kafka enabled azure event hub.
we are doing load testing with around 30k messages,All these 30k messages are first consumed at our side from external source system on confluent kafka and then we do data processing/transformation and send it to our internal kafka topics on azure(kafka enabled azure event hub) from where our downstream applications consume these messages.
We are able to consume messages(>30K) with no issue from confluent kafka, but once data transformation is done and these messages are sent to event hub topic for downstream applications to consume, thats where we observed that for incoming messages with volumes(around >400 msgs) , messages are getting reprocessed(duplicated) even after manual acknowledgement of each record at the consumer side.
Our java service are using spring cloud stream kafka dependencies:

<groupId>org.springframework.cloud</groupId>
<artifactId>spring-cloud-dependencies</artifactId>
<version>Hoxton.RELEASE</version>

<groupId>org.springframework.cloud</groupId>
<artifactId>spring-cloud-starter-stream-kafka</artifactId>
<version>3.0.0.RELEASE</version>

for consuming messages. as mentioned in earlier posts the issue happened for two consumers in a consumer group, but in our case its one topic and one consumer in a consumer group, still getting duplicate messages .
I see there is already a issue opened : https://github.com/Azure/azure-event-hubs-java/issues/339, but discussion was not concluded. 
can anyone let me know if this is an issue with cloud stream kafka or azure event hub? i do not think this is problem with cloud stream kafka as we are able to consume messages from confluent kafka , something to do with azure event hub.
would appreciate if someone can help.

**Comment by sobychacko** [comment]
@deb-amit-84 Nothing comes to mind why it is consuming duplicate messages randomly. It does not look like a binder related issue. Do you have any updates as to what might be causing this?

**Comment by sobychacko** [comment]
@deb-amit-84 Closing the issue as we cannot think of any binder scenario that may cause this. Please feel free to re-open if you find any binder issues related to this.
