### ISSUE TITLE
Support supplying custom destination resolver when sending to DLQ

### ISSUE THREAD

**Issue by sdobberstein** [spring-cloud/spring-cloud-stream-binder-kafka#966]
With the way the "sendToDlq" works today, you have two options:
1) Specify a DLQ name and that is used.
2) Don't specify a DLQ name and instead it defaults to ```error.<topic>.<group>```

It would be nice if there was a way to supply your own custom destination resolver instead.

**Example use cases:**  
1) I would like to be able to route to different topics based on the type of exception.  Serialization errors to one topic for example, and networking/code errors to another topic.
2) I would like to be able to route to different topics based on values within the headers.  For example, I might store the retry count as a header.  Until you hit a certain number of retries route it to "topic a", but once you hit some threshold then route it to "topic b".

**Comment by sdobberstein** [comment]
Here is a link to the relevant code where the destination resolver is currently being defined:
https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/7bebe9b78fd5c53aba45e1160c29932a5216de30/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/KafkaStreamsBinderUtils.java#L105-L126

**Comment by sobychacko** [comment]
@sdobberstein Are you asking for customizing the DLQ name when the binder tries to resolve the destination for the DLQ based on some criteria in the `ConsumerRecord` or the exception? That is the impression I am getting from the request. If we resort to this, then how the partition function is applied is completely up to the user-provided destination resolver function. Also, in the Kafka Streams binder, the only error that we support in the context of sending to DLQ is any deserialization errors. Any other type of errors such as logic related must be addressed in the application explicitly and automatic DLQ handling won't work there. With that said, this sounds like a reasonable enhancement to add to the binder. Are you interested in contributing a patch for this as a PR?
