### ISSUE TITLE
When using kstream with actuator in the classpath application never exits in case of exceptions

### ISSUE THREAD

**Issue by lyogev** [spring-cloud/spring-cloud-stream-binder-kafka#974]
Using spring boot 2.3.4 I have a simple kstream application that I wanted to check how it handles exceptions.
So when I throw a runtimeexception from the application code, it just hangs.
After removing:
```implementation 'org.springframework.boot:spring-boot-starter-actuator'``` from gradle, it exits as it should.
To overcome this I had to write this code:
```
    @Bean
    public StreamsBuilderFactoryBeanCustomizer customizer() {
        return fb -> {
            fb.setUncaughtExceptionHandler((thread, throwable) -> {
                // Fix a bug when actuator is in the classpath that causes the stream to never shut down
                int exitCode = SpringApplication.exit(context, () -> 1);
                System.exit(exitCode);
            });
        };
    }
```
And now it's at least shutting down, but I'm still getting this in the log:
```
14:43:34.549  INFO State transition from ERROR to PENDING_SHUTDOWN
14:43:34.551  INFO Informed to shut down
14:43:44.553  INFO Streams client cannot stop completely within the timeout
```

It looks like the streams thread is unable to shut down when actuator is running.
I tried disabling the health indicator but it doesn't seem to work:
```
management:
  endpoint:
    health:
      enabled: false
```

Maybe this class somehow interferes with the shutdown:
https://github.com/spring-projects/spring-boot/blob/v2.3.4.RELEASE/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/KafkaMetricsAutoConfiguration.java

**Comment by lyogev** [comment]
Thanks! this works much better!
So how can we get this issue fixed? should I open another issue in micrometer? spring boot actuator?

**Comment by sobychacko** [comment]
@lyogev Could you open an issue in micrometer? You can point to this issue as a reference.

**Comment by sobychacko** [comment]
@lyogev Closing this issue now. Feel free to refer to this issue when you create the issue in Micrometer.
