### ISSUE TITLE
Move ConfluentSchemaRegistryClient from spring-cloud/spring-cloud-schema-registry

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-kafka#979]
The goal here is to bring `ConfluentSchemaRegistryClient` closer to the Kafka binder, so it is easy for users to costume, and one less dependency to worry about.

**Comment by sobychacko** [comment]
We are going to keep the schema registry code unmoved from its [current location](https://github.com/spring-cloud/spring-cloud-schema-registry) for 3.1. Post 3.1, we might consider moving it and isolating it to the Kafka binder, but that needs further consideration of a few moving targets. Closing this issue now. We will create more issues or an epic in the due course for further such actions.
