### ISSUE TITLE
KafkaStreamBrancher - How to direct to multiple topics?

### ISSUE THREAD

**Issue by uselvvi** [spring-cloud/spring-cloud-stream-binder-kafka#984]
The below code creates couple of branches which can be directed to 2 different Kafka topic.

```
kstream.branch(predicate1 , predicate2)
```
Spring cloud stream does that automatically which is cool.
```
spring.cloud,.stream.bindings.[something].out-0.destination
spring.cloud,.stream.bindings.[something].out-1.destination
```

Do we have any support for this If I use `KafkaStreamBrancher`?

**Comment by sobychacko** [comment]
@uselvvi When you are using `KafkaStreamBrancher`, the application is responsible for sending to a topic using its consumer (in addition to providing the `Predicate`). In the context of a binder app, when using the branching feature, it is usually used as the last operation. When using `KafkaStreamBrancher`, it gives you the ability to continue operations. 

You can still use `KafkaStreamBrancher` in a Spring Cloud Stream application, however, you need to send to the destinations manually by providing a `Consumer` and then continue with the resultant `KStream`.

**Comment by uselvvi** [comment]
@sobychacko Yes, I know that I could pass the stream to destination via code level. But I wanted to know if there is any config which I am missing. 
Understood now. Thanks @sobychacko .

**Comment by uselvvi** [comment]
@sobychacko 
Could you please clarify this?
https://github.com/spring-cloud/spring-cloud-stream-samples/issues/197
