### ISSUE TITLE
Broken documentation link (1.4. Error Channels)

### ISSUE THREAD

**Issue by abdullahly** [spring-cloud/spring-cloud-stream-binder-kafka#986]
Section [1.4. Error Channels](url), has a broken reference link: 

See [spring-cloud-stream-overview-error-handling] for more information. 

This just links to the top of the documentation page. 

I've set the following property to enable the error channel for async producer failures. I'm currently looking for a way to unit test/trigger failures. 

`spring.cloud.stream.bindings.default.producer.error-channel-enabled=true`

**Comment by sobychacko** [comment]
@abdullahly The broken documentation link is now fixed.
