### ISSUE TITLE
How can I disable the creation of the "KafkaBinderMetrics" bean from "KafkaBinderConfiguration" Configuration for a multi-binder context?

### ISSUE THREAD

**Issue by ferblaca** [spring-cloud/spring-cloud-stream-binder-kafka#995]
Spring-Boot v2.4.0
Spring-Cloud-Stream-Binder-Kafka v3.1.0-M4

When configuring a multi-binder project, we are not able to disable the creation of the **KafkaBinderMetrics** bean in the **KafkaBinderConfiguration**.

The problem is that in **KafkaBinderMetrics**, for each **BindingCreatedEvent** event, it forces the creation of a consumer to obtain the value of the messages of the topic in order to send the metric **spring.cloud.stream.binder.kafka.offset** with the cost that it implies, and in our case we do not need this metric.

Would it be possible to consider the possibility of disabling the creation of the  **KafkaBinderMetrics** bean from the **KafkaBinderConfiguration**?

**Comment by sobychacko** [comment]
@ferblaca Do you have `Micrometer` in the classpath? If the application does not have this (possibly through Spring Boot actuator), then the `KafkaBinderMetrics` bean will not be created.  See [this](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/config/KafkaBinderConfiguration.java#L232). 

If that is not an option, then you can try override `KafkaBinderMetrics` without the costly calls and provide a bean for that in the application. Binder will not create the bean if it sees one from the application. See [this](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/config/KafkaBinderConfiguration.java#L231).

If neither of these options work, let us know, we can probably come up with some solutions in the binder.

**Comment by garyrussell** [comment]
You can also add a `MeterFilter` to the registry to suppress the creation of those meters - the consumer is only created the first time the meter is measured.

https://micrometer.io/docs/concepts#_meter_filters

**Comment by ferblaca** [comment]
hello @sobychacko, for a mono-binder context, with an AutoConfiguration that is configured before KafkaBinderConfiguration if we are able to create a KafkaBinderMetrics bean with the desired behaviour. But for a multi-binder context, the KafkaBinderConfiguration is always loaded first, and therefore we cannot create our KafkaBinderMetrics bean (We have attached an example application with what we have told you: [demo-streams-metrics-with-multibinder.zip](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/files/5642179/demo-streams-metrics-with-multibinder.zip)).

On the other hand, @Gary, if we could add a filter to avoid the metric, but equally the bean KafkaBinderMetrics would be creating a consumer for each binding...

**Comment by garyrussell** [comment]
>but equally the bean KafkaBinderMetrics would be creating a consumer for each binding...

@sobychacko - that's a bug in the `KafkaBinderMetrics` cause by https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/965

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/5a7cc9f257374989df7f3862d7009cac34d4a3f4/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderMetrics.java#L127-L135

We need to check if the return type from the `register()` is a `NoopGauge` and don't schedule the task in that case.

Then this

```java
@Component
class NoOpConsumerMeters {

	NoOpConsumerMeters(MeterRegistry registry) {
		registry.config().meterFilter(
				MeterFilter.denyNameStartsWith("spring.cloud.stream.binder.kafka.offset"));
	}

}
```

would work (I also tested it with multi-binder support).

**Comment by ferblaca** [comment]
> hello @sobychacko, for a mono-binder context, with an AutoConfiguration that is configured before KafkaBinderConfiguration if we are able to create a KafkaBinderMetrics bean with the desired behaviour. But for a multi-binder context, the KafkaBinderConfiguration is always loaded first, and therefore we cannot create our KafkaBinderMetrics bean (We have attached an example application with what we have told you: demo-streams-metrics-with-multibinder.zip).

For this, there is a way that in a multi-binder context we can define a configuration that starts before the KafkaBinderConfiguration and be able to define our KafkaBinderMetrics bean first?
