### ISSUE TITLE
Suggestion: Possibility to customize the value of the client.id property for consumer and producers factories

### ISSUE THREAD

**Issue by ferblaca** [spring-cloud/spring-cloud-stream-binder-kafka#996]
When configuring a spring cloud stream project with Kafka's binder, and the input type bindings (consumers) have no group established, the client.id value is set to "anonymous. + UUID.randomUUID()".

This can pose a **problem for the collection of micrometer metrics,** as each time the application is deployed, the value of client.id will be different.

It is possible to use ExtendedBindingProperties and add in the configuration for ConsumerProperties and ProducerProperties a static value for the "client.id", but doing that for each binding is very rigid.

Would it be possible to consider creating a customiser, a SpEL, or simply be able to add the name of the binding channel to the client.id in a configurable way?  In this way it would be possible to establish a configurable but unique value for each binding so that it always has the same value even if the application is deployed several times or scales in several PODs, so that the metrics can be grouped correctly.

**Comment by garyrussell** [comment]
You can do this today by adding a `ListenerContainerCustomizer` `@Bean`:

```java
@SpringBootApplication
public class Kbgh996Application {

	public static void main(String[] args) {
		SpringApplication.run(Kbgh996Application.class, args);
	}

	@Bean
	Consumer<String> consume() {
		return System.out::println;
	}

	@Bean
	ListenerContainerCustomizer<AbstractMessageListenerContainer<?, ?>> customizer() {
		return (container, dest, group) -> container.getContainerProperties().setClientId(dest);
	}

}
```

```
2020-12-02 13:35:00.713  INFO 3174 --- [ask-scheduler-1] o.a.k.clients.consumer.ConsumerConfig    : ConsumerConfig values: 
	allow.auto.create.topics = true
	auto.commit.interval.ms = 100
	auto.offset.reset = latest
	bootstrap.servers = [localhost:9092]
	check.crcs = true
	client.dns.lookup = use_all_dns_ips
	client.id = consume-in-0-0
        ...
```

(`consume-in-0-0` here because I didn't specify a destination in the YAML).

**Comment by ferblaca** [comment]
Thanks @garyrussell , it is very helpful for the container listener to modify the client.id of the **consumers** and establish a value that identifies in the metrics where it comes from (e.g. destination + group). It would be great if you could establish the name of the binding.

However, something similar happens to us for **producers**, which although they don't have group and in random UUID problem, it would be nice to give the value of the destinationName or bindingName to the client.id.... We have been seeing the use of the ProducerMessageHandlerCustomizer for this although it is not its purpose...

**Comment by garyrussell** [comment]
Yes, I think the (new since 3.0.9) `ProducerConfigCustomizer` should be changed to pass in the binding name and destination so you can tell which binding it is being called for.

We should also look at adding the binding name to the container customizer.
